# -*- coding: utf-8 -*-
# Goethe C1 Verbs Batch 3 (Items 201 - 300)

BATCH_3 = [
  ("erdulden", "Psychologie & Kognition", "Gehoben",
   "Schmerzen, Unterdrückung oder Unrecht geduldig ertragen", "To endure, suffer, brook or bear patiently",
   "Unrecht / Schmerzen erdulden", ["ertragen", "aushalten"],
   "Die Bevölkerung musste jahrzehntelang tyrannische Willkür erdulden.",
   "Die Bevölkerung musste jahrzehntelang tyrannische Willkür [...].",
   "The populace had to endure tyrannical arbitrariness for decades."),

  ("erfordern", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Als unausweichliche Voraussetzung verlangen", "To require, demand, call for or necessitate",
   "höchste Konzentration / Mut erfordern", ["bedingen", "voraussetzen"],
   "Die Durchführung der Operation erfordert äußerste Präzision und Ruhe.",
   "Die Durchführung der Operation [...] äußerste Präzision und Ruhe.",
   "Performing the operation requires utmost precision and composure."),

  ("ergründen", "Wissenschaft & Forschung", "Gehoben",
   "Die tiefere Ursache oder das Wesen eines Phänomens erforschen", "To fathom, plumb or fathom the depths of a question",
   "die Ursachen / das Wesen ergründen", ["erforschen", "durchdringen"],
   "Philosophen versuchten seit Jahrhunderten, das Rätsel des Bewusstseins zu ergründen.",
   "Philosophen versuchten seit Jahrhunderten, das Rätsel des Bewusstseins zu [...].",
   "Philosophers have attempted for centuries to fathom the enigma of consciousness."),

  ("erhellen", "Wissenschaft & Forschung", "Gehoben",
   "Licht ins Dunkel bringen oder einen Sachverhalt verständlich machen", "To illuminate, shed light upon or clarify",
   "einen Sachverhalt / das Dunkel erhellen", ["aufklären", "verdeutlichen"],
   "Die Entdeckung alter Manuskripte erhellt die Hintergründe der Reformation.",
   "Die Entdeckung alter Manuskripte [...] die Hintergründe der Reformation.",
   "The discovery of ancient manuscripts illuminates the background of the Reformation."),

  ("erhoffen von", "Psychologie & Kognition", "Bildungssprachlich",
   "Mit Zuversicht ein positives Resultat erwarten", "To hope for, look for or anticipate from",
   "sich Besserung erhoffen von + Dat.", ["erwarten", "herbeisehnen"],
   "Von den neuen Verhandlungen erhofft sich die Diplomatie den Durchbruch.",
   "Von den neuen Verhandlungen [...] sich die Diplomatie den Durchbruch.",
   "Diplomacy hopes for a breakthrough from the renewed negotiations."),

  ("erkennen an", "Psychologie & Kognition", "Bildungssprachlich",
   "Jemanden oder etwas an bestimmten Merkmalen identifizieren", "To recognize, identify or discern by a hallmark",
   "erkennen an + Dat.", ["identifizieren", "wahrnehmen"],
   "Man erkennt einen versierten Redner an seiner rhetorischen Gelassenheit.",
   "Man [...] einen versierten Redner an seiner rhetorischen Gelassenheit.",
   "One recognizes an accomplished speaker by his rhetorical composure."),

  ("erklimmen", "Psychologie & Kognition", "Gehoben",
   "Einen steilen Gipfel besteigen oder die Karriereleiter aufsteigen", "To scale, clamber up or climb the career ladder",
   "den Gipfel / die Karriereleiter erklimmen", ["besteigen", "aufsteigen"],
   "Durch unermüdlichen Fleiß erklimmt sie die oberste Führungsriege.",
   "Durch unermüdlichen Fleiß [...] sie die oberste Führungsriege.",
   "Through tireless diligence she is scaling the top management echelon."),

  ("erlangen", "Gesellschaft & Politik", "Gehoben",
   "Nach hartem Streben ein hohes Ziel oder Ruhm erreichen", "To attain, acquire, gain or achieve prestige/diploma",
   "Ruhm / die Hochschulreife erlangen", ["erwerben", "erringen"],
   "Erst nach Jahren harter Studien erlangte er die Approbation als Facharzt.",
   "Erst nach Jahren harter Studien [...] er die Approbation als Facharzt.",
   "Only after years of arduous study did he attain medical board certification."),

  ("erlassen", "Recht & Verwaltung", "Formell",
   "Ein Gesetz amtlich verkünden oder jemandem eine Strafe schenken", "To enact a decree or remit/waive a fine",
   "ein Gesetz / ein Dekret erlassen", ["beschließen", "dekretieren"],
   "Das Parlament erließ ein wegweisendes Gesetz zum Schutz von Whistleblowern.",
   "Das Parlament [...] ein wegweisendes Gesetz zum Schutz von Whistleblowern.",
   "Parliament enacted groundbreaking legislation protecting whistleblowers."),

  ("erläutern", "Kommunikation & Diskurs", "Bildungssprachlich",
   "Einen komplexen Zusammenhang ausführlich und verständlich erklären", "To elucidate, expound upon, explain or clarify",
   "die Zusammenhänge ausführlich erläutern", ["erklären", "darlegen"],
   "Die Dozentin erläuterte die Quantentheorie anhand anschaulicher Analogien.",
   "Die Dozentin [...] die Quantentheorie anhand anschaulicher Analogien.",
   "The lecturer elucidated quantum theory by means of vivid analogies."),

  ("erleichtern", "Psychologie & Kognition", "Bildungssprachlich",
   "Eine schwierige Aufgabe bequemer machen oder Sorgen mindern", "To facilitate, alleviate, ease or lighten a burden",
   "die Arbeit / das Gewissen erleichtern", ["vereinfachen", "entlasten"],
   "Moderne Übersetzungswerkzeuge erleichtern den Arbeitsalltag ungemein.",
   "Moderne Übersetzungswerkzeuge [...] den Arbeitsalltag ungemein.",
   "Modern translation tools immensely facilitate daily work routine."),

  ("ermächtigen zu", "Recht & Verwaltung", "Formell",
   "Jemandem offiziell und juristisch die Vollmacht erteilen", "To authorize, empower or mandate someone to act",
   "ermächtigen zu + Dat.", ["autorisieren", "bevollmächtigen"],
   "Die Vollmacht ermächtigt den Anwalt zur Entgegennahme aller Bescheide.",
   "Die Vollmacht [...] den Anwalt zur Entgegennahme aller Bescheide.",
   "The power of attorney empowers the lawyer to accept all official rulings."),

  ("ermahnen zu", "Psychologie & Kognition", "Bildungssprachlich",
   "Jemanden nachdrücklich an seine Pflichten oder Disziplin erinnern", "To admonish, exhort or urge towards compliance",
   "ermahnen zu + Dat.", ["anhalten zu", "auffordern"],
   "Die Vorsitzende ermahnte die Fraktionen zu mehr Mäßigung im Ton.",
   "Die Vorsitzende [...] die Fraktionen zu mehr Mäßigung im Ton.",
   "The chairperson admonished the factions to show greater moderation in tone."),

  ("ermessen", "Psychologie & Kognition", "Gehoben",
   "Die volle Tragweite oder Dimension eines Schadens begreifen", "To gauge, assess, measure or fathom the scale of an event",
   "die Tragweite / die Folgen ermessen", ["begreifen", "abschätzen"],
   "Niemand vermag derzeit das volle Ausmaß der Klimaschäden zu ermessen.",
   "Niemand vermag derzeit das volle Ausmaß der Klimaschäden zu [...].",
   "Nobody is currently able to gauge the full scale of climate devastation."),

  ("ermitteln", "Recht & Verwaltung", "Formell",
   "Polizeilich nach Tätern fahnden oder Werte mathematisch berechnen", "To investigate, ascertain or calculate data",
   "die Täter / den Wert ermitteln", ["recherchieren", "berechnen"],
   "Die Kriminalpolizei ermittelt wegen des dringenden Verdachts auf Untreue.",
   "Die Kriminalpolizei [...] wegen des dringenden Verdachts auf Untreue.",
   "The criminal investigation department is investigating suspicion of embezzlement."),

  ("ermöglichen", "Wirtschaft & Arbeit", "Bildungssprachlich",
   "Die materiellen oder rechtlichen Voraussetzungen für etwas schaffen", "To enable, make possible, facilitate or permit",
   "den Zugang / die Teilhabe ermöglichen", ["erlauben", "bahnen"],
   "Stipendien ermöglichen begabten Studierenden ein sorgenfreies Studium.",
   "Stipendien [...] begabten Studierenden ein sorgenfreies Studium.",
   "Scholarships enable talented students to pursue worries-free university studies."),

  ("ermuntern zu", "Psychologie & Kognition", "Bildungssprachlich",
   "Jemandem freundlich Mut zu einer Tat oder Initiative machen", "To encourage, animate or hearten someone to act",
   "ermuntern zu + Dat.", ["anspornen", "ermutigen"],
   "Die Mentorin ermunterte die Jungforscherin, ihre Thesen zu publizieren.",
   "Die Mentorin [...] die Jungforscherin, ihre Thesen zu publizieren.",
   "The mentor encouraged the junior researcher to publish her theses."),

  ("ernüchtern", "Psychologie & Kognition", "Bildungssprachlich",
   "Von Illusionen oder naiver Begeisterung auf den Boden der Tatsachen holen", "To sober up, disillusion or bring back to harsh reality",
   "die Realität ernüchtert", ["enttäuschen", "desillusionieren"],
   "Die katastrophalen Wahlergebnisse ernüchterten die Parteiführung zutiefst.",
   "Die katastrophalen Wahlergebnisse [...] die Parteiführung zutiefst.",
   "The catastrophic election returns deeply sobered up the party leadership."),

  ("erörtern", "Kommunikation & Diskurs", "Bildungssprachlich",
   "Eine Streitfrage sachlich, gründlich und von allen Seiten diskutieren", "To discuss, debate, canvass or treat an issue exhaustively",
   "eine Streitfrage / Thesen ausführlich erörtern", ["debattieren", "diskutieren"],
   "In der Klausurtagung erörterte das Gremium neue energiepolitische Optionen.",
   "In der Klausurtagung [...] das Gremium neue energiepolitische Optionen.",
   "In the closed retreat, the committee discussed new energy policy options."),

  ("erproben", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Eine neue Methode oder Technik in der Praxis auf Tauglichkeit testen", "To test, try out or pilot a new technology/procedure",
   "eine Methode / Technik in der Praxis erproben", ["testen", "pilotieren"],
   "Das neuartige Impfverfahren wird derzeit an Freiwilligen erprobt.",
   "Das neuartige Impfverfahren wird derzeit an Freiwilligen [...].",
   "The novel vaccination procedure is currently being tested on volunteers."),

  ("errechnen", "Wissenschaft & Forschung", "Fachsprachlich",
   "Einen mathematischen Wert durch exakte Berechnungen ermitteln", "To calculate, compute, work out or figure mathematically",
   "den Durchschnitt / den Korridor errechnen", ["kalkulieren", "berechnen"],
   "Die Statistiker errechneten einen dramatischen Anstieg der Lebenshaltungskosten.",
   "Die Statistiker [...] einen dramatischen Anstieg der Lebenshaltungskosten.",
   "Statisticians computed a dramatic increase in living costs."),

  ("errichten", "Gesellschaft & Politik", "Formell",
   "Ein monumentales Bauwerk bauen oder eine Institution ins Leben rufen", "To erect, construct a building or establish an institution",
   "ein Denkmal / eine Stiftung errichten", ["gründen", "bauen"],
   "Die Bundesregierung errichtete eine Stiftung zur Förderung erneuerbarer Energien.",
   "Die Bundesregierung [...] eine Stiftung zur Förderung erneuerbarer Energien.",
   "The federal government established a foundation for promoting renewable energies."),

  ("erschließen", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Neue Rohstoffvorkommen zugänglich machen oder Texte deduzieren", "To tap into resources, develop terrain or decode meanings",
   "neue Märkte / Vorkommen erschließen", ["zugänglich machen", "öffnen"],
   "Der Konzern versucht, neue Absatzmärkte in Lateinamerika zu erschließen.",
   "Der Konzern versucht, neue Absatzmärkte in Lateinamerika zu [...].",
   "The corporation is trying to tap into new sales markets in Latin America."),

  ("erschöpfen", "Psychologie & Kognition", "Bildungssprachlich",
   "Kräfte völlig aufbrauchen oder ein Thema erschöpfend behandeln", "To exhaust, deplete energy/funds or treat a topic exhaustively",
   "Kräfte / die Mittel erschöpfen sich", ["aufbrauchen", "ermüden"],
   "Nach dem Marathonlauf waren die physischen Reserven der Athleten erschöpft.",
   "Nach dem Marathonlauf waren die physischen Reserven der Athleten [...].",
   "After the marathon, the athletes' physical reserves were exhausted."),

  ("erschweren", "Gesellschaft & Politik", "Bildungssprachlich",
   "Einen Ablauf durch Hürden komplizierter und mühsamer machen", "To complicate, impede, hinder or make more difficult",
   "die Verhandlungen / den Alltag erschweren", ["behindern", "komplizieren"],
   "Mangelnde Sprachkenntnisse erschweren die gesellschaftliche Integration erheblich.",
   "Mangelnde Sprachkenntnisse [...] die gesellschaftliche Integration erheblich.",
   "Inadequate language skills significantly impede social integration."),

  ("ersinnen", "Psychologie & Kognition", "Gehoben",
   "Mit schöpferischer Fantasie einen raffinierten Plan oder Trick ausdenken", "To devise, concoct, contrive or invent a clever scheme",
   "einen Plan / eine List ersinnen", ["ausdenken", "austüfteln"],
   "Der Stratege ersann einen genialen Schachzug, um die Konkurrenz zu überlisten.",
   "Der Stratege [...] einen genialen Schachzug, um die Konkurrenz zu überlisten.",
   "The strategist devised an ingenious move to outwit the competition."),

  ("erstatten", "Recht & Verwaltung", "Formell",
   "Offiziell Bericht erstatten oder Kosten zurückzahlen", "To reimburse expenses or lodge/file a criminal complaint",
   "Bericht erstatten; Anzeige erstatten", ["berichten", "zurückzahlen"],
   "Das Opfer erstattete unverzüglich Anzeige gegen die unbekannten Täter.",
   "Das Opfer [...] unverzüglich Anzeige gegen die unbekannten Täter.",
   "The victim promptly filed a criminal complaint against unknown perpetrators."),

  ("ertappen bei", "Recht & Verwaltung", "Bildungssprachlich",
   "Jemanden auf frischer Tat bei einem Vergehen überraschen", "To catch red-handed or catch someone in the act of",
   "ertappen bei + Dat.", ["erwischen", "überführen"],
   "Der Wachdienst ertappte den Spion beim Fotografieren geheimer Akten.",
   "Der Wachdienst [...] den Spion beim Fotografieren geheimer Akten.",
   "The security guard caught the spy red-handed photographing secret files."),

  ("erübrigen", "Psychologie & Kognition", "Gehoben",
   "Etwas überflüssig machen oder sich Zeit/Geld absparen", "To render superfluous, obviate or spare time/expense",
   "sich erübrigen; Geld erübrigen", ["überflüssig sein", "ersparen"],
   "Durch die eindeutigen DNA-Beweise erübrigte sich jede weitere Zeugenaussage.",
   "Durch die eindeutigen DNA-Beweise [...] sich jede weitere Zeugenaussage.",
   "Clear DNA evidence rendered any further witness testimony superfluous."),

  ("erwägen", "Psychologie & Kognition", "Bildungssprachlich",
   "Eine Option oder Alternative gedanklich gründlich prüfen", "To consider, contemplate or weigh up an alternative",
   "einen Schritt / Alternativen erwägen", ["überlegen", "abwägen"],
   "Das Management erwägt ernsthaft, die Produktionsstätte ins Ausland zu verlegen.",
   "Das Management [...] ernsthaft, die Produktionsstätte ins Ausland zu verlegen.",
   "Management is seriously considering relocating the production site abroad."),

  ("erweitern", "Wirtschaft & Arbeit", "Formell",
   "Das Sortiment, Wissen oder Territorium vergrößern", "To expand, broaden, augment or enlarge range/knowledge",
   "den Horizont / das Angebot erweitern", ["ausbauen", "vergrößern"],
   "Die Universität erweitert ihr Studienangebot um moderne Studiengänge für KI.",
   "Die Universität [...] ihr Studienangebot um moderne Studiengänge für KI.",
   "The university is broadening its academic program with modern AI courses."),

  ("erwirken", "Recht & Verwaltung", "Formell",
   "Durch juristische Anträge einen Beschluss oder Schutz erreichen", "To obtain, secure or procure a legal injunction/order",
   "eine einstweilige Verfügung erwirken", ["durchsetzen", "erlangen"],
   "Der Medienanwalt erwirkte eine einstweilige Verfügung gegen die Berichterstattung.",
   "Der Medienanwalt [...] eine einstweilige Verfügung gegen die Berichterstattung.",
   "The media lawyer secured an injunction against the press coverage."),

  # FLANKIEREN / FUNGIEREN / ETC (233-255)
  ("flankieren", "Gesellschaft & Politik", "Bildungssprachlich",
   "Eine Hauptmaßnahme durch unterstützende Begleitmaßnahmen absichern", "To flank, accompany or underpin a core policy",
   "eine Reform durch Maßnahmen flankieren", ["begleiten", "stützen"],
   "Die Steuerreform muss durch gezielte Sozialhilfen flankiert werden.",
   "Die Steuerreform muss durch gezielte Sozialhilfen [...] werden.",
   "The tax reform must be flanked by targeted social welfare measures."),

  ("fungieren als", "Gesellschaft & Politik", "Bildungssprachlich",
   "Eine offizielle Rolle, Funktion oder Vermittlerstelle ausüben", "To function as, act as or serve in the capacity of",
   "fungieren als + Nom.", ["dienen als", "agieren als"],
   "In dem komplexen Handelsstreit fungierte die Schweiz als neutraler Schlichter.",
   "In dem komplexen Handelsstreit [...] die Schweiz als neutraler Schlichter.",
   "In the complex trade dispute, Switzerland acted as a neutral mediator."),

  ("fusionieren mit", "Wirtschaft & Arbeit", "Fachsprachlich",
   "Zwei rechtlich selbstständige Unternehmen verschmelzen", "To merge with, amalgamate or unite enterprises",
   "fusionieren mit + Dat.", ["verschmelzen", "koalieren"],
   "Die beiden Pharmakonzerne fusionierten, um Entwicklungskosten zu teilen.",
   "Die beiden Pharmakonzerne [...], um Entwicklungskosten zu teilen.",
   "Both pharmaceutical groups merged in order to share development expenditures."),

  ("gebieten über", "Gesellschaft & Politik", "Gehoben",
   "Über Armeen herrschen oder als Gebot verlangen (+ Akk./Dat.)", "To command, rule over armies or require silence",
   "Ruhe gebieten; über Truppen gebieten", ["befehlen", "herrschen über"],
   "Der Richter gebot im vollbesetzten Saal sofortige Ruhe.",
   "Der Richter [...] im vollbesetzten Saal sofortige Ruhe.",
   "The judge commanded immediate silence in the crowded courtroom."),

  ("gedeihen", "Wissenschaft & Forschung", "Gehoben",
   "Pflanzlich prächtig wachsen oder wirtschaftlich florieren", "To thrive, flourish, prosper or burgeon",
   "prächtig gedeihen; das Projekt gedeiht", ["florieren", "blühen"],
   "Wissenschaft und Kultur gedeihen am besten in einem Klima offener Freiheit.",
   "Wissenschaft und Kultur [...] am besten in einem Klima offener Freiheit.",
   "Science and culture thrive best in a climate of open freedom."),

  ("gefährden", "Gesellschaft & Politik", "Bildungssprachlich",
   "Etwas einer akuten Bedrohung oder dem Scheitern aussetzen", "To endanger, jeopardize, imperil or compromise",
   "den Frieden / die Stabilität gefährden", ["bedrohen", "in Gefahr bringen"],
   "Rücksichtslose Spekulationen gefährden die Stabilität des Finanzsystems.",
   "Rücksichtslose Spekulationen [...] die Stabilität des Finanzsystems.",
   "Reckless speculation jeopardizes the stability of the global financial system."),

  ("gipfeln in", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Seinen dramatischen Höhepunkt oder Kulmination finden", "To culminate in, peak in or reach a climax in",
   "gipfeln in + Dat.", ["kulminieren", "münden in"],
   "Die monatelangen Spannungen gipfelten in gewaltsamen Straßenschlachten.",
   "Die monatelangen Spannungen [...] in gewaltsamen Straßenschlachten.",
   "The months of tensions culminated in violent street battles."),

  ("gliedern in", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Einen Text oder eine Organisation logisch in Teile unterteilen", "To divide into, structure, organize into sections",
   "gliedern in + Akk.", ["strukturieren", "unterteilen"],
   "Der Autor gliedert seine wissenschaftliche Abhandlung in fünf Hauptkapitel.",
   "Der Autor [...] seine wissenschaftliche Abhandlung in fünf Hauptkapitel.",
   "The author structures his scholarly treatise into five main chapters."),

  ("gravieren", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Als Inschrift einmeißeln oder schwer ins Gewicht fallen", "To engrave in metal or weigh gravely / be of serious consequence",
   "ins Gewicht fallen; gravierend sein", ["wiegen", "beeinträchtigen"],
   "Die festgestellten Versäumnisse gravieren schwer zu Lasten des Betreibers.",
   "Die festgestellten Versäumnisse [...] schwer zu Lasten des Betreibers.",
   "The detected omissions weigh heavily to the detriment of the plant operator."),

  ("haften für", "Recht & Verwaltung", "Formell",
   "Gesetzlich für entstandene Schäden geradestehen", "To be liable for, answer for or guarantee damages",
   "haften für + Akk.", ["einstehen für", "bürgen für"],
   "Eltern haften für die von ihren Kindern verursachten Schäden.",
   "Eltern [...] für die von ihren Kindern verursachten Schäden.",
   "Parents are liable for the damages caused by their children."),

  ("herrschen über", "Gesellschaft & Politik", "Bildungssprachlich",
   "Die politische Macht innehaben oder vorherrschend sein", "To prevail, rule over or dominate an atmosphere",
   "herrschen über + Akk.", ["regieren", "dominieren"],
   "Auf den internationalen Devisenmärkten herrschte gestern extreme Nervosität.",
   "Auf den internationalen Devisenmärkten [...] gestern extreme Nervosität.",
   "Extreme nervousness prevailed on international foreign exchange markets yesterday."),

  ("herbeiführen", "Gesellschaft & Politik", "Bildungssprachlich",
   "Durch gezielte Aktionen eine Wende oder ein Ereignis bewirken", "To bring about, induce, precipitate or cause a shift",
   "eine Wende / die Entscheidung herbeiführen", ["auslösen", "verursachen"],
   "Ein diplomatischer Kompromiss konnte das Ende des Streiks herbeiführen.",
   "Ein diplomatischer Kompromiss konnte das Ende des Streiks [...].",
   "A diplomatic compromise was able to bring about an end to the strike."),

  ("hervorheben", "Kommunikation & Diskurs", "Bildungssprachlich",
   "Besondere Qualitäten oder Thesen sprachlich unterstreichen", "To highlight, emphasize, accentuate or underline",
   "die Vorzüge / die Wichtigkeit hervorheben", ["betonen", "akzentuieren"],
   "Die Gutachterin hob in ihrem Bericht die vorbildliche Ökobilanz hervor.",
   "Die Gutachterin [...] in ihrem Bericht die vorbildliche Ökobilanz [...].",
   "In her report, the evaluator highlighted the exemplary ecological balance."),

  ("hervorgehen aus", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Aus einer Quelle resultieren oder als Sieger hervorgehen", "To emerge from, result from or be evident from data",
   "hervorgehen aus + Dat.", ["resultieren aus", "siegen"],
   "Aus den repräsentativen Umfragen geht eine wachsende Unzufriedenheit hervor.",
   "Aus den repräsentativen Umfragen [...] eine wachsende Unzufriedenheit [...].",
   "Growing dissatisfaction is evident from the representative surveys."),

  ("hinnehmen", "Psychologie & Kognition", "Bildungssprachlich",
   "Eine Kränkung oder Niederlage zähneknirschend akzeptieren", "To accept, endure, swallow or tolerate a bitter setback",
   "eine Niederlage / Schmach hinnehmen", ["erdulden", "akzeptieren"],
   "Der Spitzenkandidat musste eine schmerzhafte Niederlage hinnehmen.",
   "Der Spitzenkandidat musste eine schmerzhafte Niederlage [...].",
   "The top candidate had to swallow a painful election defeat."),

  ("hinterfragen", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Etablierte Dogmen oder Denkmuster kritisch analysieren", "To scrutinize, question critically or challenge dogmas",
   "Traditionen / Motive kritisch hinterfragen", ["anzweifeln", "reflektieren"],
   "Aufgeklärte Bürger sollten mediale Berichterstattung stets kritisch hinterfragen.",
   "Aufgeklärte Bürger sollten mediale Berichterstattung stets kritisch [...].",
   "Enlightened citizens should always critically scrutinize media reporting."),

  ("hintergehen", "Gesellschaft & Politik", "Bildungssprachlich",
   "Jemanden heimtückisch betrügen und das Vertrauen missbrauchen", "To deceive, betray or double-cross someone behind their back",
   "einen Partner / Wähler hintergehen", ["betrügen", "täuschen"],
   "Der korrupte Finanzchef hinterging seine Vorstandskollegen über Jahre hinweg.",
   "Der korrupte Finanzchef [...] seine Vorstandskollegen über Jahre hinweg.",
   "The corrupt CFO double-crossed his executive colleagues for years on end."),

  ("hinterlassen", "Psychologie & Kognition", "Bildungssprachlich",
   "Spuren, ein Vermächtnis oder einen tiefen Eindruck zurücklassen", "To leave behind traces, an impression or a legacy",
   "einen Eindruck / ein Vermächtnis hinterlassen", ["zurücklassen", "vererben"],
   "Die Rede der Nobelpreisträgerin hinterließ einen tiefen Eindruck beim Auditorium.",
   "Die Rede der Nobelpreisträgerin [...] einen tiefen Eindruck beim Auditorium.",
   "The Nobel laureate's speech left a profound impression on the auditorium."),

  ("hintertreiben", "Gesellschaft & Politik", "Gehoben",
   "Einen Plan oder Verhandlungen heimlich sabotieren und torpedieren", "To thwart, sabotage, undermine or frustrate covertly",
   "Pläne / Verhandlungen hintertreiben", ["sabotieren", "torpedieren"],
   "Hardliner versuchten heimlich, das Friedensabkommen zu hintertreiben.",
   "Hardliner versuchten heimlich, das Friedensabkommen zu [...].",
   "Hardliners covertly attempted to thwart the peace agreement."),

  ("hinweisen auf", "Kommunikation & Diskurs", "Bildungssprachlich",
   "Aufmerksam auf Fakten oder drohende Gefahren lenken", "To point out, draw attention to or indicate a risk",
   "hinweisen auf + Akk.", ["aufmerksam machen auf", "indizieren"],
   "Der Verfasser weist ausdrücklich auf die bestehenden Rechtsrisiken hin.",
   "Der Verfasser [...] ausdrücklich auf die bestehenden Rechtsrisiken [...].",
   "The author explicitly points out the existing legal risks."),

  ("hinwirken auf", "Gesellschaft & Politik", "Bildungssprachlich",
   "Konsequent und zielgerichtet auf ein bestimmtes Resultat hinarbeiten", "To work towards, endeavor to achieve or strive for",
   "hinwirken auf + Akk.", ["hinarbeiten auf", "anstreben"],
   "Die Staatengemeinschaft muss mit Nachdruck auf eine diplomatische Lösung hinwirken.",
   "Die Staatengemeinschaft muss mit Nachdruck auf eine diplomatische Lösung [...].",
   "The international community must pressingly work towards a diplomatic solution."),

  ("nachahmen", "Psychologie & Kognition", "Bildungssprachlich",
   "Das Verhalten oder Aussehen eines Vorbilds kopieren", "To imitate, emulate, mimic or counterfeit",
   "ein Vorbild / einen Stil nachahmen", ["imitieren", "kopieren"],
   "Kleinkinder lernen Sprache vor allem, indem sie Erwachsene nachahmen.",
   "Kleinkinder lernen Sprache vor allem, indem sie Erwachsene [...].",
   "Young children learn language primarily by imitating adults."),

  ("nacheifern", "Psychologie & Kognition", "Gehoben",
   "Einem großen Vorbild mit Eifer nacheifern (+ Dat.)", "To emulate, strive to equal or follow in footsteps (+ Dat.)",
   "einem Idol nacheifern (+ Dat.)", ["folgen", "nacheifern"],
   "Die junge Pianistin eifert ihrem weltberühmten Meister voller Bewunderung nach.",
   "Die junge Pianistin [...] ihrem weltberühmten Meister voller Bewunderung [...].",
   "The young pianist emulates her world-famous maestro full of admiration."),

  ("nachempfinden", "Psychologie & Kognition", "Bildungssprachlich",
   "Sich empathisch in die seelische Verfassung anderer hineinversetzen", "To empathize with, feel for or re-experience feelings",
   "den Schmerz / die Freude nachempfinden", ["mitfühlen", "verstehen"],
   "Nur wer Ähnliches erlebt hat, kann diesen traumatischen Verlust nachempfinden.",
   "Nur wer Ähnliches erlebt hat, kann diesen traumatischen Verlust [...].",
   "Only those who have experienced similar can truly empathize with this loss."),

  ("nachgehen", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Einer Spur, einem Hobby oder Pflichten gewissenhaft nachgehen", "To pursue an inquiry, investigate a lead or pursue a profession",
   "einer Spur / seiner Arbeit nachgehen (+ Dat.)", ["untersuchen", "ausüben"],
   "Die Ermittler müssen jedem auch noch so vagen Hinweis akribisch nachgehen.",
   "Die Ermittler müssen jedem auch noch so vagen Hinweis akribisch [...].",
   "Investigators must meticulously follow up on even the vaguest lead."),

  ("nachhaken", "Kommunikation & Diskurs", "Bildungssprachlich",
   "Bei unklaren oder ausweichenden Antworten beharrlich nachfragen", "To follow up stubbornly, press for answers or probe further",
   "bei einem Thema / beim Minister nachhaken", ["nachfragen", "bohren"],
   "Die Journalistin hakte beharrlich nach, als der Minister auswich.",
   "Die Journalistin [...] beharrlich [...], als der Minister auswich.",
   "The journalist probed stubbornly when the minister dodged the query."),

  ("nachkommen", "Recht & Verwaltung", "Formell",
   "Einer rechtlichen Verpflichtung oder Frist fristgerecht genügen (+ Dat.)", "To fulfill, comply with or meet an obligation/demand (+ Dat.)",
   "einer Pflicht / Aufforderung nachkommen (+ Dat.)", ["erfüllen", "nachkommen"],
   "Das Unternehmen kam den behördlichen Auflagen pünktlich nach.",
   "Das Unternehmen [...] den behördlichen Auflagen pünktlich [...].",
   "The enterprise complied with the regulatory requirements on time."),

  ("nachrücken", "Gesellschaft & Politik", "Formell",
   "Für ein ausscheidendes Mitglied in Parlament oder Vorstand aufrücken", "To move up, succeed or replace an outgoing member",
   "auf einen frei gewordenen Sitz nachrücken", ["aufrücken", "nachfolgen"],
   "Für den zurückgetretenen Abgeordneten rückte eine Nachwuchspolitikerin nach.",
   "Für den zurückgetretenen Abgeordneten [...] eine Nachwuchspolitikerin [...].",
   "A junior politician moved up to take the resigned lawmaker's seat."),

  ("nachvollziehen", "Psychologie & Kognition", "Bildungssprachlich",
   "Die Gedankengänge oder Motive anderer gedanklich rekonstruieren", "To comprehend, trace logically, understand motives",
   "Gedankengänge / ein Urteil nachvollziehen", ["begreifen", "rekonstruieren"],
   "Auch wenn man die Entscheidung ablehnt, lässt sie sich rational nachvollziehen.",
   "Auch wenn man die Entscheidung ablehnt, lässt sie sich rational [...].",
   "Even if one rejects the decision, it can be rationally understood."),

  ("nachweisen", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Etwas durch unwiderlegbare Fakten oder Experimente beweisen", "To prove, demonstrate, substantiate or detect",
   "Schuld / Spuren im Blut nachweisen", ["belegen", "beweisen"],
   "Das Labor konnte geringste Spuren des Gifts im Blut nachweisen.",
   "Das Labor konnte geringste Spuren des Gifts im Blut [...].",
   "The laboratory was able to detect minute traces of the toxin in the blood."),

  ("nachwirken", "Psychologie & Kognition", "Bildungssprachlich",
   "Noch lange nach dem Ereignis spürbare emotionale Wirkungen zeigen", "To have a lasting impact, linger on or continue to reverberate",
   "die Krise wirkt noch lange nach", ["fortdauern", "nachhallen"],
   "Die traumatisierenden Erfahrungen der Kindheit wirkten zeitlebens nach.",
   "Die traumatisierenden Erfahrungen der Kindheit [...] zeitlebens [...].",
   "The traumatizing experiences of childhood lingered on throughout life."),

  # ÜBER / UM / UNTER / VER (265-300)
  ("überbeanspruchen", "Psychologie & Kognition", "Bildungssprachlich",
   "Körper, Geist oder Ressourcen über das zumutbare Maß hinaus belasten", "To overstrain, overtax or overuse resources/mind",
   "Kräfte / die Geduld überbeanspruchen", ["überlasten", "strapazieren"],
   "Dauerhafte Überstunden überbeanspruchen die physische und mentale Gesundheit.",
   "Dauerhafte Überstunden [...] die physische und mentale Gesundheit.",
   "Constant overtime overtaxes physical and mental health."),

  ("überbrücken", "Wirtschaft & Arbeit", "Bildungssprachlich",
   "Einen Engpass oder zeitliche Lücke vorübergehend ausgleichen", "To bridge a gap, tide over or span a temporary deficit",
   "eine Lücke / finanzielle Engpässe überbrücken", ["kompensieren", "ausgleichen"],
   "Mit einem Überbrückungskredit ließen sich die Zahlungsausfälle vorübergehend überbrücken.",
   "Mit einem Überbrückungskredit ließen sich die Zahlungsausfälle vorübergehend [...].",
   "With a bridging loan, payment defaults could be temporarily bridged."),

  ("überdenken", "Psychologie & Kognition", "Bildungssprachlich",
   "Eine frühere Entscheidung kritisch überprüfen und revidieren", "To rethink, reconsider or re-evaluate a strategy",
   "seine Haltung / den Entschluss überdenken", ["revidieren", "überprüfen"],
   "Angesichts neuer geopolitischer Risiken muss der Senat seine Energiepolitik überdenken.",
   "Angesichts neuer geopolitischer Risiken muss der Senat seine Energiepolitik [...].",
   "In view of new geopolitical risks, the Senate must rethink its energy policy."),

  ("überfordern", "Psychologie & Kognition", "Bildungssprachlich",
   "Zu hohe Anforderungen stellen, denen jemand nicht gewachsen ist", "To overtax, overburden, overwhelm or demand too much",
   "Schüler / das System überfordern", ["überlasten", "überanstrengen"],
   "Komplexe bürokratische Anträge überfordern viele ältere Bürger maßlos.",
   "Komplexe bürokratische Anträge [...] viele ältere Bürger maßlos.",
   "Complex bureaucratic forms excessively overwhelm many elderly citizens."),

  ("übergehen in", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Allmählich und fließend in einen anderen Zustand wechseln", "To merge into, transition into or blend into another state",
   "übergehen in + Akk.", ["überwechseln", "sich verwandeln"],
   "Der sanfte Regen ging im Laufe des Abends in dichten Schneefall über.",
   "Der sanfte Regen [...] im Laufe des Abends in dichten Schneefall [...].",
   "The gentle rain transitioned into heavy snowfall over the course of the evening."),

  ("übergreifen auf", "Gesellschaft & Politik", "Bildungssprachlich",
   "Von einem Herd oder Land auf benachbarte Regionen überspringen", "To spread to, spill over or encroach upon neighboring areas",
   "übergreifen auf + Akk.", ["ausgreifen auf", "sich ausbreiten auf"],
   "Die Inflation droht von den Energiekosten auf die gesamte Realwirtschaft überzugreifen.",
   "Die Inflation droht von den Energiekosten auf die gesamte Realwirtschaft [...].",
   "Inflation threatens to spill over from energy costs to the entire economy."),

  ("überhandnehmen", "Gesellschaft & Politik", "Bildungssprachlich",
   "In unerträglichem Maß zunehmen und dominant werden", "To become rampant, get out of hand or proliferate excessively",
   "Missstände nehmen überhand", ["wuchern", "ausufern"],
   "In vielen Großstädten hat die Wohnungsknappheit besorgniserregend überhandgenommen.",
   "In vielen Großstädten hat die Wohnungsknappheit besorgniserregend [...].",
   "In many metropolitan areas, the housing shortage has gotten rampantly out of hand."),

  ("überliefern", "Wissenschaft & Forschung", "Gehoben",
   "Kulturelle Traditionen oder Schriften für die Nachwelt bewahren", "To hand down, pass down or transmit through tradition",
   "Mythen / Texte an die Nachwelt überliefern", ["tradieren", "weitergeben"],
   "Antike Mythen wurden über Generationen hinweg mündlich überliefert.",
   "Antike Mythen wurden über Generationen hinweg mündlich [...].",
   "Ancient myths were passed down orally across generations."),

  ("übermitteln", "Kommunikation & Diskurs", "Formell",
   "Botschaften, Grüße oder Dokumente förmlich weiterleiten", "To transmit, convey, deliver or dispatch a message",
   "eine Botschaft / Grüße übermitteln", ["weiterleiten", "deponieren"],
   "Der Botschafter übermittelte der Regierung die offizielle Note des Präsidenten.",
   "Der Botschafter [...] der Regierung die offizielle Note des Präsidenten.",
   "The ambassador conveyed the official presidential diplomatic note to government."),

  ("überrumpeln", "Psychologie & Kognition", "Bildungssprachlich",
   "Jemanden durch einen unvorhergesehenen Vorstoß überrumpeln", "To catch off guard, bamboozle or take by surprise",
   "Gegner / den Gesprächspartner überrumpeln", ["überraschen", "übervorteilen"],
   "Mit seinem plötzlichen Rücktritt überrumpelte der CEO den Aufsichtsrat.",
   "Mit seinem plötzlichen Rücktritt [...] der CEO den Aufsichtsrat.",
   "With his abrupt resignation, the CEO caught the supervisory board off guard."),

  ("überschätzen", "Psychologie & Kognition", "Bildungssprachlich",
   "Kräfte, Relevanz oder Fähigkeiten zu hoch bewerten", "To overestimate, overrate or exaggerate capabilities",
   "seine Kräfte / den Einfluss überschätzen", ["überbewerten", "überheben"],
   "Viele Gründer überschätzen das anfängliche Marktpotenzial ihres Produkts.",
   "Viele Gründer [...] das anfängliche Marktpotenzial ihres Produkts.",
   "Many founders overestimate the initial market potential of their product."),

  ("übertreffen", "Wirtschaft & Arbeit", "Bildungssprachlich",
   "Leistungsstärker sein als Konkurrenten oder Erwartungen", "To exceed, surpass, outperform or eclipse expectations",
   "die Erwartungen / Rekorde übertreffen", ["überflügeln", "überbieten"],
   "Die diesjährigen Quartalsgewinne übertrafen selbst optimistische Prognosen.",
   "Die diesjährigen Quartalsgewinne [...] selbst optimistische Prognosen.",
   "This year's quarterly earnings exceeded even optimistic forecasts."),

  ("überwältigen", "Psychologie & Kognition", "Bildungssprachlich",
   "Durch physische Kraft besiegen oder von Gefühlen erfasst werden", "To overpower a foe or overwhelm someone with emotion",
   "einen Angreifer / von Gefühlen überwältigt sein", ["bezwingen", "erdrücken"],
   "Die Retter wurden von der Welle der Hilfsbereitschaft förmlich überwältigt.",
   "Die Retter wurden von der Welle der Hilfsbereitschaft förmlich [...].",
   "The rescue workers were literally overwhelmed by the wave of helpfulness."),

  ("überwiegen", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Das größere Gewicht oder die Mehrheit besitzen", "To predominate, prevail, outweigh or be preponderant",
   "die Vorteile überwiegen die Nachteile", ["dominieren", "vorherrschen"],
   "In der Gesamtbewertung überwiegen die Chancen der Technologie die Risiken deutlich.",
   "In der Gesamtbewertung [...] die Chancen der Technologie die Risiken deutlich.",
   "In the overall assessment, the opportunities of the tech clearly outweigh the risks."),

  ("überwinden", "Psychologie & Kognition", "Bildungssprachlich",
   "Ein Hindernis, Vorurteil oder Krise siegreich hinter sich lassen", "To overcome, conquer, surmount or transcend a crisis",
   "Hindernisse / Traumata überwinden", ["meistern", "bewältigen"],
   "Gemeinsam konnte die Gesellschaft die traumatische Spaltung überwinden.",
   "Gemeinsam konnte die Gesellschaft die traumatische Spaltung [...].",
   "Together, society was able to overcome the traumatic divide."),

  ("überzeugen von", "Kommunikation & Diskurs", "Bildungssprachlich",
   "Jemanden durch schlüssige Beweise für eine Sichtweise gewinnen", "To convince of, persuade someone of the truth",
   "überzeugen von + Dat.", ["persuadieren", "gewinnen für"],
   "Die Wissenschaftlerin konnte die Kommission von ihrer Hypothese überzeugen.",
   "Die Wissenschaftlerin konnte die Kommission von ihrer Hypothese [...].",
   "The scientist was able to convince the commission of her hypothesis."),

  ("unterbinden", "Gesellschaft & Politik", "Formell",
   "Eine unerwünschte Handlung, Schmuggel oder Aufruhr stoppen", "To curb, suppress, halt or put a stop to illicit trade",
   "Schmuggel / Missstände rigoros unterbinden", ["stoppen", "verhindern"],
   "Die Zollbehörden setzten alles daran, den Schmuggel von Plagiaten zu unterbinden.",
   "Die Zollbehörden setzten alles daran, den Schmuggel von Plagiaten zu [...].",
   "Customs authorities did everything to put a stop to the smuggling of pirated goods."),

  ("untergraben", "Gesellschaft & Politik", "Bildungssprachlich",
   "Das Fundament von Vertrauen oder Demokratie schleichend zerstören", "To undermine, erode, subvert or chip away at authority",
   "das Vertrauen / die Autorität untergraben", ["aushöhlen", "zersetzen"],
   "Gezielte Desinformation soll das Vertrauen in freie Wahlen untergraben.",
   "Gezielte Desinformation soll das Vertrauen in freie Wahlen [...].",
   "Targeted disinformation is intended to undermine trust in free elections."),

  ("unterliegen", "Recht & Verwaltung", "Formell",
   "Vorschriften oder Besteuerung unterworfen sein (+ Dat.)", "To be subject to regulations or succumb in a match (+ Dat.)",
   "den Vorschriften / im Wettkampf unterliegen (+ Dat.)", ["unterworfen sein", "verlieren"],
   "Alle pharmazeutischen Erzeugnisse unterliegen strengsten Qualitätskontrollen.",
   "Alle pharmazeutischen Erzeugnisse [...] strengsten Qualitätskontrollen.",
   "All pharmaceutical products are subject to the strictest quality controls."),

  ("untermauern", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Eine These mit hieb- und stichfesten Daten stützen", "To substantiate, underpin, buttress or corroborate",
   "eine These / Theorie untermauern", ["stützen", "belegen"],
   "Der Autor untermauert seine kontroverse These mit neuen Archivfunden.",
   "Der Autor [...] seine kontroverse These mit neuen Archivfunden.",
   "The author underpins his controversial thesis with new archival discoveries."),

  ("unterstellen", "Recht & Verwaltung", "Bildungssprachlich",
   "Jemandem unberechtigt bösartige Motive zuschreiben", "To insinuate, allege or attribute dubious motives to someone",
   "böswillige Absichten unterstellen", ["inzinuieren", "zuschreiben"],
   "Man sollte dem politischen Kontrahenten nicht von vornherein Böses unterstellen.",
   "Man sollte dem politischen Kontrahenten nicht von vornherein Böses [...].",
   "One should not insinuate evil motives to one's political opponent right away."),

  ("verankern in", "Recht & Verwaltung", "Formell",
   "Einen Grundsatz fest im Grundgesetz oder Bewusstsein festschreiben", "To enshrine, anchor, root or entrench in the constitution",
   "im Grundgesetz / in der Kultur verankern", ["festschreiben", "etablieren"],
   "Der Klimaschutz wurde als Staatsziel verbindlich im Grundgesetz verankert.",
   "Der Klimaschutz wurde als Staatsziel verbindlich im Grundgesetz [...].",
   "Climate protection was firmly enshrined in the constitution as a national goal."),

  ("veranlassen zu", "Psychologie & Kognition", "Bildungssprachlich",
   "Jemanden dazu bringen, eine Handlung auszuführen", "To prompt, induce, cause or impel someone to act",
   "veranlassen zu + Dat.", ["bewegen zu", "anstoßen"],
   "Der dramatische Kurssturz veranlasste den Anleger zum panischen Verkauf.",
   "Der dramatische Kurssturz [...] den Anleger zum panischen Verkauf.",
   "The dramatic stock plunge prompted the investor to panic sell."),

  ("veranschaulichen", "Kommunikation & Diskurs", "Bildungssprachlich",
   "Abstrakte Sachverhalte durch Diagramme greifbar darstellen", "To illustrate, exemplify, elucidate or visualize clearly",
   "komplexe Sachverhalte veranschaulichen", ["illustrieren", "verdeutlichen"],
   "Infografiken helfen dabei, komplexe statistische Trends zu veranschaulichen.",
   "Infografiken helfen dabei, komplexe statistische Trends zu [...].",
   "Infographics help to illustrate complex statistical trends vividly."),

  ("verbürgen für", "Gesellschaft & Politik", "Gehoben",
   "Mit seiner Ehre oder Vermögen für etwas garantieren", "To vouch for, warrant, guarantee or stand surety for",
   "sich verbürgen für + Akk.", ["bürgen für", "garantieren"],
   "Der Professor verbürgte sich persönlich für die Integrität seines Doktoranden.",
   "Der Professor [...] sich persönlich für die Integrität seines Doktoranden.",
   "The professor personally vouched for the integrity of his doctoral student."),

  ("verdrängen", "Psychologie & Kognition", "Bildungssprachlich",
   "Ein Trauma ins Unterbewusste schieben oder Konkurrenten verdrängen", "To repress trauma or supplant/displace competitors",
   "Erinnerungen / Konkurrenten verdrängen", ["reprimieren", "verdrängen"],
   "Aus Selbstschutz verdrängte er die schmerzhaften Erinnerungen an den Unfall.",
   "Aus Selbstschutz [...] er die schmerzhaften Erinnerungen an den Unfall.",
   "Out of self-preservation, he repressed painful memories of the accident."),

  ("vereiteln", "Gesellschaft & Politik", "Bildungssprachlich",
   "Einen feindlichen Plan, Anschlag oder Flucht vereiteln", "To foil, thwart, frustrate or prevent an attack/plot",
   "einen Anschlag / Pläne vereiteln", ["verhindern", "durchkreuzen"],
   "Die Sicherheitskräfte konnten einen geplanten Cyberangriff rechtzeitig vereiteln.",
   "Die Sicherheitskräfte konnten einen geplanten Cyberangriff rechtzeitig [...].",
   "Security forces were able to thwart a planned cyberattack in good time."),

  ("verfechten", "Gesellschaft & Politik", "Bildungssprachlich",
   "Eine Überzeugung, These oder Gerechtigkeit mutig verteidigen", "To champion, advocate, stand up for or defend staunchly",
   "Ideale / Thesen leidenschaftlich verfechten", ["verteidigen", "eintreten für"],
   "Die Juristin verfocht zeitlebens das Prinzip universeller Menschenrechte.",
   "Die Juristin [...] zeitlebens das Prinzip universeller Menschenrechte.",
   "Throughout her life, the jurist championed the principle of universal human rights."),

  ("verfügen über", "Wirtschaft & Arbeit", "Formell",
   "Ressourcen, Wissen oder Befugnisse rechtmäßig besitzen", "To have at one's disposal, possess or command resources",
   "verfügen über + Akk.", ["besitzen", "gebieten über"],
   "Die Forschungsgruppe verfügt über modernste spektroskopische Messgeräte.",
   "Die Forschungsgruppe [...] über modernste spektroskopische Messgeräte.",
   "The research team has cutting-edge spectroscopic equipment at its disposal."),

  ("verharren in", "Psychologie & Kognition", "Gehoben",
   "Regungslos an einer Stelle oder in alten Denkweisen verharren", "To persist in, linger in, remain motionless in a state",
   "in Starre / in Untätigkeit verharren", ["verbleiben", "stagnieren"],
   "Viele Konzerne verharren in überholten Denkmustern und versäumen Innovation.",
   "Viele Konzerne [...] in überholten Denkmustern und versäumen Innovation.",
   "Many corporations persist in obsolete mindsets and miss out on innovation."),

  ("verharmlosen", "Gesellschaft & Politik", "Bildungssprachlich",
   "Gefahren oder Verbrechen fälschlicherweise als harmlos darstellen", "To downplay, trivialize or minimize the severity of",
   "Gefahren / Risiken verharmlosen", ["bagatellisieren", "herunterspielen"],
   "Man darf die Gefahren von rechtsextremem Extremismus keinesfalls verharmlosen.",
   "Man darf die Gefahren von rechtsextremem Extremismus keinesfalls [...].",
   "One must by no means downplay the perils of right-wing extremism."),

  ("verknüpfen mit", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Zwei Gedanken, Systeme oder Verträge logisch verbinden", "To link, interconnect, tie or associate with",
   "verknüpfen mit + Dat.", ["verbinden mit", "koppeln"],
   "Die Theorie verknüpft Erkenntnisse der Neurowissenschaft mit Psychologie.",
   "Die Theorie [...] Erkenntnisse der Neurowissenschaft mit Psychologie.",
   "The theory links insights of neuroscience with empirical psychology."),

  ("verkörpern", "Psychologie & Kognition", "Bildungssprachlich",
   "Ein Ideal, einen Geisteszustand oder Prinzip personifizieren", "To embody, personify, epitomize or typify a principle",
   "ein Ideal / Werte verkörpern", ["personifizieren", "darstellen"],
   "Die Richterin verkörpert in vorbildlicher Weise richterliche Unabhängigkeit.",
   "Die Richterin [...] in vorbildlicher Weise richterliche Unabhängigkeit.",
   "The judge epitomizes judicial independence in an exemplary manner."),

  ("verlagern auf", "Wirtschaft & Arbeit", "Bildungssprachlich",
   "Einen Schwerpunkt, Frachten oder Standorte verschieben", "To shift, relocate, divert or transfer onto",
   "verlagern auf + Akk.", ["verschieben", "transferieren"],
   "Die Europäische Union will mehr Güterverkehr von der Straße auf die Schiene verlagern.",
   "Die Europäische Union will mehr Güterverkehr von der Straße auf die Schiene [...].",
   "The EU aims to shift more freight traffic from road onto rail."),

  ("verleiten zu", "Psychologie & Kognition", "Bildungssprachlich",
   "Jemanden durch Verlockung zu einer unbedachten Tat verführen", "To tempt, induce, lure or lead someone into an error",
   "verleiten zu + Dat.", ["verführen zu", "anstiften"],
   "Günstige Kredite verleiteten viele Käufer zu riskanten Immobiliengeschäften.",
   "Günstige Kredite [...] viele Käufer zu riskanten Immobiliengeschäften.",
   "Cheap credit lured many buyers into risky real estate transactions."),

  ("vermitteln", "Kommunikation & Diskurs", "Bildungssprachlich",
   "Wissen verständlich lehren oder zwischen Streitenden vermitteln", "To impart knowledge or mediate between conflicting parties",
   "Wissen / im Streit vermitteln", ["schlichten", "lehren"],
   "Ein guter Pädagoge versteht es, selbst trockenen Stoff fesselnd zu vermitteln.",
   "Ein guter Pädagoge versteht es, selbst trockenen Stoff fesselnd zu [...].",
   "A good educator knows how to impart even dry material captivatingly."),

  ("vermuten", "Psychologie & Kognition", "Bildungssprachlich",
   "Etwas auf Basis von Indizien mit Wahrscheinlichkeit annehmen", "To presume, suspect, surmise or hypothesize",
   "einen Zusammenhang / Täter vermuten", ["annehmen", "mutmaßen"],
   "Meteorologen vermuten, dass der Sommer neue Hitzerekorde bringen wird.",
   "Meteorologen [...], dass der Sommer neue Hitzerekorde bringen wird.",
   "Meteorologists suspect that the summer will bring fresh heat records.")
]
