# -*- coding: utf-8 -*-
# Goethe C1 Verbs Batch 2 (Items 101 - 200)

BATCH_2 = [
  ("beibehalten", "Gesellschaft & Politik", "Formell",
   "Eine Praxis, Strategie oder Tradition unverändert fortführen", "To maintain, retain or adhere to a policy or practice",
   "eine Strategie / Gewohnheit beibehalten", ["fortführen", "bewahren"],
   "Trotz sinkender Erträge behielt der Betrieb seine Qualitätsstandards bei.",
   "Trotz sinkender Erträge [...] der Betrieb seine Qualitätsstandards [...].",
   "Despite falling revenues, the company retained its high quality standards."),

  ("beibringen", "Kommunikation & Diskurs", "Bildungssprachlich",
   "Jemandem eine Fertigkeit lehren oder Beweismittel vorlegen", "To teach a skill or produce evidentiary proof",
   "den Beweis / Nachweise beibringen", ["vorlegen", "unterrichten"],
   "Der Kläger konnte die geforderten Eigentumsnachweise nicht beibringen.",
   "Der Kläger konnte die geforderten Eigentumsnachweise nicht [...].",
   "The plaintiff was unable to produce the required proofs of ownership."),

  ("beilegen", "Gesellschaft & Politik", "Formell",
   "Einen Rechtsstreit gütlich beenden oder ein Dokument hinzufügen", "To settle a dispute amicably or enclose a document",
   "einen Streit / Konflikt gütlich beilegen", ["schlichten", "begraben"],
   "Beide Staaten einigten sich darauf, den Grenzstreit diplomatisch beizulegen.",
   "Beide Staaten einigten sich darauf, den Grenzstreit diplomatisch [...].",
   "Both nations agreed to settle the border dispute diplomatically."),

  ("beipflichten", "Kommunikation & Diskurs", "Gehoben",
   "Der Ansicht eines Vorredners ausdrücklich zustimmen (+ Dat.)", "To concur with, agree with someone's opinion (+ Dat.)",
   "jdm. in vollem Umfang beipflichten (+ Dat.)", ["zustimmen", "akkordieren"],
   "Ich muss dem Kollegen in seiner skeptischen Einschätzung voll beipflichten.",
   "Ich muss dem Kollegen in seiner skeptischen Einschätzung voll [...].",
   "I must fully concur with my colleague in his skeptical appraisal."),

  ("beisteuern zu", "Gesellschaft & Politik", "Bildungssprachlich",
   "Einen wertvollen inhaltlichen oder finanziellen Beitrag leisten", "To contribute towards or chip in resources/ideas",
   "beisteuern zu + Dat.", ["beitragen", "subventionieren"],
   "Die Stiftung steuerte einen namhaften Betrag zur Restaurierung bei.",
   "Die Stiftung [...] einen namhaften Betrag zur Restaurierung [...].",
   "The foundation contributed a substantial sum towards the restoration."),

  ("beitragen zu", "Gesellschaft & Politik", "Bildungssprachlich",
   "Einen ursächlichen Anteil zum Gelingen oder Misslingen beitragen", "To contribute to, conduce to or play a role in",
   "beitragen zu + Dat.", ["mitwirken an", "fördern"],
   "Regelmäßige Bewegung trägt maßgeblich zur kognitiven Fitness im Alter bei.",
   "Regelmäßige Bewegung [...] maßgeblich zur kognitiven Fitness im Alter [...].",
   "Regular exercise contributes significantly to cognitive fitness in old age."),

  ("bekräftigen", "Kommunikation & Diskurs", "Formell",
   "Eine Zusage, Partnerschaft oder Absicht nachdrücklich bestätigen", "To reaffirm, corroborate or emphatically reiterate",
   "den Willen / eine Absicht bekräftigen", ["bestätigen", "untermauern"],
   "Beide Staatsoberhäupter bekräftigten ihren Willen zu enger Kooperation.",
   "Beide Staatsoberhäupter [...] ihren Willen zu enger Kooperation.",
   "Both heads of state reaffirmed their willingness for close cooperation."),

  ("beklagen", "Gesellschaft & Politik", "Formell",
   "Über einen unhaltbaren Zustand öffentlich klagen", "To lament, decry or deplore an undesirable condition",
   "den Verfall / Mängel beklagen", ["kritisieren", "bedauern"],
   "Die Verbände beklagten den fortschreitenden Mangel an Fachkräften.",
   "Die Verbände [...] den fortschreitenden Mangel an Fachkräften.",
   "The associations decried the progressive shortage of skilled labor."),

  ("bekunden", "Kommunikation & Diskurs", "Gehoben",
   "Ein Gefühl, Interesse oder Beileid feierlich zum Ausdruck bringen", "To manifest, express or attest sympathy/interest",
   "Interesse / Beileid feierlich bekunden", ["zeigen", "äußern"],
   "Zahlreiche Investoren bekundeten Interesse an dem innovativen Patent.",
   "Zahlreiche Investoren [...] Interesse an dem innovativen Patent.",
   "Numerous investors expressed interest in the innovative patent."),

  ("belegen", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Eine These durch stichhaltige Beweise oder Daten beweisen", "To substantiate, verify or corroborate with empirical proof",
   "eine These empirisch belegen", ["beweisen", "nachweisen"],
   "Die Forscher konnten ihre Hypothese durch umfangreiche Studien belegen.",
   "Die Forscher konnten ihre Hypothese durch umfangreiche Studien [...].",
   "The researchers were able to substantiate their hypothesis through studies."),

  ("beleuchten", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Einen komplexen Gegenstand aus verschiedenen Blickwinkeln untersuchen", "To shed light on, examine or illuminate an issue",
   "ein Thema kritisch beleuchten", ["analysieren", "untersuchen"],
   "Die Dokumentation beleuchtet die Hintergründe der geopolitischen Krise.",
   "Die Dokumentation [...] die Hintergründe der geopolitischen Krise.",
   "The documentary sheds light on the background of the geopolitical crisis."),

  ("bemängeln", "Recht & Verwaltung", "Formell",
   "Konkrete Schwächen oder Qualitätsmängel rügen", "To find fault with, criticize or censure shortcomings",
   "Defizite / die Qualität bemängeln", ["kritisieren", "rügen"],
   "Der Prüfbericht bemängelte gravierende Sicherheitslücken in der Software.",
   "Der Prüfbericht [...] gravierende Sicherheitslücken in der Software.",
   "The audit report found fault with severe security flaws in the software."),

  ("bemessen nach", "Wirtschaft & Arbeit", "Fachsprachlich",
   "Die Höhe von Abgaben, Beiträgen oder Strafen exakt berechnen", "To calculate, proportion or assess according to criteria",
   "bemessen nach + Dat.", ["berechnen", "festsetzen"],
   "Die Höhe des Beitrags bemisst sich nach dem steuerpflichtigen Einkommen.",
   "Die Höhe des Beitrags [...] sich nach dem steuerpflichtigen Einkommen.",
   "The amount of the contribution is assessed according to taxable income."),

  ("benachrichtigen von/über", "Recht & Verwaltung", "Formell",
   "Jemanden offiziell über einen Vorgang in Kenntnis setzen", "To notify formally, apprise or inform of a fact",
   "jdn. benachrichtigen von/über + Akk.", ["informieren", "in Kenntnis setzen"],
   "Die Behörde benachrichtigte die Anwohner unverzüglich über die Baumaßnahme.",
   "Die Behörde [...] die Anwohner unverzüglich über die Baumaßnahme.",
   "The authority promptly notified residents about the construction work."),

  ("benachteiligen", "Gesellschaft & Politik", "Bildungssprachlich",
   "Jemandem ungerechtfertigte Nachteile zufügen", "To disadvantage, discriminate against or penalize unfairly",
   "Minderheiten / Frauen benachteiligen", ["diskriminieren", "zurücksetzen"],
   "Das neue Steuersystem darf Familien mit geringem Einkommen nicht benachteiligen.",
   "Das neue Steuersystem darf Familien mit geringem Einkommen nicht [...].",
   "The new taxation system must not disadvantage low-income families."),

  ("beratschlagen über", "Gesellschaft & Politik", "Gehoben",
   "Gemeinsam ausführlich über eine schwierige Lage beraten", "To deliberate, consult or confer collectively on an issue",
   "beratschlagen über + Akk.", ["deliberieren", "sich beraten"],
   "Das Kabinett beratschlagte stundenlang über schärfere Sicherheitsmaßnahmen.",
   "Das Kabinett [...] stundenlang über schärfere Sicherheitsmaßnahmen.",
   "The cabinet deliberated for hours over stricter security measures."),

  ("bereichern", "Psychologie & Kognition", "Bildungssprachlich",
   "Das Wissen oder den Horizont erweitern und wertvoller machen", "To enrich, enhance or add value to culture/knowledge",
   "die Kultur / den Diskurs bereichern", ["erweitern", "aufwerten"],
   "Der interkulturelle Austausch bereichert den akademischen Diskurs ungemein.",
   "Der interkulturelle Austausch [...] den akademischen Diskurs ungemein.",
   "Intercultural exchange enriches academic discourse immensely."),

  ("bereitstellen", "Wirtschaft & Arbeit", "Formell",
   "Finanzielle Mittel oder Sachgüter zur Verfügung stellen", "To allocate, provide, supply or earmark funding",
   "Mittel / Infrastruktur bereitstellen", ["zur Verfügung stellen", "bewilligen"],
   "Das Ministerium stellte Sondermittel für die energetische Sanierung bereit.",
   "Das Ministerium [...] Sondermittel für die energetische Sanierung [...].",
   "The ministry allocated special funds for energy-efficient renovation."),

  ("bergen", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Etwas retten oder ein verborgenes Risiko in sich tragen", "To rescue or harbor an inherent danger/potential",
   "Risiken / Gefahren / Chancen bergen", ["in sich tragen", "beinhalten"],
   "Der technologische Umbruch birgt gleichermaßen enorme Chancen und Gefahren.",
   "Der technologische Umbruch [...] gleichermaßen enorme Chancen und Gefahren.",
   "The technological transformation harbors both immense opportunities and dangers."),

  ("berücksichtigen", "Psychologie & Kognition", "Bildungssprachlich",
   "Faktoren aufmerksam in Planungen und Urteilen einbeziehen", "To take into consideration, account for or factor in",
   "die Interessen / Belange berücksichtigen", ["einbeziehen", "beachten"],
   "Bei der Neugestaltung des Platzes müssen die Belange von Behinderten berücksichtigt werden.",
   "Bei der Neugestaltung des Platzes müssen die Belange von Behinderten [...] werden.",
   "The needs of people with disabilities must be factored in when redesigning."),

  ("beruhen auf", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Als sachliche oder empirische Grundlage auf etwas basieren", "To be based upon, rest on or stem from (+ Dat.)",
   "beruhen auf + Dat.", ["basieren auf", "fußen auf"],
   "Die neuen Erkenntnisse beruhen auf langjährigen klinischen Langzeitstudien.",
   "Die neuen Erkenntnisse [...] auf langjährigen klinischen Langzeitstudien.",
   "The new insights are based on years of longitudinal clinical studies."),

  ("bescheinigen", "Recht & Verwaltung", "Formell",
   "Amtlich und schriftlich die Richtigkeit bestätigen", "To attest, certify or formally verify a qualification",
   "jdm. Kompetenz / Erfolg bescheinigen", ["attestieren", "zertifizieren"],
   "Der Gutachter bescheinigte dem Bauwerk eine vorbildliche Statik.",
   "Der Gutachter [...] dem Bauwerk eine vorbildliche Statik.",
   "The surveyor certified that the building had exemplary structural stability."),

  ("beschleunigen", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Das Tempo eines Prozesses oder einer Reaktion erhöhen", "To accelerate, hasten, expedite or speed up a process",
   "das Verfahren / den Wandel beschleunigen", ["forcieren", "vorantreiben"],
   "Bürokratieabbau soll die Genehmigung von Windkraftanlagen spürbar beschleunigen.",
   "Bürokratieabbau soll die Genehmigung von Windkraftanlagen spürbar [...].",
   "Cutting red tape is meant to speed up the approval of wind turbines."),

  ("beschwichtigen", "Psychologie & Kognition", "Bildungssprachlich",
   "Erboste Gemüter oder Unruhe durch Worte beruhigen", "To appease, soothe, mollify or pacify anger/fears",
   "die Gemüter / die Demonstranten beschwichtigen", ["beruhigen", "kalmieren"],
   "Der Regierungssprecher versuchte, die aufgebrachte Öffentlichkeit zu beschwichtigen.",
   "Der Regierungssprecher versuchte, die aufgebrachte Öffentlichkeit zu [...].",
   "The government spokesman attempted to appease the agitated public."),

  ("beseitigen", "Gesellschaft & Politik", "Formell",
   "Hindernisse, Mängel oder Gefahren vollständig ausräumen", "To eliminate, eradicate or remove flaws/barriers",
   "Mängel / Barrieren restlos beseitigen", ["eliminieren", "ausräumen"],
   "Die Kommunen müssen bauliche Barrieren im Nahverkehr rasch beseitigen.",
   "Die Kommunen müssen bauliche Barrieren im Nahverkehr rasch [...].",
   "Municipalities must swiftly eliminate architectural barriers in transit."),

  ("besiegeln", "Gesellschaft & Politik", "Gehoben",
   "Einen Bund feierlich schließen oder das Schicksal festlegen", "To seal, finalize a treaty or seal someone's fate",
   "einen Pakt / ein Schicksal besiegeln", ["festlegen", "bekräftigen"],
   "Der verheerende Großbrand besiegelte das Ende der traditionsreichen Fabrik.",
   "Der verheerende Großbrand [...] das Ende der traditionsreichen Fabrik.",
   "The devastating fire sealed the end of the traditional factory."),

  ("besinnen auf", "Psychologie & Kognition", "Gehoben",
   "Sich nach Verirrungen wieder auf fundamentale Werte ausrichten", "To recall, reflect upon or return to core values",
   "sich besinnen auf + Akk.", ["zurückkehren zu", "fokussieren"],
   "In turbulenten Zeiten sollte sich die Gesellschaft auf ihre demokratischen Wurzeln besinnen.",
   "In turbulenten Zeiten sollte sich die Gesellschaft auf ihre demokratischen Wurzeln [...].",
   "In turbulent times, society should reflect upon its democratic roots."),

  ("bestärken in", "Psychologie & Kognition", "Bildungssprachlich",
   "Jemanden in seinem Entschluss oder Selbstvertrauen festigen", "To encourage, confirm or strengthen someone in a resolve",
   "jdm. in seinem Entschluss bestärken", ["ermutigen", "festigen"],
   "Der Beifall des Publikums bestärkte sie in ihrem mutigen künstlerischen Vorhaben.",
   "Der Beifall des Publikums [...] sie in ihrem mutigen künstlerischen Vorhaben.",
   "The audience's applause strengthened her in her courageous endeavor."),

  ("bestätigen", "Wissenschaft & Forschung", "Formell",
   "Die Richtigkeit einer Annahme oder Aussage offiziell verifizieren", "To confirm, corroborate, verify or validate findings",
   "eine Vermutung / das Urteil bestätigen", ["verifizieren", "bekräftigen"],
   "Die jüngsten Laborergebnisse bestätigen die Richtigkeit der Modellrechnung.",
   "Die jüngsten Laborergebnisse [...] die Richtigkeit der Modellrechnung.",
   "The latest laboratory findings confirm the accuracy of the mathematical model."),

  ("bestehen auf", "Gesellschaft & Politik", "Bildungssprachlich",
   "Hartnäckig auf Erfüllung eines Rechts fordern", "To insist on, press for or stand upon a right",
   "bestehen auf + Dat.", ["beharren auf", "einfordern"],
   "Der Verbraucherschutzverband bestand auf der lückenlosen Einhaltung der Garantie.",
   "Der Verbraucherschutzverband [...] auf der lückenlosen Einhaltung der Garantie.",
   "The consumer protection association insisted on full compliance with warranty."),

  ("bestreiten", "Recht & Verwaltung", "Bildungssprachlich",
   "Die Wahrheit leugnen oder den Lebensunterhalt finanzieren", "To dispute an allegation or finance one's living expenses",
   "Vorwürfe bestreiten; den Lebensunterhalt bestreiten", ["abstreiten", "finanzieren"],
   "Der Minister bestritt vor der Presse vehement alle erhobenen Vorwürfe.",
   "Der Minister [...] vor der Presse vehement alle erhobenen Vorwürfe.",
   "Before the press, the minister vehemently disputed all allegations raised."),

  ("betätigen", "Psychologie & Kognition", "Formell",
   "In einem bestimmten Fachgebiet aktiv tätig sein", "To engage in, operate or be active in a field",
   "sich ehrenamtlich / politisch betätigen", ["engagieren", "aktiv sein"],
   "Viele Ruheständler betätigen sich heute aktiv in gemeinnützigen Initiativen.",
   "Viele Ruheständler [...] sich heute aktiv in gemeinnützigen Initiativen.",
   "Many retirees nowadays actively engage in charitable initiatives."),

  ("beteiligen an", "Gesellschaft & Politik", "Formell",
   "Einen Anteil an Entscheidungen oder Gewinnen gewähren", "To involve, participate in or share in decisions",
   "sich beteiligen an + Dat.", ["mitwirken", "teilhaben an"],
   "Die Bürger sollen verstärkt an städtebaulichen Planungen beteiligt werden.",
   "Die Bürger sollen verstärkt an städtebaulichen Planungen [...] werden.",
   "Citizens should be increasingly involved in urban planning processes."),

  ("beteuern", "Kommunikation & Diskurs", "Gehoben",
   "Feierlich und eindringlich die eigene Unschuld versichern", "To protest, profess or solemnly swear innocence",
   "seine Unschuld / Treue beteuern", ["versichern", "bekräftigen"],
   "Der Verdächtige beteuerte bis zuletzt seine vollkommene Ahnungslosigkeit.",
   "Der Verdächtige [...] bis zuletzt seine vollkommene Ahnungslosigkeit.",
   "The suspect protested his complete innocence until the very end."),

  ("betonen", "Kommunikation & Diskurs", "Bildungssprachlich",
   "Einen Aspekt durch Akzente besonders hervorheben", "To emphasize, stress, accentuate or underline",
   "die Dringlichkeit / Bedeutung betonen", ["hervorheben", "unterstreichen"],
   "Die Bildungsforscherin betonte die herausragende Rolle früher Sprachförderung.",
   "Die Bildungsforscherin [...] die herausragende Rolle früher Sprachförderung.",
   "The educational researcher emphasized the prominent role of early language support."),

  ("betrachten als", "Psychologie & Kognition", "Bildungssprachlich",
   "Etwas oder jemanden in einer bestimmten Eigenschaft ansehen", "To regard, view, consider or deem someone as",
   "betrachten als + Akk.", ["erachten als", "ansehen als"],
   "Historiker betrachten den Vertrag als entscheidenden Wendepunkt im Konflikt.",
   "Historiker [...] den Vertrag als entscheidenden Wendepunkt im Konflikt.",
   "Historians regard the treaty as a decisive turning point in the conflict."),

  ("betreffen", "Gesellschaft & Politik", "Bildungssprachlich",
   "Für jemanden oder einen Sachverhalt unmittelbare Relevanz besitzen", "To affect, concern or pertain directly to someone",
   "die Gesamtheit betreffen", ["tangieren", "angehen"],
   "Der Klimawandel betrifft alle Kontinente und Generationen gleichermaßen.",
   "Der Klimawandel [...] alle Kontinente und Generationen gleichermaßen.",
   "Climate change affects all continents and generations equally."),

  ("bewahren vor", "Gesellschaft & Politik", "Gehoben",
   "Vor Schaden, Verfall oder Katastrophen behüten", "To preserve, safeguard or protect from destruction",
   "bewahren vor + Dat.", ["schützen vor", "behüten"],
   "Effektive Deiche bewahrten die Küstenregion vor verheerenden Überflutungen.",
   "Effektive Deiche [...] die Küstenregion vor verheerenden Überflutungen.",
   "Effective dikes preserved the coastal region from devastating floods."),

  ("bewältigen", "Psychologie & Kognition", "Bildungssprachlich",
   "Eine enorme Krise, Trauer oder Herausforderung meistern", "To overcome, master, cope with or resolve a crisis",
   "eine Krise / Trauer bewältigen", ["meistern", "überwinden"],
   "Mit großer Resilienz bewältigte die Bevölkerung die Folgen der Katastrophe.",
   "Mit großer Resilienz [...] die Bevölkerung die Folgen der Katastrophe.",
   "With great resilience, the population overcame the aftermath of the catastrophe."),

  ("bewegen zu", "Psychologie & Kognition", "Bildungssprachlich",
   "Jemanden durch Überzeugung oder Emotion zu einer Tat veranlassen", "To induce, prompt or persuade someone to an action",
   "bewegen zu + Dat.", ["veranlassen zu", "bewegen"],
   "Was hat den Vorstand letztlich dazu bewegt, seine Strategie radikal zu ändern?",
   "Was hat den Vorstand letztlich dazu [...], seine Strategie radikal zu ändern?",
   "What ultimately prompted the executive board to change its strategy radically?"),

  ("bewilligen", "Recht & Verwaltung", "Formell",
   "Einen amtlichen Antrag auf Gelder oder Urlaub genehmigen", "To grant, approve or authorize a subsidy or budget",
   "einen Kredit / Zuschuss bewilligen", ["genehmigen", "gewähren"],
   "Die Behörde bewilligte den Antrag auf Fördermittel ohne Auflagen.",
   "Die Behörde [...] den Antrag auf Fördermittel ohne Auflagen.",
   "The authority approved the grant application without any stipulations."),

  ("bewirken", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Als kausale Ursache ein bestimmtes Ergebnis herbeiführen", "To bring about, cause, effect or result in an outcome",
   "einen Umschwung / Wandel bewirken", ["herbeiführen", "verursachen"],
   "Gezielte Investitionen in Bildung bewirken nachhaltige Wohlstandsgewinne.",
   "Gezielte Investitionen in Bildung [...] nachhaltige Wohlstandsgewinne.",
   "Targeted investments in education bring about sustainable prosperity gains."),

  ("bezeichnen als", "Kommunikation & Diskurs", "Bildungssprachlich",
   "Jemandem oder etwas einen kennzeichnenden Namen geben", "To designate, characterize or describe someone as",
   "bezeichnen als + Akk.", ["charakterisieren", "nennen"],
   "Kritiker bezeichneten den Gesetzesentwurf als verfassungswidrigen Schnellschuss.",
   "Kritiker [...] den Gesetzesentwurf als verfassungswidrigen Schnellschuss.",
   "Critics described the draft bill as an unconstitutional hasty move."),

  ("beziffern auf", "Wirtschaft & Arbeit", "Fachsprachlich",
   "Einen Geldbetrag oder Schaden zahlenmäßig exakt schätzen", "To put at, estimate or quantify an amount at (+ Akk.)",
   "beziffern auf + Akk.", ["quantifizieren", "veranschlagen auf"],
   "Experten beziffern die Schäden des Jahrhundertsturms auf mehrere Milliarden.",
   "Experten [...] die Schäden des Jahrhundertsturms auf mehrere Milliarden.",
   "Experts estimate the storm damages at several billion euros."),

  ("bezwecken", "Gesellschaft & Politik", "Bildungssprachlich",
   "Mit einer Maßnahme eine ganz bestimmte Absicht verfolgen", "To intend, aim at or purport to achieve",
   "was bezweckt die Verordnung?", ["intendieren", "beabsichtigen"],
   "Die Reform bezweckt eine gerechtere Verteilung der Steuerlasten.",
   "Die Reform [...] eine gerechtere Verteilung der Steuerlasten.",
   "The reform purports to achieve a fairer distribution of the tax burden."),

  ("bezweifeln", "Psychologie & Kognition", "Bildungssprachlich",
   "An der Wahrheit oder Umsetzbarkeit erhebliche Zweifel hegen", "To doubt, dispute or question the veracity/feasibility",
   "die Machbarkeit / Echtheit bezweifeln", ["infrage stellen", "anzweifeln"],
   "Skeptiker bezweifeln, dass das ehrgeizige Vorhaben fristgerecht gelingt.",
   "Skeptiker [...], dass das ehrgeizige Vorhaben fristgerecht gelingt.",
   "Skeptics doubt whether the ambitious project will succeed on time."),

  # EIN- (147-170)
  ("einbeziehen in", "Gesellschaft & Politik", "Bildungssprachlich",
   "In Überlegungen, Verträge oder Planungen integrieren", "To incorporate, include or integrate into a scheme",
   "einbeziehen in + Akk.", ["integrieren", "berücksichtigen"],
   "Die Bürgerinitiativen wurden frühzeitig in den Planungsprozess einbezogen.",
   "Die Bürgerinitiativen wurden frühzeitig in den Planungsprozess [...].",
   "Citizen initiatives were integrated into the planning process early on."),

  ("einbüßen", "Wirtschaft & Arbeit", "Bildungssprachlich",
   "Einen empfindlichen Verlust an Einfluss, Geld oder Ansehen erleiden", "To forfeit, lose or suffer a loss of influence/prestige",
   "an Einfluss / Vermögen einbüßen", ["verlieren", "verwirken"],
   "Durch den Skandal büßte das Unternehmen erheblich an Glaubwürdigkeit ein.",
   "Durch den Skandal [...] das Unternehmen erheblich an Glaubwürdigkeit [...].",
   "Through the scandal, the enterprise suffered a major loss of credibility."),

  ("eindämmen", "Gesellschaft & Politik", "Bildungssprachlich",
   "Die Ausbreitung einer Pandemie, Flut oder Gewalt begrenzen", "To contain, curb, stem or stem the tide of a crisis",
   "die Ausbreitung / Inflation eindämmen", ["begrenzen", "zügeln"],
   "Gezielte Quarantänemaßnahmen halfen, die Infektionswelle rasch einzudämmen.",
   "Gezielte Quarantänemaßnahmen halfen, die Infektionswelle rasch [...].",
   "Targeted quarantine measures helped to curb the wave of infection swiftly."),

  ("eingliedern in", "Gesellschaft & Politik", "Formell",
   "Personen oder Truppen harmonisch in ein Ganzes integrieren", "To incorporate, integrate or assimilate into an entity",
   "eingliedern in + Akk.", ["integrieren", "assimilieren"],
   "Die Neubürger wurden durch Sprachkurse rasch in den Arbeitsmarkt eingegliedert.",
   "Die Neubürger wurden durch Sprachkurse rasch in den Arbeitsmarkt [...].",
   "New arrivals were rapidly integrated into the labor market via courses."),

  ("eingrenzen", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Die Grenzen eines Problems oder Phänomens exakt bestimmen", "To narrow down, circumscribe, delimit or isolate",
   "die Ursache / das Thema eingrenzen", ["präzisieren", "delimitieren"],
   "Durch Ausschlussdiagnostik konnte der Arzt den Herd der Infektion eingrenzen.",
   "Durch Ausschlussdiagnostik konnte der Arzt den Herd der Infektion [...].",
   "Through differential diagnosis, the physician could narrow down the infection."),

  ("einhalten", "Recht & Verwaltung", "Formell",
   "Vorschriften, Fristen oder Vereinbarungen penibel befolgen", "To comply with, adhere to, observe a deadline/rule",
   "Fristen / Verträge strikt einhalten", ["befolgen", "respektieren"],
   "Sämtliche Vertragspartner verpflichteten sich, die Fristen penibel einzuhalten.",
   "Sämtliche Vertragspartner verpflichteten sich, die Fristen penibel [...].",
   "All contractual partners committed to strictly complying with the deadlines."),

  ("einholen", "Wirtschaft & Arbeit", "Bildungssprachlich",
   "Einen Rückstand wettmachen oder behördliche Genehmigung einholen", "To catch up with a lead or obtain formal approval",
   "den Rückstand / Genehmigungen einholen", ["aufholen", "beschaffen"],
   "Vor Baubeginn muss der Bauträger noch alle Umweltgutachten einholen.",
   "Vor Baubeginn muss der Bauträger noch alle Umweltgutachten [...].",
   "Before breaking ground, the developer must obtain all environmental permits."),

  ("einleuchten", "Psychologie & Kognition", "Bildungssprachlich",
   "Vollkommen klar, logisch nachvollziehbar und plausibel sein (+ Dat.)", "To be clear, plausible and intuitive to someone (+ Dat.)",
   "das leuchtet mir vollkommen ein (+ Dat.)", ["plausibel sein", "überzeugen"],
   "Die Argumentation der Klägerin leuchtete dem Richterkollegium sofort ein.",
   "Die Argumentation der Klägerin [...] dem Richterkollegium sofort [...].",
   "The plaintiff's argumentation was immediately plausible to the bench."),

  ("einnehmen", "Psychologie & Kognition", "Bildungssprachlich",
   "Geld erwirtschaften, Medikamente schlucken oder jemanden für sich gewinnen", "To take up a stance, ingest medicine or captivate someone",
   "eine Haltung / Geld einnehmen", ["vertreten", "erwirtschaften"],
   "Der Referent verstand es meisterhaft, das Publikum für seine Vision einzunehmen.",
   "Der Referent verstand es meisterhaft, das Publikum für seine Vision [...].",
   "The speaker masterfully knew how to win over the audience for his vision."),

  ("einordnen in", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Einen Befund systematisch in einen größeren Kontext einfügen", "To classify, categorize or contextualize within a schema",
   "einordnen in + Akk.", ["kategorisieren", "subsumieren"],
   "Der Soziologe ordnete die Jugendproteste in den globalen Kontext ein.",
   "Der Soziologe [...] die Jugendproteste in den globalen Kontext [...].",
   "The sociologist categorized the youth protests within a global context."),

  ("einräumen", "Kommunikation & Diskurs", "Gehoben",
   "Einen Fehler reumütig zugeben oder ein Recht/Rabatt gewähren", "To admit a mistake, concede a point or grant a discount",
   "Fehler / ein Recht / Rabatt einräumen", ["zugestehen", "gewähren"],
   "Der Minister musste in der Debatte handwerkliche Fehler beim Entwurf einräumen.",
   "Der Minister musste in der Debatte handwerkliche Fehler beim Entwurf [...].",
   "The minister had to concede procedural flaws in the draft during debate."),

  ("einrichten auf", "Psychologie & Kognition", "Bildungssprachlich",
   "Sich innerlich oder organisatorisch auf eine Lage vorbereiten", "To prepare, brace oneself or adapt for an eventuality",
   "sich einrichten auf + Akk.", ["sich wappnen", "sich vorbereiten"],
   "Wir müssen uns auf längere Lieferengpässe bei Halbleitern einrichten.",
   "Wir müssen uns auf längere Lieferengpässe bei Halbleitern [...].",
   "We must brace ourselves for prolonged supply bottlenecks in semiconductors."),

  ("einschätzen", "Psychologie & Kognition", "Bildungssprachlich",
   "Die Tragweite oder Qualität eines Phänomens sachkundig bewerten", "To assess, evaluate or estimate the gravity of an issue",
   "die Lage / Risiken realistisch einschätzen", ["beurteilen", "evaluieren"],
   "Die Geheimdienste schätzten die Bedrohungslage als akut und besorgniserregend ein.",
   "Die Geheimdienste [...] die Bedrohungslage als akut und besorgniserregend [...].",
   "Intelligence services assessed the threat situation as acute and alarming."),

  ("einschränken", "Gesellschaft & Politik", "Formell",
   "Die Ausübung von Grundrechten, Budgets oder Freiheiten beschränken", "To restrict, curtail, limit or restrain liberties",
   "Rechte / Ausgaben drastisch einschränken", ["beschränken", "drosseln"],
   "Im Notstand durfte die Regierung Bürgerrechte vorübergehend einschränken.",
   "Im Notstand durfte die Regierung Bürgerrechte vorübergehend [...].",
   "During the state of emergency, the government could curtail civil rights."),

  ("einsehen", "Psychologie & Kognition", "Bildungssprachlich",
   "Akten juristisch prüfen oder die Unausweichlichkeit begreifen", "To inspect official files or realize/admit an error",
   "Akten einsehen; die Notwendigkeit einsehen", ["begreifen", "inspizieren"],
   "Nach langem Zögern sah der Parteivorsitzende seinen Rücktritt als unausweichlich ein.",
   "Nach langem Zögern [...] der Parteivorsitzende seinen Rücktritt als unausweichlich [...].",
   "After long hesitation, the party leader realized his resignation was unavoidable."),

  ("einsetzen für", "Gesellschaft & Politik", "Bildungssprachlich",
   "Sich engagiert und nachdrücklich für eine edle Sache starkmachen", "To champion, advocate, campaign or stand up for a cause",
   "sich einsetzen für + Akk.", ["engagieren für", "kämpfen für"],
   "Zahlreiche Aktivisten setzen sich unermüdlich für den Artenschutz ein.",
   "Zahlreiche Aktivisten [...] sich unermüdlich für den Artenschutz [...].",
   "Numerous activists campaign tirelessly for wildlife conservation."),

  ("einstehen für", "Gesellschaft & Politik", "Bildungssprachlich",
   "Die volle moralische oder finanzielle Verantwortung tragen", "To vouch for, answer for or stand up for someone/something",
   "einstehen für + Akk.", ["bürgen für", "geradestehen für"],
   "Ein intehrer Politiker muss stets mit seinem Namen für seine Taten einstehen.",
   "Ein intehrer Politiker muss stets mit seinem Namen für seine Taten [...].",
   "An ethical politician must always answer for his actions with his reputation."),

  ("einstimmen auf", "Psychologie & Kognition", "Bildungssprachlich",
   "Eine Gruppe emotional auf ein schwieriges Vorhaben vorbereiten", "To attune, prepare emotionally or rally for an ordeal",
   "einstimmen auf + Akk.", ["einschwören auf", "vorbereiten"],
   "Der Trainer stimmte die Mannschaft auf ein kräftezehrendes Finale ein.",
   "Der Trainer [...] die Mannschaft auf ein kräftezehrendes Finale [...].",
   "The coach attuned the team for an exhausting final match."),

  ("eintauchen in", "Psychologie & Kognition", "Bildungssprachlich",
   "Ganzheitlich und fasziniert in ein Thema oder Kultur eintauchen", "To immerse oneself deeply into a topic, culture or mood",
   "eintauchen in + Akk.", ["vertiefen in", "versenken in"],
   "Die Forscherin tauchte jahrelang in die Welt der indigenen Mythen ein.",
   "Die Forscherin [...] jahrelang in die Welt der indigenen Mythen [...].",
   "The researcher immersed herself for years in the realm of indigenous myths."),

  ("eintreten für", "Gesellschaft & Politik", "Bildungssprachlich",
   "In Wort und Tat öffentlich für Werte oder Personen Partei ergreifen", "To advocate, stand up for, champion or support principles",
   "eintreten für + Akk.", ["plädieren für", "fechten für"],
   "Die Zivilgesellschaft muss mutig für den Erhalt der Rechtsstaatlichkeit eintreten.",
   "Die Zivilgesellschaft muss mutig für den Erhalt der Rechtsstaatlichkeit [...].",
   "Civil society must courageously stand up for upholding the rule of law."),

  ("einwenden gegen", "Kommunikation & Diskurs", "Formell",
   "Bedenken oder Widerspruch gegen einen Plan formulieren", "To object to, raise an objection against an assertion",
   "einwenden gegen + Akk.", ["monieren", "beanstanden"],
   "Der Gutachter hatte gravierende rechtliche Bedenken gegen das Gesetz einzuwenden.",
   "Der Gutachter hatte gravierende rechtliche Bedenken gegen das Gesetz [...].",
   "The legal expert had serious objections to raise against the law."),

  ("einwilligen in", "Recht & Verwaltung", "Formell",
   "Formell und rechtswirksam seine Zustimmung geben", "To consent to, acquiesce in or formally agree to",
   "einwilligen in + Akk.", ["zustimmen", "billigen"],
   "Vor der Operation muss der Patient explizit in das Narkoseverfahren einwilligen.",
   "Vor der Operation muss der Patient explizit in das Narkoseverfahren [...].",
   "Prior to surgery, the patient must explicitly consent to the anesthesia."),

  ("einwirken auf", "Gesellschaft & Politik", "Bildungssprachlich",
   "Einen kontinuierlichen Einfluss auf Akteure oder Materialien ausüben", "To act upon, influence continuously or impact someone",
   "einwirken auf + Akk.", ["beeinflussen", "prägen"],
   "Extreme Wetterereignisse wirken nachhaltig auf fragile Ökosysteme ein.",
   "Extreme Wetterereignisse [...] nachhaltig auf fragile Ökosysteme [...].",
   "Extreme weather events continuously impact fragile ecosystems."),

  # ENT- (171-197)
  ("entbehren", "Wissenschaft & Forschung", "Gehoben",
   "Vollständig ohne etwas sein; oft: jeglicher Grundlage entbehren (+ Gen.)", "To lack completely; to be devoid of truth/foundation (+ Gen.)",
   "jeder Grundlage entbehren (+ Gen.)", ["mangeln an", "vermissen"],
   "Die sensationalistischen Behauptungen der Boulevardpresse entbehren jeder Grundlage.",
   "Die sensationalistischen Behauptungen der Boulevardpresse [...] jeder Grundlage.",
   "The tabloid press's sensationalist claims are devoid of any factual foundation."),

  ("entbinden von", "Recht & Verwaltung", "Formell",
   "Jemanden von seiner Pflicht, Geheimhaltung oder Amt befreien", "To release, relieve or exempt from duty or confidentiality",
   "entbinden von + Dat.", ["befreien von", "entlasten"],
   "Die Ministerin wurde auf eigenen Wunsch von ihren Amtspflichten entbunden.",
   "Die Ministerin wurde auf eigenen Wunsch von ihren Amtspflichten [...].",
   "The minister was relieved of her official duties at her own request."),

  ("entfachen", "Gesellschaft & Politik", "Bildungssprachlich",
   "Ein Feuer, eine Debatte oder Begeisterung stürmisch entzünden", "To spark, kindle or unleash a fierce controversy/enthusiasm",
   "eine Debatte / Leidenschaft entfachen", ["auslösen", "anzetteln"],
   "Der Enthüllungsbericht entfachte eine hitzige Debatte über Lobbyismus.",
   "Der Enthüllungsbericht [...] eine hitzige Debatte über Lobbyismus.",
   "The investigative report unleashed a heated debate about lobbyism."),

  ("entfalten", "Psychologie & Kognition", "Bildungssprachlich",
   "Verborgene Talente, Kräfte oder Wirkungen voll entwickeln", "To unfold, develop, unleash or display full potential",
   "sein volles Potenzial entfalten", ["entwickeln", "freisetzen"],
   "Erst unter optimalen Bedingungen kann das Talent seine volle Kraft entfalten.",
   "Erst unter optimalen Bedingungen kann das Talent seine volle Kraft [...].",
   "Only under optimal conditions can talent unleash its full potential."),

  ("entfremden von", "Gesellschaft & Politik", "Bildungssprachlich",
   "Durch Enttäuschung die innere emotionale Bindung verlieren", "To alienate, estrange or detach from values or peers",
   "sich entfremden von + Dat.", ["distanzieren von", "abkehren von"],
   "Viele Bürger haben sich zunehmend von den etablierten Institutionen entfremdet.",
   "Viele Bürger haben sich zunehmend von den etablierten Institutionen [...].",
   "Many citizens have increasingly become alienated from established institutions."),

  ("entgehen", "Psychologie & Kognition", "Bildungssprachlich",
   "Einer Gefahr entrinnen oder unbemerkt an jemandem vorbeigehen (+ Dat.)", "To escape, elude someone's notice or avoid a penalty (+ Dat.)",
   "einer Strafe / der Aufmerksamkeit entgehen (+ Dat.)", ["entrinnen", "vermeiden"],
   "Dieser subtile Grammatikfehler war selbst dem aufmerksamen Lektorat entgangen.",
   "Dieser subtile Grammatikfehler war selbst dem aufmerksamen Lektorat [...].",
   "This subtle grammatical flaw had escaped even the alert copy-editing team."),

  ("entgleisen", "Gesellschaft & Politik", "Bildungssprachlich",
   "Aus den Fugen geraten, unkontrollierbar werden oder verbal ausfällig werden", "To derail, get out of hand or make a grave verbal slip",
   "eine Situation / Äußerung entgleist", ["eskalieren", "ausarten"],
   "Während der hitzigen Talkshow entglitt dem Politiker eine verbale Entgleisung.",
   "Während der hitzigen Talkshow [...] die Diskussion völlig.",
   "During the heated talk show, the entire debate derailed completely."),

  ("entkräften", "Kommunikation & Diskurs", "Bildungssprachlich",
   "Ein gegnerisches Argument durch unwiderlegbare Fakten zunichtemachen", "To refute, rebut, invalidate or debunk an argument",
   "ein Argument / Vorwürfe schlüssig entkräften", ["widerlegen", "demontieren"],
   "Mit stichhaltigen Statistiken konnte die Forscherin die Vorwürfe mühelos entkräften.",
   "Mit stichhaltigen Statistiken konnte die Forscherin die Vorwürfe mühelos [...].",
   "With solid statistics, the researcher was able to rebut the charges effortlessly."),

  ("entlarven", "Gesellschaft & Politik", "Bildungssprachlich",
   "Die wahre, unehrliche Natur von Heuchelei oder Betrug aufdecken", "To unmask, expose, debunk or reveal deception",
   "einen Schwindel / Scheinheiligkeit entlarven", ["aufdecken", "bloßstellen"],
   "Die Dokumentation entlarvte das angebliche Umweltengagement als Greenwashing.",
   "Die Dokumentation [...] das angebliche Umweltengagement als Greenwashing.",
   "The documentary unmasked the alleged environmental commitment as greenwashing."),

  ("entlasten von", "Wirtschaft & Arbeit", "Formell",
   "Eine Bürde, Stress oder finanzielle Abgaben mindern", "To relieve, disburden or unburden from taxes/strain",
   "die Bürger / das System entlasten", ["befreien von", "erleichtern"],
   "Steuersenkungen für kleine Einkommen sollen den Mittelstand spürbar entlasten.",
   "Steuersenkungen für kleine Einkommen sollen den Mittelstand spürbar [...].",
   "Tax cuts for modest incomes are intended to noticeably relieve the middle class."),

  ("entmutigen", "Psychologie & Kognition", "Bildungssprachlich",
   "Jemandem durch Misserfolge die Zuversicht und Tatkraft nehmen", "To dishearten, discourage or daunt someone",
   "sich durch Rückschläge nicht entmutigen lassen", ["demotivieren", "verzagen"],
   "Lassen Sie sich von anfänglichen Grammatikfehlern keineswegs entmutigen!",
   "Lassen Sie sich von anfänglichen Grammatikfehlern keineswegs [...]!",
   "By no means let yourself be discouraged by initial grammatical mistakes!"),

  ("entnehmen aus", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Informationen aus einer Quelle logisch entnehmen oder Proben ziehen", "To gather, deduce from or take samples from a source",
   "entnehmen aus + Dat.", ["folgern", "extrahieren"],
   "Dem Geschäftsbericht lässt sich entnehmen, dass die Umsätze stabil blieben.",
   "Dem Geschäftsbericht lässt sich [...], dass die Umsätze stabil blieben.",
   "From the annual report one can gather that revenues remained stable."),

  ("enträtseln", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Ein tiefes Geheimnis oder einen antiken Code entschlüsseln", "To unravel, solve or decipher a profound mystery/code",
   "ein Mysterium / den Code enträtseln", ["entschlüsseln", "dechiffrieren"],
   "Genetikern gelang es, die genaue Sequenz des Erbguts vollständig zu enträtseln.",
   "Genetikern gelang es, die genaue Sequenz des Erbguts vollständig zu [...].",
   "Geneticists succeeded in fully unraveling the exact sequence of the genome."),

  ("entrüsten über", "Psychologie & Kognition", "Bildungssprachlich",
   "Über empörendes Unrecht oder Anmaßung moralische Wut empfinden", "To become indignant, outraged or scandalized over",
   "sich entrüsten über + Akk.", ["sich empören über", "ereifern"],
   "Die Bürger entrüsteten sich über die maßlose Selbstbedienung der Vorstände.",
   "Die Bürger [...] sich über die maßlose Selbstbedienung der Vorstände.",
   "Citizens became indignant over the excessive self-enrichment of executives."),

  ("entschädigen für", "Recht & Verwaltung", "Formell",
   "Einen erlittenen Schaden durch Ausgleichszahlung wiedergutmachen", "To compensate, indemnify or reimburse for damages",
   "entschädigen für + Akk.", ["kompensieren", "abfinden"],
   "Die Fluggesellschaft musste die Passagiere für den Flugausfall entschädigen.",
   "Die Fluggesellschaft musste die Passagiere für den Flugausfall [...].",
   "The airline had to compensate the passengers for the flight cancellation."),

  ("entschärfen", "Gesellschaft & Politik", "Bildungssprachlich",
   "Einen gefährlichen Sprengkörper oder eine explosive politische Krise beruhigen", "To defuse, de-escalate or alleviate a volatile crisis",
   "einen Konflikt / eine Krise entschärfen", ["deeskalieren", "abmildern"],
   "Diplomatische Verhandlungen trugen dazu bei, die militärische Krise zu entschärfen.",
   "Diplomatische Verhandlungen trugen dazu bei, die militärische Krise zu [...].",
   "Diplomatic negotiations helped to defuse the military crisis."),

  ("entscheiden über", "Recht & Verwaltung", "Formell",
   "Ein abschließendes Urteil oder verbindlichen Beschluss fällen", "To decide, rule upon or adjudicate an issue",
   "entscheiden über + Akk.", ["urteilen über", "beschließen"],
   "Das Bundesverfassungsgericht muss nun über die Rechtmäßigkeit des Gesetzes entscheiden.",
   "Das Bundesverfassungsgericht muss nun über die Rechtmäßigkeit des Gesetzes [...].",
   "The Federal Constitutional Court must now decide upon the lawfulness of the act."),

  ("entschlüsseln", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Einen Code, Chiffretext oder Ursachengefüge dechiffrieren", "To decode, decipher or decode causal structures",
   "eine Chiffre / DNA entschlüsseln", ["dechiffrieren", "enträtseln"],
   "Den Historikern gelang es, die verschlüsselte Korrespondenz zu entschlüsseln.",
   "Den Historikern gelang es, die verschlüsselte Korrespondenz zu [...].",
   "Historians succeeded in deciphering the encrypted correspondence."),

  ("entsinnen", "Psychologie & Kognition", "Gehoben",
   "Sich aus dem Gedächtnis an ein Ereignis erinnern (+ Genitiv)", "To recall, recollect, remember (+ genitive)",
   "sich entsinnen + Gen.", ["sich erinnern an", "gedenken"],
   "Er konnte sich des genauen Wortlauts der Absprache nicht mehr entsinnen.",
   "Er konnte sich des genauen Wortlauts der Absprache nicht mehr [...].",
   "He could no longer recall the exact phrasing of the agreement."),

  ("entspringen", "Wissenschaft & Forschung", "Gehoben",
   "Als geografische Quelle hervorkommen oder geistig abstammen (+ Dat.)", "To originate from, stem from or spring forth from (+ Dat.)",
   "einer Quelle / einer Tradition entspringen (+ Dat.)", ["abstammen", "hervorgehen"],
   "Diese fortschrittliche Denkweise entspringt der humanistischen Aufklärung.",
   "Diese fortschrittliche Denkweise [...] der humanistischen Aufklärung.",
   "This progressive mindset stems from the humanist Enlightenment."),

  ("entstehen aus", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Aus Keimen, Ursachen oder Prozessen neu hervorgehen", "To originate, arise or emerge from conditions",
   "entstehen aus + Dat.", ["hervorgehen aus", "resultieren aus"],
   "Aus der Fusion zweier Start-ups entstand ein marktführender Softwarekonzern.",
   "Aus der Fusion zweier Start-ups [...] ein marktführender Softwarekonzern.",
   "From the merger of two start-ups arose a market-leading software corporation."),

  ("entstellen", "Recht & Verwaltung", "Bildungssprachlich",
   "Aussagen oder Tatsachen manipulieren und verzerren", "To distort, disfigure or misrepresent statements",
   "Tatsachen / Aussagen böswillig entstellen", ["verzerren", "fälschen"],
   "Der Zeuge beschuldigte die Journalisten, seine Zitate entstellt zu haben.",
   "Der Zeuge beschuldigte die Journalisten, seine Zitate [...] zu haben.",
   "The witness accused journalists of having distorted his quotations."),

  ("enttarnen", "Gesellschaft & Politik", "Bildungssprachlich",
   "Einen Spion, Doppelagenten oder Hochstapler öffentlich entlarven", "To unmask, blow the cover of an impostor or spy",
   "einen Spion / Hochstapler enttarnen", ["entlarven", "auffliegen lassen"],
   "Der Verfassungsschutz konnte den feindlichen Informanten rechtzeitig enttarnen.",
   "Der Verfassungsschutz konnte den feindlichen Informanten rechtzeitig [...].",
   "Intelligence services succeeded in unmasking the enemy informant in good time."),

  ("entwaffnen", "Gesellschaft & Politik", "Bildungssprachlich",
   "Armeen abrüsten oder Kritik durch Charme zunichtemachen", "To disarm militarily or disarm someone with charm/wit",
   "Gegner / Truppen entwaffnen", ["abrüsten", "überwältigen"],
   "Mit entwaffnender Offenheit räumte die Kandidatin ihre früheren Fehler ein.",
   "Mit [...] Offenheit räumte die Kandidatin ihre früheren Fehler ein.",
   "With disarming candor, the candidate conceded her past errors."),

  ("entwerfen", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Einen Bauplan, Entwurf oder ein zukunftsweisendes Konzept zeichnen", "To design, draft, outline or conceptualize",
   "einen Plan / Entwurf entwerfen", ["konzipieren", "skizzieren"],
   "Die Architektin entwarf einen spektakulären, klimaneutralen Museumsbau.",
   "Die Architektin [...] einen spektakulären, klimaneutralen Museumsbau.",
   "The architect designed a spectacular, climate-neutral museum building."),

  ("entziehen", "Recht & Verwaltung", "Formell",
   "Jemandem die Erlaubnis, Lizenz oder Lebensgrundlage wegnehmen (+ Dat.)", "To withdraw, revoke, deprive of or strip someone of a right",
   "jdm. die Fahrerlaubnis / das Vertrauen entziehen", ["aberkennen", "widerrufen"],
   "Das Parlament entzog dem amtierenden Regierungschef das Vertrauen.",
   "Das Parlament [...] dem amtierenden Regierungschef das Vertrauen.",
   "Parliament withdrew its confidence from the incumbent head of government."),

  ("entziffern", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Undeutliche Handschriften oder historische Schriften lesbar machen", "To decipher, decode or puzzle out illegible handwriting",
   "Hieroglyphen / eine Handschrift entziffern", ["lesen", "dechiffrieren"],
   "Nur wenige Spezialisten sind in der Lage, die Keilschrifttafeln zu entziffern.",
   "Nur wenige Spezialisten sind in der Lage, die Keilschrifttafeln zu [...].",
   "Only a few specialists are capable of deciphering the cuneiform tablets."),

  ("entwöhnen von", "Psychologie & Kognition", "Bildungssprachlich",
   "Sich oder jemanden schrittweise von einer Gewohnheit befreien", "To wean off, detach or break a habit",
   "sich entwöhnen von + Dat.", ["abgewöhnen", "lösen von"],
   "Es erfordert viel Geduld, sich von ungesunden Routinen zu entwöhnen.",
   "Es erfordert viel Geduld, sich von ungesunden Routinen zu [...].",
   "It requires much patience to wean oneself off unhealthy routines."),

  # ER- (198-200)
  ("erachten als", "Psychologie & Kognition", "Gehoben",
   "Etwas nach sorgfältiger Prüfung als zutreffend beurteilen", "To deem, judge, consider or hold to be (+ Akk.)",
   "erachten als + Akk.", ["betrachten als", "halten für"],
   "Der Verfassungsgerichtshof erachtete die Gesetzesklausel als nichtig.",
   "Der Verfassungsgerichtshof [...] die Gesetzesklausel als nichtig.",
   "The Constitutional Court deemed the statutory clause null and void."),

  ("erbeuten", "Gesellschaft & Politik", "Bildungssprachlich",
   "Bei einem Raubzug oder Krieg Beute machen", "To capture, plunder or seize booty/trophies",
   "wertvolle Dokumente / Beute erbeuten", ["erhaschen", "kapern"],
   "Hacker konnten vertrauliche Kundendatenbanken von Weltkonzernen erbeuten.",
   "Hacker konnten vertrauliche Kundendatenbanken von Weltkonzernen [...].",
   "Hackers were able to plunder confidential customer databases of multinationals."),

  ("erbringen", "Wirtschaft & Arbeit", "Formell",
   "Eine geforderte Leistung erbringen oder den Beweis führen", "To render a service, deliver performance or provide proof",
   "Leistungen / den Beweis erbringen", ["leisten", "nachweisen"],
   "Der Angeklagte konnte ein lückenloses Alibi für die Tatzeit erbringen.",
   "Der Angeklagte konnte ein lückenloses Alibi für die Tatzeit [...].",
   "The defendant was able to provide an airtight alibi for the time of the crime.")
]
