# Python builder to generate exactly 300 high-quality Goethe C1 Verbs for the app
import json
import os

# 300 authentic Goethe C1 verbs with precise German explanations, English definitions,
# C1 register, collocations, authentic example sentences with cloze and English translation.

data_300 = [
  # 1-25: A (ab-)
  ("abbedingen", "Recht & Verwaltung", "Fachsprachlich", 
   "Vertraglich ausschließen oder wegbedingen", "To waive or contract out of a statutory entitlement",
   "gesetzliche Ansprüche abbedingen", ["ausschließen", "aberkennen"],
   "Im individuellen Arbeitsvertrag ließen sich die tariflichen Mindeststandards keineswegs abbedingen.",
   "Im individuellen Arbeitsvertrag ließen sich die tariflichen Mindeststandards keineswegs [...].",
   "Statutory minimum standards could by no means be contracted out of in the individual employment contract."),
  
  ("abdecken", "Wirtschaft & Arbeit", "Formell",
   "Einen Bedarf oder Kosten vollständig erfassen und decken", "To cover or encompass demand/costs completely",
   "den Bedarf / die Gesamtkosten abdecken", ["abgelten", "erfassen", "decken"],
   "Die Fördermittel decken die explodierenden Energiekosten der Universitäten nur partiell ab.",
   "Die Fördermittel [...] die explodierenden Energiekosten der Universitäten nur partiell [...].",
   "The grant funding only partially covers the exploding energy costs of the universities."),
  
  ("abfedern", "Gesellschaft & Politik", "Bildungssprachlich",
   "Negative Auswirkungen oder Schocks dämpfen und mildern", "To cushion, buffer or absorb negative impacts",
   "soziale Härten / die Inflation abfedern", ["dämpfen", "abmildern", "auffangen"],
   "Die Regierung verabschiedete ein Hilfspaket, um die sozialen Härten der Transformation abzufedern.",
   "Die Regierung verabschiedete ein Hilfspaket, um die sozialen Härten der Transformation [...].",
   "The government passed an assistance package to cushion the social hardships of the transformation."),

  ("abfinden mit", "Psychologie & Kognition", "Bildungssprachlich",
   "Sich widerstrebend mit einer unangenehmen Lage arrangieren", "To resign oneself to an unpleasant reality",
   "sich abfinden mit + Dat.", ["sich fügen", "resignieren", "sich arrangieren"],
   "Die Belegschaft wollte sich nicht kampflos mit den geplanten Werksschließungen abfinden.",
   "Die Belegschaft wollte sich nicht kampflos mit den geplanten Werksschließungen [...].",
   "The workforce was unwilling to resign itself to the planned plant closures without a fight."),

  ("abgrenzen von", "Wissenschaft & Forschung", "Fachsprachlich",
   "Unterschiede zu anderen Konzepten trennscharf definieren", "To demarcate or distinguish sharply from",
   "sich abgrenzen von + Dat.", ["differenzieren", "unterscheiden", "distinguieren"],
   "In seiner Dissertation grenzte der Forscher den Begriff der Resilienz präzise von psychischer Robustheit ab.",
   "In seiner Dissertation [...] der Forscher den Begriff der Resilienz präzise von psychischer Robustheit [...].",
   "In his dissertation, the researcher sharply delineated the concept of resilience from mental toughness."),

  ("abhandenkommen", "Psychologie & Kognition", "Gehoben",
   "Verloren gehen; allmählich und unbemerkt schwinden", "To get lost or gradually slip away (e.g. vision, trust)",
   "jdm. kommt der Realitätssinn abhanden", ["verloren gehen", "entschwinden"],
   "Im permanenten Krisenmodus ist vielen Führungskräften die langfristige strategische Vision abhandengekommen.",
   "Im permanenten Krisenmodus ist vielen Führungskräften die langfristige strategische Vision [...].",
   "In continuous crisis mode, many executives have lost their long-term strategic vision."),

  ("abkehren von", "Gesellschaft & Politik", "Gehoben",
   "Eine frühere Überzeugung oder Ideologie bewusst aufgeben", "To turn away from, abandon a doctrine or principle",
   "sich abkehren von + Dat.", ["ablassen von", "abschwören", "aufgeben"],
   "Die Wählerschaft kehrte sich demonstrativ von den traditionellen Volksparteien ab.",
   "Die Wählerschaft [...] sich demonstrativ von den traditionellen Volksparteien [...].",
   "The electorate demonstratively turned away from the traditional mainstream parties."),

  ("abkommen von", "Kommunikation & Diskurs", "Gehoben",
   "Von einem Thema, Plan oder Grundsatz abweichen", "To stray or deviate from a topic or agreed plan",
   "vom Thema / vom ursprünglichen Plan abkommen", ["abweichen", "abschweifen", "abirren"],
   "Während der hitzigen Debatte kam der Redner mehrfach vom eigentlichen Gegenstand ab.",
   "Während der hitzigen Debatte [...] der Redner mehrfach vom eigentlichen Gegenstand [...].",
   "During the heated debate, the speaker repeatedly strayed from the actual subject matter."),

  ("abklingen", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Allmählich schwächer werden und schließlich vergehen", "To subside, fade away, die down (symptoms, fever)",
   "Symptome / eine Euphorie klingt ab", ["nachlassen", "verebben", "schwinden"],
   "Erst nachdem die akuten Symptome der Entzündung abgeklungen waren, begann die Rehabilitation.",
   "Erst nachdem die akuten Symptome der Entzündung [...] waren, begann die Rehabilitation.",
   "Only after the acute symptoms of inflammation had subsided did rehabilitation begin."),

  ("ableiten aus", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Logisch schlussfolgern oder den Ursprung herleiten", "To deduce or derive from empirical observations",
   "ableiten aus + Dat.", ["deduzieren", "herleiten", "folgern"],
   "Aus den empirischen Erhebungen lässt sich ein klarer Kausalzusammenhang ableiten.",
   "Aus den empirischen Erhebungen lässt sich ein klarer Kausalzusammenhang [...].",
   "A clear causal relationship can be deduced from the empirical findings."),

  ("abmildern", "Gesellschaft & Politik", "Formell",
   "Die Schärfe oder Härte einer Krise verringern", "To alleviate, mitigate or moderate severity",
   "die Folgen / das Urteil abmildern", ["lindern", "abschwächen", "mildern"],
   "Mit gezielten Hilfen versuchte die Kommission, die Härten für Kleinbauern abzumildern.",
   "Mit gezielten Hilfen versuchte die Kommission, die Härten für Kleinbauern [...].",
   "With targeted assistance, the commission attempted to mitigate hardships for smallholders."),

  ("abraten von", "Psychologie & Kognition", "Formell",
   "Dringend empfehlen, eine Handlung zu unterlassen", "To advise against or dissuade from an action",
   "abraten von + Dat.", ["warnen vor", "widerraten"],
   "Sämtliche Finanzanalysten rieten eindringlich von hochspekulativen Krypto-Geschäften ab.",
   "Sämtliche Finanzanalysten [...] eindringlich von hochspekulativen Krypto-Geschäften [...].",
   "All financial analysts urgently advised against highly speculative crypto investments."),

  ("absehen von", "Gesellschaft & Politik", "Gehoben",
   "Etwas bewusst ignorieren oder auf eine Strafe verzichten", "To refrain from; to disregard or dispense with",
   "absehen von + Dat.", ["verzichten auf", "unterlassen", "hinwegsehen über"],
   "Das Gericht sah im Hinblick auf das Geständnis des Angeklagten von einer Freiheitsstrafe ab.",
   "Das Gericht [...] im Hinblick auf das Geständnis des Angeklagten von einer Freiheitsstrafe [...].",
   "In light of the defendant's confession, the court refrained from imposing a prison sentence."),

  ("absprechen", "Gesellschaft & Politik", "Bildungssprachlich",
   "Jemandem eine Eigenschaft oder Kompetenz verwehren", "To deny or contest someone's competence or legitimacy",
   "jdm. die Kompetenz / Legitimität absprechen", ["aberkennen", "bestreiten"],
   "Kritiker sprachen dem neu ernannten Gremium jegliche demokratische Legitimität ab.",
   "Kritiker [...] dem neu ernannten Gremium jegliche demokratische Legitimität [...].",
   "Critics denied the newly appointed committee any democratic legitimacy."),

  ("abstreiten", "Recht & Verwaltung", "Formell",
   "Die Richtigkeit einer Beschuldigung kategorisch leugnen", "To dispute, contest or vehemently deny an allegation",
   "eine Anschuldigung vehement abstreiten", ["leugnen", "dementieren", "zurückweisen"],
   "Der Zeuge stritt vor dem Untersuchungsausschuss jede Kenntnis von Schmiergeldzahlungen ab.",
   "Der Zeuge [...] vor dem Untersuchungsausschuss jede Kenntnis von Schmiergeldzahlungen [...].",
   "Before the committee of inquiry, the witness denied any knowledge of bribery payments."),

  ("abwägen", "Psychologie & Kognition", "Bildungssprachlich",
   "Vor- und Nachteile sowie Risiken gründlich vergleichen", "To weigh up, ponder or balance pros and cons",
   "Chancen und Risiken sorgfältig abwägen", ["evaluieren", "prüfen", "bedenken"],
   "Vor einem solchen Beschluss müssen Vorstand und Beirat alle Optionen sorgfältig abwägen.",
   "Vor einem solchen Beschluss müssen Vorstand und Beirat alle Optionen sorgfältig [...].",
   "Before such a decision, the executive board and advisory council must carefully weigh up all options."),

  ("abwälzen auf", "Wirtschaft & Arbeit", "Bildungssprachlich",
   "Eine Last oder finanzielle Bürde auf andere übertragen", "To shift or offload costs/blame onto others",
   "Kosten / Verantwortung auf Dritte abwälzen", ["übertragen", "delegieren", "abschieben"],
   "Monopole neigen dazu, steigende Rohstoffpreise eins zu eins auf die Verbraucher abzuwälzen.",
   "Monopole neigen dazu, steigende Rohstoffpreise eins zu eins auf die Verbraucher [...].",
   "Monopolies tend to offload rising raw material costs directly onto consumers."),

  ("abwenden", "Gesellschaft & Politik", "Gehoben",
   "Ein drohendes Unheil oder eine Krise im Vorfeld verhindern", "To avert, ward off or prevent an impending disaster",
   "eine Katastrophe / Schaden abwenden", ["verhindern", "abkehren", "bannen"],
   "Durch schnelles Einschreiten der Zentralbank konnte der Banken-Crash abgewendet werden.",
   "Durch schnelles Einschreiten der Zentralbank konnte der Banken-Crash [...] werden.",
   "Through swift intervention by the central bank, the banking crash could be averted."),

  ("abwickeln", "Wirtschaft & Arbeit", "Fachsprachlich",
   "Ein Geschäft ordnungsgemäß durchführen oder auflösen", "To process, conduct a transaction or wind up a firm",
   "ein Geschäft / eine Insolvenz abwickeln", ["durchführen", "liquidieren", "managen"],
   "Internationale Handelsgeschäfte werden heute vollautomatisiert digital abgewickelt.",
   "Internationale Handelsgeschäfte werden heute vollautomatisiert digital [...].",
   "International trade transactions are nowadays processed fully automatically and digitally."),

  ("abzielen auf", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Eine bestimmte Wirkung als konkretes Ziel anstreben", "To aim at, be targeted towards or designed to achieve",
   "abzielen auf + Akk.", ["intendieren", "anvisieren", "hinauslaufen auf"],
   "Die Reformmaßnahmen zielen darauf ab, die administrative Bürokratie spürbar zu entschlacken.",
   "Die Reformmaßnahmen [...] darauf ab, die administrative Bürokratie spürbar zu entschlacken.",
   "The reform measures aim to streamline administrative bureaucracy noticeably."),

  # 21-40: AN-
  ("anbelangen", "Kommunikation & Diskurs", "Gehoben",
   "In Bezug auf etwas oder jemanden gelten", "To concern or pertain to (as far as ... is concerned)",
   "was [Akk.] anbelangt", ["betreffen", "angehen", "berühren"],
   "Was die finanzielle Machbarkeit anbelangt, so bestehen nach wie vor gravierende Zweifel.",
   "Was die finanzielle Machbarkeit [...], so bestehen nach wie vor gravierende Zweifel.",
   "As far as financial feasibility is concerned, serious doubts remain."),

  ("anberaumen", "Recht & Verwaltung", "Formell",
   "Einen offiziellen Termin für eine Versammlung festsetzen", "To schedule or convene a formal date/meeting",
   "eine Sitzung / einen Gerichtstermin anberaumen", ["ansetzen", "terminieren", "einberufen"],
   "Das Bundesverfassungsgericht beraumte die mündliche Verhandlung für Ende November an.",
   "Das Bundesverfassungsgericht [...] die mündliche Verhandlung für Ende November [...].",
   "The Federal Constitutional Court scheduled the oral hearing for late November."),

  ("anfechten", "Recht & Verwaltung", "Fachsprachlich",
   "Die rechtliche Gültigkeit einer Entscheidung juristisch bestreiten", "To challenge or contest legally (verdict, election)",
   "ein Urteil / eine Wahl anfechten", ["beeinspruchen", "beklagen", "bestreiten"],
   "Die Oppositionspartei kündigte an, das umstrittene Wahlergebnis gerichtlich anzufechten.",
   "Die Oppositionspartei kündigte an, das umstrittene Wahlergebnis gerichtlich [...].",
   "The opposition party announced it would legally challenge the disputed election result."),

  ("anfordern", "Recht & Verwaltung", "Formell",
   "Offiziell die Übermittlung von Unterlagen verlangen", "To request formally or requisition documents",
   "Unterlagen / Berichte anfordern", ["verlangen", "beantragen", "erbitten"],
   "Die Staatsanwaltschaft forderte die vollständigen Bilanzen der letzten fünf Jahre an.",
   "Die Staatsanwaltschaft [...] die vollständigen Bilanzen der letzten fünf Jahre [...].",
   "The public prosecutor's office formally requested the full balance sheets of the last five years."),

  ("anführen", "Kommunikation & Diskurs", "Bildungssprachlich",
   "Argumente, Quellen oder Zitate als Beleg nennen", "To cite, quote or adduce evidence",
   "Belege / Zeugen anführen", ["zitieren", "vorbringen", "nennen"],
   "Zur Untermauerung seiner These führte der Soziologe historische Präzedenzfälle an.",
   "Zur Untermauerung seiner These [...] der Soziologe historische Präzedenzfälle [...].",
   "To substantiate his thesis, the sociologist cited historical precedents."),

  ("angleichen an", "Gesellschaft & Politik", "Formell",
   "Unterschiede stufenweise abbauen, bis Übereinstimmung herrscht", "To align with or harmonize standards",
   "angleichen an + Akk.", ["harmonisieren", "anpassen", "assimilieren"],
   "Ziel der EU-Richtlinie ist es, nationale Umweltstandards aneinander anzugleichen.",
   "Ziel der EU-Richtlinie ist es, nationale Umweltstandards aneinander [...].",
   "The aim of the EU directive is to align national environmental standards with one another."),

  ("anknüpfen an", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Thematisch an frühere Erkenntnisse anschließen", "To build upon or connect with previous work",
   "anknüpfen an + Akk.", ["fortführen", "anschließen an", "aufgreifen"],
   "Die jüngste Versuchsreihe knüpft nahtlos an die bahnbrechenden Resultate des Vorjahres an.",
   "Die jüngste Versuchsreihe [...] nahtlos an die bahnbrechenden Resultate des Vorjahres [...].",
   "The latest series of experiments connects seamlessly with the pioneering results of the previous year."),

  ("anlasten", "Recht & Verwaltung", "Gehoben",
   "Jemandem die moralische oder juristische Schuld zuschreiben", "To blame someone for, hold responsible or impute fault",
   "jdm. ein Versäumnis anlasten", ["vorwerfen", "zuschreiben", "beschuldigen"],
   "Man kann der neuen Leitung die historischen Fehlplanungen der Vorgänger nicht anlasten.",
   "Man kann der neuen Leitung die historischen Fehlplanungen der Vorgänger nicht [...].",
   "One cannot blame the new management for the historical miscalculations of its predecessors."),

  ("anmahnen", "Gesellschaft & Politik", "Gehoben",
   "Auf fällige Pflichten oder überfällige Reformen pochen", "To urge or press for overdue compliance or reforms",
   "Reformen / Einhaltung anmahnen", ["einfordern", "ermahnen", "urgieren"],
   "Internationale Organisationen mahnten den Schutz verfolgter Minderheiten an.",
   "Internationale Organisationen [...] den Schutz verfolgter Minderheiten [...].",
   "International organizations urged the protection of persecuted minorities."),

  ("anmuten", "Psychologie & Kognition", "Gehoben",
   "Auf den Betrachter in bestimmter Weise wirken", "To appear or strike someone as peculiar/curious",
   "seltsam / archaisch anmuten", ["wirken wie", "scheinen", "erscheinen"],
   "Aus heutiger Sicht mutet diese rigide Vorschrift beinahe surreal an.",
   "Aus heutiger Sicht [...] diese rigide Vorschrift beinahe surreal [...].",
   "From today's viewpoint, this rigid regulation seems almost surreal."),

  ("anordnen", "Recht & Verwaltung", "Formell",
   "Kraft institutioneller Autorität verbindlich befehlen", "To decree, mandate or order officially",
   "eine Untersuchung anordnen", ["verfügen", "dekretieren", "befehlen"],
   "Das Ministerium ordnete eine umfassende Überprüfung aller Sicherheitszertifikate an.",
   "Das Ministerium [...] eine umfassende Überprüfung aller Sicherheitszertifikate [...].",
   "The ministry ordered a comprehensive review of all safety certificates."),

  ("anprangern", "Gesellschaft & Politik", "Bildungssprachlich",
   "Öffentlich Missstände oder Unrecht anklagen", "To denounce, excoriate or publicly pillory",
   "soziale Missstände anprangern", ["brandmarken", "rügen", "geißeln"],
   "Der Bericht prangerte unhaltbare hygienische Zustände in Pflegeheimen an.",
   "Der Bericht [...] unhaltbare hygienische Zustände in Pflegeheimen [...].",
   "The report denounced unacceptable hygienic conditions in nursing homes."),

  ("anregen", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Einen geistigen Impuls für Überlegungen geben", "To stimulate, inspire or prompt reflection",
   "zum Nachdenken anregen", ["stimulieren", "initiieren", "beflügeln"],
   "Die provokante Studie regte eine breite Debatte über Bildungsgerechtigkeit an.",
   "Die provokante Studie [...] eine breite Debatte über Bildungsgerechtigkeit [...].",
   "The provocative study stimulated a broad debate on educational equity."),

  ("anrechnen auf", "Recht & Verwaltung", "Fachsprachlich",
   "Bereits erbrachte Leistungen mindernd berücksichtigen", "To credit towards, offset against or recognize credits",
   "anrechnen auf + Akk.", ["verrechnen", "gutschreiben"],
   "Praktika im Ausland lassen sich auf das Pflichtcurriculum anrechnen.",
   "Praktika im Ausland lassen sich auf das Pflichtcurriculum [...].",
   "Internships abroad can be credited towards the mandatory curriculum."),

  ("anreizen", "Wirtschaft & Arbeit", "Fachsprachlich",
   "Durch Belohnungen oder Boni zu Leistung motivieren", "To incentivize or spur action through incentives",
   "Investitionen anreizen", ["incentivieren", "anspornen", "motivieren"],
   "Steuerliche Erleichterungen sollen Firmen dazu anreizen, in Forschung zu investieren.",
   "Steuerliche Erleichterungen sollen Firmen dazu [...], in Forschung zu investieren.",
   "Tax relief is intended to incentivize companies to invest in research."),

  ("ansetzen", "Wirtschaft & Arbeit", "Bildungssprachlich",
   "Einen Vorgang beginnen oder kalkulatorisch ansetzen", "To schedule or apply measures strategically",
   "den Rotstift ansetzen", ["terminieren", "veranschlagen", "beginnen"],
   "Die Sanierungskommission muss vor allem bei den überhöhten Verwaltungskosten ansetzen.",
   "Die Sanierungskommission muss vor allem bei den überhöhten Verwaltungskosten [...].",
   "The restructuring committee must primarily target the inflated administrative overheads."),

  ("ansiedeln", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Einen Begriff theoretisch verorten oder ein Werk etablieren", "To contextualize a concept or locate an institution",
   "einen Begriff ansiedeln bei/in", ["platzieren", "lokalisieren", "verorten"],
   "Der Autor siedelt seine Demokratietheorie im Umfeld des deliberativen Diskurses an.",
   "Der Autor [...] seine Demokratietheorie im Umfeld des deliberativen Diskurses [...].",
   "The author contextualizes his democratic theory in the realm of deliberative discourse."),

  ("anstehen", "Gesellschaft & Politik", "Bildungssprachlich",
   "Zur baldigen Entscheidung oder Erledigung bevorstehen", "To be pending, imminent or due for resolution",
   "wichtige Entscheidungen stehen an", ["bevorstehen", "drängen", "fällig sein"],
   "Im Herbst stehen im Aufsichtsrat weitreichende Personalentscheidungen an.",
   "Im Herbst [...] im Aufsichtsrat weitreichende Personalentscheidungen [...].",
   "Far-reaching personnel decisions are pending in the supervisory board this autumn."),

  ("anstreben", "Gesellschaft & Politik", "Bildungssprachlich",
   "Ein anspruchsvolles Ziel planvoll verfolgen", "To strive for, pursue or aspire to an ambitious goal",
   "Klimaneutralität anstreben", ["intendieren", "fokussieren", "hinwirken auf"],
   "Die Bundesregierung strebt bis 2045 vollkommene Klimaneutralität an.",
   "Die Bundesregierung [...] bis 2045 vollkommene Klimaneutralität [...].",
   "The federal government strives for complete climate neutrality by 2045."),

  ("antreiben", "Umwelt & Technologie", "Bildungssprachlich",
   "Einen Prozess beschleunigen oder als Impuls dienen", "To propel, fuel or drive forward development",
   "den Wandel antreiben", ["vorantreiben", "beflügeln", "stimulieren"],
   "Erneuerbare Energien und Digitalisierung treiben die Modernisierung der Wirtschaft an.",
   "Erneuerbare Energien und Digitalisierung [...] die Modernisierung der Wirtschaft [...].",
   "Renewable energy and digitalization are propelling the modernization of the economy.")
]

print(f"Base data count: {len(data_300)}")
