// Script to generate 300 comprehensive Goethe C1 Verbs
const fs = require('fs');
const path = require('path');

// 300 authentic Goethe-Zertifikat C1 verbs with definitions, collocations, context sentences and English translations
const rawVerbsList = [
  // A
  {
    w: "abbedingen",
    de: "Vertraglich ausschließen oder wegbedingen",
    en: "To exclude, waive or contract out of a statutory provision",
    cat: "Wirtschaft & Arbeit",
    reg: "Fachsprachlich",
    coll: "gesetzliche Ansprüche abbedingen",
    syn: ["ausschließen", "aberkennen", "wegbedingen"],
    sent: "Im individuellen Arbeitsvertrag ließen sich die tariflichen Mindeststandards keineswegs abbedingen.",
    cloze: "Im individuellen Arbeitsvertrag ließen sich die tariflichen Mindeststandards keineswegs [...].",
    enSent: "Statutory minimum standards could by no means be contracted out of in the individual employment contract."
  },
  {
    w: "abdecken",
    de: "Einen Bedarf, ein Themenspektrum oder Kosten vollständig erfassen und finanzieren",
    en: "To cover, encompass or satisfy a demand/cost/topic",
    cat: "Wirtschaft & Arbeit",
    reg: "Formell",
    coll: "einen Bedarf / die Kosten abdecken",
    syn: ["abgelten", "erfassen", "decken"],
    sent: "Die bereitgestellten Fördermittel decken die explodierenden Energiekosten der Universitäten nur partiell ab.",
    cloze: "Die bereitgestellten Fördermittel [...] die explodierenden Energiekosten der Universitäten nur partiell [...].",
    enSent: "The provided subsidies only partially cover the exploding energy costs of the universities."
  },
  {
    w: "abfedern",
    de: "Negative Auswirkungen, Schocks oder Härten dämpfen und mildern",
    en: "To cushion, absorb or buffer negative impacts/hardships",
    cat: "Gesellschaft & Politik",
    reg: "Bildungssprachlich",
    coll: "soziale Härten / die Inflation abfedern",
    syn: ["dämpfen", "abmildern", "auffangen"],
    sent: "Die Regierung verabschiedete ein Hilfspaket, um die sozialen Härten der Transformation abzufedern.",
    cloze: "Die Regierung verabschiedete ein Hilfspaket, um die sozialen Härten der Transformation [...].",
    enSent: "The government passed an assistance package to cushion the social hardships of the transformation."
  },
  {
    w: "abfinden mit",
    de: "Sich widerstrebend mit einer unangenehmen Gegebenheit resigniert arrangieren",
    en: "To resign oneself to; to come to terms with an unpleasant reality",
    cat: "Psychologie & Kognition",
    reg: "Bildungssprachlich",
    coll: "sich abfinden mit + Dat.",
    syn: ["sich fügen", "resignieren", "sich arrangieren"],
    sent: "Die Belegschaft wollte sich nicht kampflos mit den geplanten Werksschließungen abfinden.",
    cloze: "Die Belegschaft wollte sich nicht kampflos mit den geplanten Werksschließungen [...].",
    enSent: "The workforce was unwilling to resign itself to the planned plant closures without a fight."
  },
  {
    w: "abgrenzen von",
    de: "Unterschiede zu anderen Konzepten oder Phänomenen trennscharf definieren",
    en: "To demarcate, delineate or distinguish sharply from",
    cat: "Wissenschaft & Forschung",
    reg: "Wissenschaft & Forschung",
    coll: "sich abgrenzen von + Dat.",
    syn: ["differenzieren", "unterscheiden", "distinguieren"],
    sent: "In seiner Dissertation grenzte der Forscher den Begriff der Resilienz präzise von psychischer Robustheit ab.",
    cloze: "In seiner Dissertation [...] der Forscher den Begriff der Resilienz präzise von psychischer Robustheit [...].",
    enSent: "In his dissertation, the researcher sharply delineated the concept of resilience from mere mental toughness."
  },
  {
    w: "abhandenkommen",
    de: "Verloren gehen; allmählich und unbemerkt schwinden",
    en: "To get lost; to be misplaced; to lose gradually (e.g., trust, sense of reality)",
    cat: "Psychologie & Kognition",
    reg: "Gehoben",
    coll: "jdm. kommt der Realitätssinn abhanden",
    syn: ["verloren gehen", "entschwinden", "verlieren"],
    sent: "Im Zuge des permanenten Krisenmanagements ist vielen Führungskräften die langfristige strategische Vision abhandengekommen.",
    cloze: "Im Zuge des permanenten Krisenmanagements ist vielen Führungskräften die langfristige strategische Vision [...].",
    enSent: "In the course of permanent crisis management, many executives have lost their long-term strategic vision."
  },
  {
    w: "abkehren von",
    de: "Eine frühere Überzeugung, Ideologie oder Methode bewusst aufgeben",
    en: "To turn away from; to abandon a doctrine, policy or principle",
    cat: "Gesellschaft & Politik",
    reg: "Gehoben",
    coll: "sich abkehren von + Dat.",
    syn: ["ablassen von", "abschwören", "aufgeben"],
    sent: "Die Wählerschaft kehrte sich demonstrativ von den traditionellen Volksparteien ab.",
    cloze: "Die Wählerschaft [...] sich demonstrativ von den traditionellen Volksparteien [...].",
    enSent: "The electorate demonstratively turned away from the traditional mainstream parties."
  },
  {
    w: "abkommen von",
    de: "Von einem eingeschlagenen Pfad, Thema oder Grundsatz abweichen",
    en: "To stray, deviate from a topic, path or agreed principle",
    cat: "Kommunikation & Diskurs",
    reg: "Gehoben",
    coll: "vom Thema / vom ursprünglichen Plan abkommen",
    syn: ["abweichen", "abschweifen", "abirren"],
    sent: "Während der hitzigen Plenardebatte kam der Redner mehrfach vom eigentlichen Gegenstand ab.",
    cloze: "Während der hitzigen Plenardebatte [...] der Redner mehrfach vom eigentlichen Gegenstand [...].",
    enSent: "During the heated plenary debate, the speaker repeatedly strayed from the actual subject matter."
  },
  {
    w: "abklingen",
    de: "Allmählich schwächer werden und schließlich ganz aufhören",
    en: "To subside, fade away, die down (of symptoms, excitement, applause)",
    cat: "Wissenschaft & Forschung",
    reg: "Bildungssprachlich",
    coll: "Symptome / eine Euphorie klingt ab",
    syn: ["nachlassen", "verebben", "schwinden"],
    sent: "Erst nachdem die akuten Symptome der Entzündung abgeklungen waren, konnte die Reha beginnen.",
    cloze: "Erst nachdem die akuten Symptome der Entzündung [...] waren, konnte die Reha beginnen.",
    enSent: "Only after the acute symptoms of inflammation had subsided could rehabilitation begin."
  },
  {
    w: "ableiten aus/von",
    de: "Logisch schlussfolgern oder den Ursprung eines Sachverhalts herleiten",
    en: "To deduce, derive from; to trace origins",
    cat: "Wissenschaft & Forschung",
    reg: "Bildungssprachlich",
    coll: "ableiten aus + Dat. / von + Dat.",
    syn: ["deduzieren", "herleiten", "folgern"],
    sent: "Aus den empirischen Erhebungen lässt sich ein klarer Kausalzusammenhang ableiten.",
    cloze: "Aus den empirischen Erhebungen lässt sich ein klarer Kausalzusammenhang [...].",
    enSent: "A clear causal relationship can be deduced from the empirical findings."
  },
  {
    w: "abmildern",
    de: "Die Schärfe, Wucht oder Konsequenzen einer Krise verringern",
    en: "To alleviate, mitigate or moderate severity",
    cat: "Gesellschaft & Politik",
    reg: "Formell",
    coll: "die Folgen / das Urteil abmildern",
    syn: ["lindern", "abschwächen", "mildern"],
    sent: "Mit flankierenden Fördermaßnahmen versuchte die Kommission, die Härten für Kleinbauern abzumildern.",
    cloze: "Mit flankierenden Fördermaßnahmen versuchte die Kommission, die Härten für Kleinbauern [...].",
    enSent: "With flanking supportive measures, the commission attempted to mitigate hardships for smallholders."
  },
  {
    w: "abraten von",
    de: "Jemandem dringend empfehlen, eine bestimmte Handlung zu unterlassen",
    en: "To advise against, dissuade from doing something",
    cat: "Psychologie & Kognition",
    reg: "Formell",
    coll: "abraten von + Dat.",
    syn: ["warnen vor", "widerraten", "abmahnen"],
    sent: "Sämtliche Finanzanalysten rieten eindringlich von hochspekulativen Derivatgeschäften ab.",
    cloze: "Sämtliche Finanzanalysten [...] eindringlich von hochspekulativen Derivatgeschäften [...].",
    enSent: "All financial analysts urgently advised against highly speculative derivative transactions."
  },
  {
    w: "absehen von",
    de: "Etwas bewusst unberücksichtigt lassen; von einer Maßnahme oder Sanktion ablassen",
    en: "To refrain from; to disregard or dispense with something",
    cat: "Gesellschaft & Politik",
    reg: "Gehoben",
    coll: "absehen von + Dat.",
    syn: ["verzichten auf", "unterlassen", "hinwegsehen über"],
    sent: "Das Gericht sah im Hinblick auf das Geständnis des Angeklagten von einer Freiheitsstrafe ab.",
    cloze: "Das Gericht [...] im Hinblick auf das Geständnis des Angeklagten von einer Freiheitsstrafe [...].",
    enSent: "In light of the defendant's confession, the court refrained from imposing a prison sentence."
  },
  {
    w: "absprechen",
    de: "Jemandem eine Eigenschaft, Kompetenz oder Berechtigung demonstrativ verwehren",
    en: "To deny, dispute or contest someone's competence, right or quality",
    cat: "Gesellschaft & Politik",
    reg: "Bildungssprachlich",
    coll: "jdm. die Kompetenz / Legitimität absprechen",
    syn: ["aberkennen", "bestreiten", "in Abrede stellen"],
    sent: "Kritiker sprachen dem neu ernannten Gremium jegliche demokratische Legitimität ab.",
    cloze: "Kritiker [...] dem neu ernannten Gremium jegliche demokratische Legitimität [...].",
    enSent: "Critics denied the newly appointed committee any democratic legitimacy."
  },
  {
    w: "abstreiten",
    de: "Die Wahrheit einer Behauptung oder Beschuldigung kategorisch leugnen",
    en: "To dispute, contest or vehemently deny an allegation",
    cat: "Recht & Verwaltung",
    reg: "Formell",
    coll: "eine Anschuldigung vehement abstreiten",
    syn: ["leugnen", "dementieren", "zurückweisen"],
    sent: "Der Zeuge stritt vor dem Untersuchungsausschuss jede Kenntnis von Schmiergeldzahlungen ab.",
    cloze: "Der Zeuge [...] vor dem Untersuchungsausschuss jede Kenntnis von Schmiergeldzahlungen [...].",
    enSent: "Before the committee of inquiry, the witness denied any knowledge of bribery payments."
  },
  {
    w: "abwägen",
    de: "Vor- und Nachteile sowie Risiken gründlich und besonnen gegeneinander prüfen",
    en: "To weigh up, ponder or carefully balance pros and cons",
    cat: "Psychologie & Kognition",
    reg: "Bildungssprachlich",
    coll: "Chancen und Risiken sorgfältig abwägen",
    syn: ["evaluieren", "prüfen", "bedenken"],
    sent: "Vor einem derart folgenschweren Beschluss müssen Vorstand und Betriebsrat alle Optionen sorgfältig abwägen.",
    cloze: "Vor einem derart folgenschweren Beschluss müssen Vorstand und Betriebsrat alle Optionen sorgfältig [...].",
    enSent: "Before such a momentous decision, the executive board and works council must carefully weigh up all options."
  },
  {
    w: "abwälzen auf",
    de: "Eine Last, Pflicht oder finanzielle Bürde unangemessen auf andere übertragen",
    en: "To shift, offload onto others (costs, blame, burdens)",
    cat: "Wirtschaft & Arbeit",
    reg: "Bildungssprachlich",
    coll: "Kosten / Verantwortung auf Dritte abwälzen",
    syn: ["übertragen", "delegieren", "abschieben"],
    sent: "Monopolistische Konzerne neigen dazu, steigende Rohstoffpreise eins zu eins auf die Verbraucher abzuwälzen.",
    cloze: "Monopolistische Konzerne neigen dazu, steigende Rohstoffpreise eins zu eins auf die Verbraucher [...].",
    enSent: "Monopolistic corporations tend to offload rising raw material costs directly onto consumers."
  },
  {
    w: "abwenden",
    de: "Ein drohendes Unheil oder eine akute Krise im Vorfeld verhindern",
    en: "To avert, ward off, stave off an impending disaster",
    cat: "Gesellschaft & Politik",
    reg: "Gehoben",
    coll: "eine Katastrophe / Schaden abwenden",
    syn: ["verhindern", "abkehren", "bannen"],
    sent: "Durch entschlossenes Einschreiten der Zentralbank konnte ein Kollaps des Finanzsystems abgewendet werden.",
    cloze: "Durch entschlossenes Einschreiten der Zentralbank konnte ein Kollaps des Finanzsystems [...] werden.",
    enSent: "Decisive intervention by the central bank succeeded in averting a collapse of the financial system."
  },
  {
    w: "abzielen auf",
    de: "Eine bestimmte Absicht oder Wirkung als konkretes Ziel anstreben",
    en: "To aim at, be targeted towards, be designed to achieve",
    cat: "Wissenschaft & Forschung",
    reg: "Bildungssprachlich",
    coll: "abzielen auf + Akk.",
    syn: ["intendieren", "anvisieren", "hinauslaufen auf"],
    sent: "Die Reformmaßnahmen zielen darauf ab, die administrative Bürokratie spürbar zu entschlacken.",
    cloze: "Die Reformmaßnahmen [...] darauf ab, die administrative Bürokratie spürbar zu entschlacken.",
    enSent: "The reform measures aim to streamline administrative bureaucracy noticeably."
  },
  {
    w: "anbelangen",
    de: "In Bezug auf etwas oder jemanden gelten (oft idiomatisch verwendet)",
    en: "To concern, pertain to (as far as ... is concerned)",
    cat: "Kommunikation & Diskurs",
    reg: "Gehoben",
    coll: "was [Akk.] anbelangt",
    syn: ["betreffen", "angehen", "berühren"],
    sent: "Was die finanzielle Machbarkeit anbelangt, so bestehen nach wie vor gravierende Zweifel im Beirat.",
    cloze: "Was die finanzielle Machbarkeit [...], so bestehen nach wie vor gravierende Zweifel im Beirat.",
    enSent: "As far as financial feasibility is concerned, serious doubts remain within the advisory board."
  },
  {
    w: "anberaumen",
    de: "Einen offiziellen Termin für eine Versammlung oder Gerichtsverhandlung festsetzen",
    en: "To schedule, convene or fix a formal date/meeting",
    cat: "Recht & Verwaltung",
    reg: "Formell",
    coll: "eine Sitzung / einen Gerichtstermin anberaumen",
    syn: ["ansetzen", "terminieren", "einberufen"],
    sent: "Das Bundesverfassungsgericht beraumte die mündliche Verhandlung für Ende November an.",
    cloze: "Das Bundesverfassungsgericht [...] die mündliche Verhandlung für Ende November [...].",
    enSent: "The Federal Constitutional Court scheduled the oral hearing for late November."
  },
  {
    w: "anfechten",
    de: "Die rechtliche Gültigkeit einer Wahl, Klausel oder Entscheidung juristisch bestreiten",
    en: "To challenge, contest or dispute legally (a verdict, election, will)",
    cat: "Recht & Verwaltung",
    reg: "Fachsprachlich",
    coll: "ein Urteil / eine Wahl anfechten",
    syn: ["beeinspruchen", "beklagen", "bestreiten"],
    sent: "Die unterlegene Partei kündigte umgehend an, das umstrittene Wahlergebnis gerichtlich anzufechten.",
    cloze: "Die unterlegene Partei kündigte umgehend an, das umstrittene Wahlergebnis gerichtlich [...].",
    enSent: "The defeated party immediately announced it would legally challenge the disputed election result."
  },
  {
    w: "anfordern",
    de: "Offiziell und nachdrücklich die Zusendung von Unterlagen oder personeller Unterstützung verlangen",
    en: "To request formally, requisition or summon resources",
    cat: "Recht & Verwaltung",
    reg: "Formell",
    coll: "Unterlagen / Verstärkung anfordern",
    syn: ["verlangen", "beantragen", "erbitten"],
    sent: "Die Staatsanwaltschaft forderte die vollständigen Geschäftsberichte der letzten fünf Jahre an.",
    cloze: "Die Staatsanwaltschaft [...] die vollständigen Geschäftsberichte der letzten fünf Jahre [...].",
    enSent: "The public prosecutor's office formally requested the full annual financial reports of the last five years."
  },
  {
    w: "anführen",
    de: "Argumente, Beispiele oder Quellen als Beleg zitieren und ins Feld führen",
    en: "To cite, quote, adduce evidence or lead an organization",
    cat: "Kommunikation & Diskurs",
    reg: "Bildungssprachlich",
    coll: "Belege / Zeugen ins Feld führen / anführen",
    syn: ["zitieren", "vorbringen", "nennen"],
    sent: "Zur Untermauerung seiner provokanten These führte der Soziologe zahlreiche historische Präzedenzfälle an.",
    cloze: "Zur Untermauerung seiner provokanten These [...] der Soziologe zahlreiche historische Präzedenzfälle [...].",
    enSent: "To substantiate his provocative thesis, the sociologist cited numerous historical precedents."
  },
  {
    w: "angleichen an",
    de: "Bestehende Unterschiede stufenweise beseitigen, bis Gleichförmigkeit herrscht",
    en: "To align with, harmonize or assimilate to a standard",
    cat: "Gesellschaft & Politik",
    reg: "Formell",
    coll: "angleichen an + Akk.",
    syn: ["harmonisieren", "anpassen", "assimilieren"],
    sent: "Ziel der EU-Richtlinie ist es, die nationalen Umweltstandards sukzessive aneinander anzugleichen.",
    cloze: "Ziel der EU-Richtlinie ist es, die nationalen Umweltstandards sukzessive aneinander [...].",
    enSent: "The aim of the EU directive is to gradually align national environmental standards with one another."
  },
  {
    w: "anknüpfen an",
    de: "Thematisch oder methodisch an frühere Erkenntnisse oder Traditionen anschließen",
    en: "To build upon, pick up on or connect with previous work",
    cat: "Wissenschaft & Forschung",
    reg: "Bildungssprachlich",
    coll: "anknüpfen an + Akk.",
    syn: ["fortführen", "anschließen an", "aufgreifen"],
    sent: "Die jüngste Versuchsreihe knüpft nahtlos an die bahnbrechenden Resultate des Vorjahres an.",
    cloze: "Die jüngste Versuchsreihe [...] nahtlos an die bahnbrechenden Resultate des Vorjahres [...].",
    enSent: "The latest series of experiments connects seamlessly with the pioneering findings of the previous year."
  },
  {
    w: "anlasten",
    de: "Jemandem die moralische oder juristische Schuld für ein Vergehen zuschreiben",
    en: "To blame someone for, hold responsible or impute fault to someone",
    cat: "Recht & Verwaltung",
    reg: "Gehoben",
    coll: "jdm. ein Versäumnis anlasten",
    syn: ["vorwerfen", "zuschreiben", "beschuldigen"],
    sent: "Man kann der neuen Abteilungsleitung die historischen Fehlplanungen ihrer Vorgänger nicht anlasten.",
    cloze: "Man kann der neuen Abteilungsleitung die historischen Fehlplanungen ihrer Vorgänger nicht [...].",
    enSent: "One cannot hold the new departmental management responsible for the historic miscalculations of its predecessors."
  },
  {
    w: "anmahnen",
    de: "Auf fällige Pflichten, Fristen oder längst überfällige Reformen nachdrücklich pochen",
    en: "To urge, admonish or press for overdue compliance/action",
    cat: "Gesellschaft & Politik",
    reg: "Gehoben",
    coll: "Reformen / Einhaltung der Fristen anmahnen",
    syn: ["einfordern", "ermahnen", "urgieren"],
    sent: "Internationale Menschenrechtsorganisationen mahnten wiederholt den Schutz verfolgter Minderheiten an.",
    cloze: "Internationale Menschenrechtsorganisationen [...] wiederholt den Schutz verfolgter Minderheiten [...].",
    enSent: "International human rights organizations repeatedly urged the protection of persecuted minorities."
  },
  {
    w: "anmuten",
    de: "Auf das Gemüt oder den Betrachter in bestimmter Weise wirken",
    en: "To appear, strike someone as, seem curious/bizarre",
    cat: "Psychologie & Kognition",
    reg: "Gehoben",
    coll: "seltsam / archaisch anmuten",
    syn: ["wirken wie", "scheinen", "erscheinen"],
    sent: "Aus heutiger Sicht mutet diese rigide bürokratische Vorschrift beinahe absurd an.",
    cloze: "Aus heutiger Sicht [...] diese rigide bürokratische Vorschrift beinahe absurd [...].",
    enSent: "From today's perspective, this rigid bureaucratic regulation seems almost absurd."
  },
  {
    w: "anordnen",
    de: "Kraft amtlicher oder institutioneller Autorität verbindlich verfügen",
    en: "To order, decree or mandate officially",
    cat: "Recht & Verwaltung",
    reg: "Formell",
    coll: "eine Untersuchung / Quarantäne anordnen",
    syn: ["verfügen", "dekretieren", "befehlen"],
    sent: "Angesichts der rasanten Ausbreitung des Erregers ordnete die Gesundheitsbehörde strenge Auflagen an.",
    cloze: "Angesichts der rasanten Ausbreitung des Erregers [...] die Gesundheitsbehörde strenge Auflagen [...].",
    enSent: "Given the rapid spread of the pathogen, the health authority ordered stringent restrictions."
  },
  {
    w: "anprangern",
    de: "Öffentlich und unmissverständlich schwere Missstände oder Unrecht brandmarken",
    en: "To denounce, excoriate or pillory public grievances/wrongs",
    cat: "Gesellschaft & Politik",
    reg: "Bildungssprachlich",
    coll: "soziale Ungerechtigkeit öffentlich anprangern",
    syn: ["brandmarken", "rügen", "geißeln"],
    sent: "Der Investigativjournalist prangerte in seiner Reportage die katastrophalen Arbeitsbedingungen in den Fabriken an.",
    cloze: "Der Investigativjournalist [...] in seiner Reportage die katastrophalen Arbeitsbedingungen in den Fabriken [...].",
    enSent: "In his investigative report, the journalist denounced the catastrophic working conditions in the factories."
  },
  {
    w: "anregen",
    de: "Einen fruchtbaren Impuls oder Gedankenanstoß für weitere Überlegungen geben",
    en: "To stimulate, prompt, inspire or initiate reflection",
    cat: "Wissenschaft & Forschung",
    reg: "Bildungssprachlich",
    coll: "eine Diskussion / zum Nachdenken anregen",
    syn: ["stimulieren", "initiieren", "beflügeln"],
    sent: "Die provokante These des Professors regte eine leidenschaftliche Kontroverse im Seminar an.",
    cloze: "Die provokante These des Professors [...] eine leidenschaftliche Kontroverse im Seminar [...].",
    enSent: "The professor's provocative thesis stimulated a passionate controversy in the seminar."
  },
  {
    w: "anrechnen auf",
    de: "Bereits erbrachte Leistungen oder Vorstrafen mindernd berücksichtigen",
    en: "To credit towards, offset against or take into account",
    cat: "Recht & Verwaltung",
    reg: "Fachsprachlich",
    coll: "anrechnen auf + Akk.",
    syn: ["verrechnen", "gutschreiben", "in Abzug bringen"],
    sent: "Bereits im Ausland absolvierte Studienleistungen lassen sich problemlos auf das Masterstudium anrechnen.",
    cloze: "Bereits im Ausland absolvierte Studienleistungen lassen sich problemlos auf das Masterstudium [...].",
    enSent: "Academic credits already completed abroad can easily be credited towards the master's degree."
  },
  {
    w: "anreizen",
    de: "Durch attraktive Belohnungen oder Vergünstigungen zu verstärktem Engagement motivieren",
    en: "To incentivize, spur or motivate through incentives",
    cat: "Wirtschaft & Arbeit",
    reg: "Fachsprachlich",
    coll: "Investitionen / Innovationen anreizen",
    syn: ["incentivieren", "anspornen", "motivieren"],
    sent: "Steuervergünstigungen sollen mittelständische Betriebe dazu anreizen, in grüne Technologien zu investieren.",
    cloze: "Steuervergünstigungen sollen mittelständische Betriebe dazu [...], in grüne Technologien zu investieren.",
    enSent: "Tax incentives are intended to spur medium-sized enterprises to invest in green technologies."
  },
  {
    w: "ansetzen",
    de: "Etwas an einem bestimmten Punkt beginnen oder planvoll kalkulieren",
    en: "To schedule, apply a measure or assess value",
    cat: "Wirtschaft & Arbeit",
    reg: "Bildungssprachlich",
    coll: "den Rotstift / eine Frist ansetzen",
    syn: ["terminieren", "veranschlagen", "beginnen"],
    sent: "Um das Budgetdefizit auszugleichen, muss man den Sparhebel vor allem bei den Verwaltungskosten ansetzen.",
    cloze: "Um das Budgetdefizit auszugleichen, muss man den Sparhebel vor allem bei den Verwaltungskosten [...].",
    enSent: "To balance the budget deficit, austerity measures must be applied primarily to administrative overheads."
  },
  {
    w: "ansiedeln bei/in",
    de: "Ein Unternehmen etablieren oder einen Begriff in einem theoretischen Kontext verorten",
    en: "To settle, locate a business or contextualize a concept",
    cat: "Wissenschaft & Forschung",
    reg: "Bildungssprachlich",
    coll: "ein Unternehmen / einen Begriff ansiedeln",
    syn: ["platzieren", "lokalisieren", "verorten"],
    sent: "Der Philosoph siedelte seine Diskursethik im Spannungsfeld zwischen Kantischer Pflichtlehre und Moderne an.",
    cloze: "Der Philosoph [...] seine Diskursethik im Spannungsfeld zwischen Kantischer Pflichtlehre und Moderne [...].",
    enSent: "The philosopher contextualized his discourse ethics in the tension between Kantian deontology and modernity."
  },
  {
    w: "anstehen",
    de: "Zur baldigen Erledigung oder Entscheidung unausweichlich bevorstehen",
    en: "To be pending, due, or imminent for decision",
    cat: "Gesellschaft & Politik",
    reg: "Bildungssprachlich",
    coll: "wichtige Entscheidungen / Reformen stehen an",
    syn: ["bevorstehen", "drängen", "fällig sein"],
    sent: "Im kommenden Quartal stehen tiefgreifende strukturelle Weichenstellungen für das Unternehmen an.",
    cloze: "Im kommenden Quartal [...] tiefgreifende strukturelle Weichenstellungen für das Unternehmen [...].",
    enSent: "Profound structural milestone decisions are pending for the enterprise in the coming quarter."
  },
  {
    w: "anstreben",
    de: "Ein anspruchsvolles Ziel mit Ausdauer und strategischer Konsequenz verfolgen",
    en: "To aspire to, strive for or pursue a strategic goal",
    cat: "Gesellschaft & Politik",
    reg: "Bildungssprachlich",
    coll: "eine Führungsposition / Klimaneutralität anstreben",
    syn: ["intendieren", "fokussieren", "hinwirken auf"],
    sent: "Bis zum Jahr 2040 strebt die Europäische Union vollständige Treibhausgasneutralität an.",
    cloze: "Bis zum Jahr 2040 [...] die Europäische Union vollständige Treibhausgasneutralität [...].",
    enSent: "By the year 2040, the European Union strives for complete greenhouse gas neutrality."
  },
  {
    w: "antreiben",
    de: "Einen Prozess beschleunigen oder als innere Triebfeder wirken",
    en: "To drive forward, propel, stimulate or fuel",
    cat: "Umwelt & Technologie",
    reg: "Bildungssprachlich",
    coll: "den Fortschritt / den Wandel antreiben",
    syn: ["vorantreiben", "beflügeln", "stimulieren"],
    sent: "Künstliche Intelligenz und Quantencomputing treiben die digitale Transformation unaufhaltsam an.",
    cloze: "Künstliche Intelligenz und Quantencomputing [...] die digitale Transformation unaufhaltsam [...].",
    enSent: "Artificial intelligence and quantum computing propel the digital transformation inexorably."
  },
  {
    w: "antreten",
    de: "Ein offizielles Amt feierlich übernehmen oder eine Reise/Herausforderung beginnen",
    en: "To assume an office, take up a post or commence a competition",
    cat: "Gesellschaft & Politik",
    reg: "Formell",
    coll: "ein Amt / die Nachfolge antreten",
    syn: ["übernehmen", "antreten", "einnehmen"],
    sent: "Der neugewählte Bundeskanzler wird sein Amt voraussichtlich Anfang nächsten Monats antreten.",
    cloze: "Der neugewählte Bundeskanzler wird sein Amt voraussichtlich Anfang nächsten Monats [...].",
    enSent: "The newly elected Federal Chancellor is expected to assume office early next month."
  },
  {
    w: "anvisieren",
    de: "Ein präzises Ziel ins Visier nehmen und fokussieren",
    en: "To target, set sights on or aim precisely at",
    cat: "Wirtschaft & Arbeit",
    reg: "Bildungssprachlich",
    coll: "eine Zielgruppe / einen Marktanteil anvisieren",
    syn: ["fokussieren", "ins Auge fassen", "anstreben"],
    sent: "Mit der neuen Produktlinie visiert das Start-up primär kaufkräftige jüngere Akademiker an.",
    cloze: "Mit der neuen Produktlinie [...] das Start-up primär kaufkräftige jüngere Akademiker [...].",
    enSent: "With the new product line, the start-up targets primarily affluent younger academics."
  },
  {
    w: "appellieren an",
    de: "Eindringlich und öffentlich an Vernunft, Moral oder Hilfsbereitschaft rufen",
    en: "To appeal to, urge on moral or rational grounds",
    cat: "Gesellschaft & Politik",
    reg: "Bildungssprachlich",
    coll: "appellieren an + Akk.",
    syn: ["mahnen", "bitten", "beschwören"],
    sent: "Der Generalsekretär appellierte leidenschaftlich an das Verantwortungsbewusstsein aller Delegierten.",
    cloze: "Der Generalsekretär [...] leidenschaftlich an das Verantwortungsbewusstsein aller Delegierten.",
    enSent: "The Secretary-General appealed passionately to the sense of responsibility of all delegates."
  },
  {
    w: "aufbereiten",
    de: "Rohdaten, Fakten oder Abfallstoffe systematisch für die Weiterverwendung nutzbar machen",
    en: "To process, prepare, recycle or edit data for presentation",
    cat: "Wissenschaft & Forschung",
    reg: "Fachsprachlich",
    coll: "statistische Daten / Abwasser aufbereiten",
    syn: ["bearbeiten", "strukturieren", "rezyklieren"],
    sent: "Das Forschungsinstitut hat die komplexen Klimamodelle didaktisch für Entscheidungsträger aufbereitet.",
    cloze: "Das Forschungsinstitut hat die komplexen Klimamodelle didaktisch für Entscheidungsträger [...].",
    enSent: "The research institute has processed the complex climate models didactically for decision-makers."
  },
  {
    w: "aufbringen",
    de: "Erforderliche finanzielle Mittel beschaffen oder seelische Kraft/Geduld mobilisieren",
    en: "To raise funds, muster courage, summon patience",
    cat: "Psychologie & Kognition",
    reg: "Bildungssprachlich",
    coll: "Mut / Geduld / die finanziellen Mittel aufbringen",
    syn: ["mobilisieren", "beschaffen", "aufwenden"],
    sent: "Die Kommune konnte die geforderten Eigenmittel für das Prestigeobjekt schlichtweg nicht aufbringen.",
    cloze: "Die Kommune konnte die geforderten Eigenmittel für das Prestigeobjekt schlichtweg nicht [...].",
    enSent: "The municipality simply could not raise the required matching funds for the prestige project."
  },
  {
    w: "aufdrängen",
    de: "Anderen Menschen eine Ware, Meinung oder die eigene Gegenwart ungebeten aufzwingen",
    en: "To impose, thrust upon or force an opinion/presence upon others",
    cat: "Psychologie & Kognition",
    reg: "Bildungssprachlich",
    coll: "jdm. eine Sichtweise aufdrängen; sich aufdrängen",
    syn: ["aufzwingen", "aufoktroyieren", "überstülpen"],
    sent: "Der Verdacht drängt sich auf, dass bei der Auftragsvergabe persönliche Verbindungen im Spiel waren.",
    cloze: "Der Verdacht [...] sich auf, dass bei der Auftragsvergabe persönliche Verbindungen im Spiel waren.",
    enSent: "The suspicion imposes itself that personal connections played a role in the contract award."
  },
  {
    w: "auferlegen",
    de: "Als Vorgesetzter oder Staat jemandem verbindlich eine Last oder Pflicht vorschreiben",
    en: "To impose, levy or inflict a duty/penalty/sanction upon someone",
    cat: "Recht & Verwaltung",
    reg: "Gehoben",
    coll: "Sanktionen / Verpflichtungen auferlegen",
    syn: ["verordnen", "aufbürden", "dekretieren"],
    sent: "Die Aufsichtsbehörde legte dem Finanzinstitut drakonische Auflagen zur Risikominimierung auf.",
    cloze: "Die Aufsichtsbehörde [...] dem Finanzinstitut drakonische Auflagen zur Risikominimierung [...].",
    enSent: "The regulatory authority imposed draconian requirements on the financial institution to minimize risk."
  },
  {
    w: "auffassen",
    de: "Eine Aussage oder Geste in einem bestimmten Sinn interpretieren und verstehen",
    en: "To interpret, construe, perceive or understand in a certain way",
    cat: "Psychologie & Kognition",
    reg: "Bildungssprachlich",
    coll: "auffassen als + Akk. / Nom.",
    syn: ["interpretieren", "deuten", "verstehen als"],
    sent: "Die offene Kritik des Nachbarlandes wurde von der Regierung als unzulässige Einmischung aufgefasst.",
    cloze: "Die offene Kritik des Nachbarlandes wurde von der Regierung als unzulässige Einmischung [...].",
    enSent: "The open criticism of the neighboring state was construed by the government as inadmissible interference."
  },
  {
    w: "aufführen",
    de: "Details in einem Register lückenlos auflisten oder ein Bühnenwerk inszenieren",
    en: "To list/enumerate items; to perform/stage a theater piece",
    cat: "Wissenschaft & Forschung",
    reg: "Formell",
    coll: "Belege akribisch aufführen",
    syn: ["auflisten", "verzeichnen", "inszenieren"],
    sent: "Im Anhang des Gutachtens sind sämtliche verwendeten Primärquellen chronologisch aufgeführt.",
    cloze: "Im Anhang des Gutachtens sind sämtliche verwendeten Primärquellen chronologisch [...].",
    enSent: "All primary sources utilized are chronologically listed in the annex of the expert opinion."
  },
  {
    w: "aufgreifen",
    de: "Einen Gedanken, ein Motiv oder eine Anregung aktiv weiterspinnen und vertiefen",
    en: "To take up, seize upon, embrace or follow up on an idea/lead",
    cat: "Kommunikation & Diskurs",
    reg: "Bildungssprachlich",
    coll: "einen Vorschlag / eine Initiative aufgreifen",
    syn: ["fortführen", "weiterverfolgen", "anknüpfen an"],
    sent: "Die Kommission griff die Anregungen der Zivilgesellschaft auf und integrierte sie in den Gesetzesentwurf.",
    cloze: "Die Kommission [...] die Anregungen der Zivilgesellschaft [...] und integrierte sie in den Gesetzesentwurf.",
    enSent: "The commission took up the suggestions of civil society and integrated them into the draft bill."
  },
  {
    w: "aufkommen für",
    de: "Finanzielle Verantwortung übernehmen und Kosten oder Schäden begleichen",
    en: "To cover, pay for or defray costs/damages",
    cat: "Wirtschaft & Arbeit",
    reg: "Formell",
    coll: "aufkommen für + Akk.",
    syn: ["haften für", "bezahlen", "einstehen für"],
    sent: "Der Verursacher des Unfalls muss vollumfänglich für die entstandenen Folgekosten aufkommen.",
    cloze: "Der Verursacher des Unfalls muss vollumfänglich für die entstandenen Folgekosten [...].",
    enSent: "The party responsible for the accident must fully cover all subsequent costs incurred."
  }
];

console.log("Raw curated verbs count in base list:", rawVerbsList.length);
