# -*- coding: utf-8 -*-
# Generates 300 high-yield Goethe C1 German verbs split cleanly into 3 batches of 100
import json

# Comprehensive list of 300 Goethe C1 Verbs
VERBS_300 = [
  # --- BATCH 1: 1 to 100 ---
  # AB- (1-20)
  ("abbedingen", "Recht & Verwaltung", "Fachsprachlich",
   "Vertraglich ausschließen oder wegbedingen", "To contract out of or waive a statutory entitlement",
   "gesetzliche Ansprüche abbedingen", ["ausschließen", "aberkennen"],
   "Im Arbeitsvertrag ließen sich die Mindeststandards keineswegs abbedingen.",
   "Im Arbeitsvertrag ließen sich die Mindeststandards keineswegs [...].",
   "Statutory minimum standards could by no means be contracted out of in the contract."),
  
  ("abdecken", "Wirtschaft & Arbeit", "Formell",
   "Einen Bedarf oder Kosten vollständig erfassen und decken", "To cover or encompass aggregate demand or costs",
   "den Bedarf / die Gesamtkosten abdecken", ["abgelten", "erfassen"],
   "Die Fördermittel decken die explodierenden Energiekosten nur partiell ab.",
   "Die Fördermittel [...] die explodierenden Energiekosten nur partiell [...].",
   "The grant subsidies only partially cover the exploding energy costs."),

  ("abfedern", "Gesellschaft & Politik", "Bildungssprachlich",
   "Negative Auswirkungen oder Krisenfolgen dämpfen und mildern", "To cushion, buffer or absorb negative impacts",
   "soziale Härten / die Inflation abfedern", ["dämpfen", "abmildern", "auffangen"],
   "Die Regierung verabschiedete ein Hilfspaket, um soziale Härten abzufedern.",
   "Die Regierung verabschiedete ein Hilfspaket, um soziale Härten [...].",
   "The government passed a relief package to cushion social hardships."),

  ("abfinden mit", "Psychologie & Kognition", "Bildungssprachlich",
   "Sich widerstrebend mit einer unangenehmen Lage abfinden", "To resign oneself to an unpleasant reality",
   "sich abfinden mit + Dat.", ["sich fügen", "resignieren"],
   "Die Belegschaft wollte sich nicht kampflos mit den Werksschließungen abfinden.",
   "Die Belegschaft wollte sich nicht kampflos mit den Werksschließungen [...].",
   "The workforce did not want to resign itself to the plant closures without a fight."),

  ("abgrenzen von", "Wissenschaft & Forschung", "Fachsprachlich",
   "Unterschiede zu anderen Begriffen trennscharf definieren", "To demarcate or distinguish sharply from",
   "sich abgrenzen von + Dat.", ["differenzieren", "unterscheiden"],
   "In seiner Dissertation grenzte er Resilienz präzise von Robustheit ab.",
   "In seiner Dissertation [...] er Resilienz präzise von Robustheit [...].",
   "In his dissertation, he sharply demarcated resilience from mere robustness."),

  ("abhandenkommen", "Psychologie & Kognition", "Gehoben",
   "Verloren gehen; allmählich und unbemerkt schwinden", "To get lost or gradually slip away (e.g. vision, sense)",
   "jdm. kommt der Realitätssinn abhanden", ["verloren gehen", "entschwinden"],
   "Im permanenten Krisenmodus ist vielen Führungskräften die Vision abhandengekommen.",
   "Im permanenten Krisenmodus ist vielen Führungskräften die Vision [...].",
   "In continuous crisis mode, many executives have lost their strategic vision."),

  ("abkehren von", "Gesellschaft & Politik", "Gehoben",
   "Eine frühere Überzeugung oder Ideologie bewusst aufgeben", "To turn away from, abandon a doctrine or party",
   "sich abkehren von + Dat.", ["ablassen von", "abschwören"],
   "Die Wählerschaft kehrte sich demonstrativ von den Volksparteien ab.",
   "Die Wählerschaft [...] sich demonstrativ von den Volksparteien [...].",
   "The electorate demonstratively turned away from the mainstream parties."),

  ("abkommen von", "Kommunikation & Diskurs", "Gehoben",
   "Von einem Thema oder dem ursprünglichen Plan abweichen", "To stray or deviate from a topic or agreed plan",
   "vom Thema / vom Plan abkommen", ["abweichen", "abschweifen"],
   "Während der Debatte kam der Redner mehrfach vom eigentlichen Thema ab.",
   "Während der Debatte [...] der Redner mehrfach vom eigentlichen Thema [...].",
   "During the debate, the speaker repeatedly strayed from the actual topic."),

  ("abklingen", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Allmählich schwächer werden und schließlich ganz vergehen", "To subside, fade away, die down (symptoms, fever)",
   "Symptome / eine Euphorie klingt ab", ["nachlassen", "verebben"],
   "Erst nachdem die akuten Symptome abgeklungen waren, begann die Reha.",
   "Erst nachdem die akuten Symptome [...] waren, begann die Reha.",
   "Only after the acute symptoms had subsided did rehabilitation begin."),

  ("ableiten aus", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Logisch schlussfolgern oder den Ursprung herleiten", "To deduce or derive logically from empirical facts",
   "ableiten aus + Dat.", ["deduzieren", "herleiten"],
   "Aus den Erhebungen lässt sich ein klarer Kausalzusammenhang ableiten.",
   "Aus den Erhebungen lässt sich ein klarer Kausalzusammenhang [...].",
   "A clear causal relationship can be deduced from the survey findings."),

  ("abmildern", "Gesellschaft & Politik", "Formell",
   "Die Schärfe oder Härte einer Krise verringern", "To alleviate, mitigate or moderate severity",
   "die Folgen / das Urteil abmildern", ["lindern", "abschwächen"],
   "Mit gezielten Hilfen versuchte man, die Härten für Kleinbauern abzumildern.",
   "Mit gezielten Hilfen versuchte man, die Härten für Kleinbauern [...].",
   "Targeted assistance was used to try to mitigate hardships for smallholders."),

  ("abraten von", "Psychologie & Kognition", "Formell",
   "Dringend empfehlen, eine bestimmte Handlung zu unterlassen", "To advise against or dissuade from an action",
   "abraten von + Dat.", ["warnen vor", "widerraten"],
   "Sämtliche Analysten rieten eindringlich von spekulativen Derivaten ab.",
   "Sämtliche Analysten [...] eindringlich von spekulativen Derivaten [...].",
   "All analysts urgently advised against speculative derivatives."),

  ("absehen von", "Gesellschaft & Politik", "Gehoben",
   "Etwas bewusst ignorieren oder auf eine Strafe verzichten", "To refrain from; to disregard or dispense with",
   "absehen von + Dat.", ["verzichten auf", "unterlassen"],
   "Das Gericht sah im Hinblick auf das Geständnis von einer Haftstrafe ab.",
   "Das Gericht [...] im Hinblick auf das Geständnis von einer Haftstrafe [...].",
   "In light of the confession, the court refrained from a prison sentence."),

  ("absprechen", "Gesellschaft & Politik", "Bildungssprachlich",
   "Jemandem eine Eigenschaft oder Kompetenz verwehren", "To deny or contest someone's competence or legitimacy",
   "jdm. die Kompetenz / Legitimität absprechen", ["aberkennen", "bestreiten"],
   "Kritiker sprachen dem neu ernannten Gremium jegliche Legitimität ab.",
   "Kritiker [...] dem neu ernannten Gremium jegliche Legitimität [...].",
   "Critics denied the newly appointed committee any legitimacy."),

  ("abstreiten", "Recht & Verwaltung", "Formell",
   "Die Richtigkeit einer Beschuldigung kategorisch leugnen", "To dispute, contest or vehemently deny an allegation",
   "eine Anschuldigung vehement abstreiten", ["leugnen", "dementieren"],
   "Der Zeuge stritt vor Gericht jede Kenntnis von Bestechungsgeldern ab.",
   "Der Zeuge [...] vor Gericht jede Kenntnis von Bestechungsgeldern [...].",
   "In court, the witness denied any knowledge of bribery funds."),

  ("abwägen", "Psychologie & Kognition", "Bildungssprachlich",
   "Vor- und Nachteile sowie Risiken gründlich vergleichen", "To weigh up, ponder or carefully balance options",
   "Chancen und Risiken sorgfältig abwägen", ["evaluieren", "prüfen"],
   "Vor einem solchen Entschluss muss der Vorstand alle Risiken abwägen.",
   "Vor einem solchen Entschluss muss der Vorstand alle Risiken [...].",
   "Before such a decision, the executive board must weigh up all risks."),

  ("abwälzen auf", "Wirtschaft & Arbeit", "Bildungssprachlich",
   "Eine Last oder finanzielle Bürde auf andere übertragen", "To shift or offload costs/blame onto others",
   "Kosten / Verantwortung auf Dritte abwälzen", ["übertragen", "delegieren"],
   "Großkonzerne neigen dazu, Kosten direkt auf Verbraucher abzuwälzen.",
   "Großkonzerne neigen dazu, Kosten direkt auf Verbraucher [...].",
   "Large corporations tend to offload costs directly onto consumers."),

  ("abwenden", "Gesellschaft & Politik", "Gehoben",
   "Ein drohendes Unheil oder eine Krise im Vorfeld verhindern", "To avert, ward off or stave off impending disaster",
   "eine Katastrophe / Schaden abwenden", ["verhindern", "bannen"],
   "Durch Intervention der Notenbank konnte die Bankenkrise abgewendet werden.",
   "Durch Intervention der Notenbank konnte die Bankenkrise [...] werden.",
   "Through central bank intervention, the banking crisis could be averted."),

  ("abwickeln", "Wirtschaft & Arbeit", "Fachsprachlich",
   "Ein Geschäft ordnungsgemäß durchführen oder auflösen", "To process, transact or liquidate an enterprise",
   "ein Geschäft / eine Insolvenz abwickeln", ["durchführen", "liquidieren"],
   "Internationale Transaktionen werden heute digital abgewickelt.",
   "Internationale Transaktionen werden heute digital [...].",
   "International transactions are nowadays processed digitally."),

  ("abzielen auf", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Eine bestimmte Wirkung als konkretes Ziel anstreben", "To aim at, be targeted towards or designed to achieve",
   "abzielen auf + Akk.", ["intendieren", "anvisieren"],
   "Die Reformmaßnahmen zielen darauf ab, Bürokratie abzubauen.",
   "Die Reformmaßnahmen [...] darauf ab, Bürokratie abzubauen.",
   "The reform measures aim to reduce bureaucracy."),

  # AN- (21-40)
  ("anbelangen", "Kommunikation & Diskurs", "Gehoben",
   "In Bezug auf etwas oder jemanden gelten", "To concern or pertain to (as far as ... is concerned)",
   "was [Akk.] anbelangt", ["betreffen", "angehen"],
   "Was die finanzielle Machbarkeit anbelangt, so bestehen Zweifel.",
   "Was die finanzielle Machbarkeit [...], so bestehen Zweifel.",
   "As far as financial feasibility is concerned, doubts remain."),

  ("anberaumen", "Recht & Verwaltung", "Formell",
   "Einen offiziellen Termin für eine Sitzung festsetzen", "To schedule or convene a formal meeting",
   "eine Sitzung / einen Termin anberaumen", ["ansetzen", "terminieren"],
   "Das Bundesgericht beraumte die Verhandlung für November an.",
   "Das Bundesgericht [...] die Verhandlung für November [...].",
   "The federal court scheduled the hearing for November."),

  ("anfechten", "Recht & Verwaltung", "Fachsprachlich",
   "Die rechtliche Gültigkeit einer Entscheidung juristisch bestreiten", "To challenge or contest legally (verdict, election)",
   "ein Urteil / eine Wahl anfechten", ["beeinspruchen", "bestreiten"],
   "Die Opposition kündigte an, das Wahlergebnis gerichtlich anzufechten.",
   "Die Opposition kündigte an, das Wahlergebnis gerichtlich [...].",
   "The opposition announced it would legally challenge the election result."),

  ("anfordern", "Recht & Verwaltung", "Formell",
   "Offiziell die Zusendung von Dokumenten verlangen", "To request formally or requisition files",
   "Unterlagen / Akten anfordern", ["verlangen", "beantragen"],
   "Die Staatsanwaltschaft forderte die vollständigen Akten an.",
   "Die Staatsanwaltschaft [...] die vollständigen Akten [...].",
   "The public prosecutor's office requested the complete files."),

  ("anführen", "Kommunikation & Diskurs", "Bildungssprachlich",
   "Argumente, Quellen oder Zitate als Beleg nennen", "To cite, quote or adduce evidence",
   "Belege / Zeugen anführen", ["zitieren", "vorbringen"],
   "Zur Untermauerung seiner These führte der Forscher Beispiele an.",
   "Zur Untermauerung seiner These [...] der Forscher Beispiele [...].",
   "To substantiate his thesis, the researcher cited examples."),

  ("angleichen an", "Gesellschaft & Politik", "Formell",
   "Unterschiede stufenweise abbauen, bis Übereinstimmung herrscht", "To align with or assimilate to a standard",
   "angleichen an + Akk.", ["harmonisieren", "anpassen"],
   "Ziel ist es, die nationalen Standards aneinander anzugleichen.",
   "Ziel ist es, die nationalen Standards aneinander [...].",
   "The goal is to align national standards with one another."),

  ("anknüpfen an", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Thematisch an frühere Erkenntnisse anschließen", "To build upon or connect with previous research",
   "anknüpfen an + Akk.", ["fortführen", "anschließen an"],
   "Die neue Studie knüpft an die Resultate des Vorjahres an.",
   "Die neue Studie [...] an die Resultate des Vorjahres [...].",
   "The new study connects with the results of the previous year."),

  ("anlasten", "Recht & Verwaltung", "Gehoben",
   "Jemandem die moralische oder juristische Schuld zuschreiben", "To blame someone for, hold responsible or impute fault",
   "jdm. ein Versäumnis anlasten", ["vorwerfen", "zuschreiben"],
   "Man kann der neuen Leitung die alten Versäumnisse nicht anlasten.",
   "Man kann der neuen Leitung die alten Versäumnisse nicht [...].",
   "One cannot blame the new management for old shortcomings."),

  ("anmahnen", "Gesellschaft & Politik", "Gehoben",
   "Auf fällige Pflichten oder überfällige Reformen pochen", "To urge or press for overdue compliance or reform",
   "Reformen / Einhaltung anmahnen", ["einfordern", "ermahnen"],
   "Organisationen mahnten den Schutz verfolgter Minderheiten an.",
   "Organisationen [...] den Schutz verfolgter Minderheiten [...].",
   "Organizations urged the protection of persecuted minorities."),

  ("anmuten", "Psychologie & Kognition", "Gehoben",
   "Auf den Betrachter in bestimmter Weise wirken", "To appear or strike someone as peculiar/curious",
   "seltsam / archaisch anmuten", ["wirken wie", "erscheinen"],
   "Aus heutiger Sicht mutet diese rigide Klausel seltsam an.",
   "Aus heutiger Sicht [...] diese rigide Klausel seltsam [...].",
   "From today's perspective, this rigid clause seems strange."),

  ("anordnen", "Recht & Verwaltung", "Formell",
   "Kraft institutioneller Autorität verbindlich befehlen", "To decree, mandate or order officially",
   "eine Prüfung anordnen", ["verfügen", "dekretieren"],
   "Die Behörde ordnete eine eingehende Prüfung aller Zertifikate an.",
   "Die Behörde [...] eine eingehende Prüfung aller Zertifikate [...].",
   "The authority ordered a thorough audit of all certificates."),

  ("anprangern", "Gesellschaft & Politik", "Bildungssprachlich",
   "Öffentlich Missstände oder Unrecht scharf kritisieren", "To denounce, excoriate or publicly pillory",
   "soziale Missstände anprangern", ["brandmarken", "rügen"],
   "Der Bericht prangerte unhaltbare Zustände in Kliniken an.",
   "Der Bericht [...] unhaltbare Zustände in Kliniken [...].",
   "The report denounced unacceptable conditions in hospitals."),

  ("anregen", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Einen geistigen Impuls für Überlegungen geben", "To stimulate, inspire or prompt reflection",
   "zum Nachdenken anregen", ["stimulieren", "initiieren"],
   "Die Thesen regten eine fruchtbare Diskussion über Ethik an.",
   "Die Thesen [...] eine fruchtbare Diskussion über Ethik [...].",
   "The theses stimulated a fruitful discussion on ethics."),

  ("anrechnen auf", "Recht & Verwaltung", "Fachsprachlich",
   "Bereits erbrachte Leistungen anerkennend berücksichtigen", "To credit towards or offset against credits",
   "anrechnen auf + Akk.", ["verrechnen", "gutschreiben"],
   "Leistungen im Auslandssemester lassen sich auf das Studium anrechnen.",
   "Leistungen im Auslandssemester lassen sich auf das Studium [...].",
   "Credits earned during a semester abroad can be counted towards the degree."),

  ("anreizen", "Wirtschaft & Arbeit", "Fachsprachlich",
   "Durch Belohnungen oder Boni zu Leistung motivieren", "To incentivize or spur action through rewards",
   "Investitionen anreizen", ["incentivieren", "anspornen"],
   "Prämien sollen Firmen dazu anreizen, CO2-neutral zu produzieren.",
   "Prämien sollen Firmen dazu [...], CO2-neutral zu produzieren.",
   "Premiums are intended to incentivize firms to produce CO2-neutrally."),

  ("ansetzen", "Wirtschaft & Arbeit", "Bildungssprachlich",
   "Einen Vorgang beginnen oder kalkulatorisch veranschlagen", "To schedule, apply measures or estimate cost",
   "den Rotstift ansetzen", ["terminieren", "veranschlagen"],
   "Die Sanierer müssen bei den hohen Verwaltungsausgaben ansetzen.",
   "Die Sanierer müssen bei den hohen Verwaltungsausgaben [...].",
   "The restructuring team must target high administrative expenditures."),

  ("ansiedeln", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Einen Begriff theoretisch verorten oder Werk etablieren", "To locate, situate or contextualize a concept",
   "einen Begriff ansiedeln bei/in", ["platzieren", "verorten"],
   "Er siedelt seinen Ansatz in der kritischen Gesellschaftstheorie an.",
   "Er [...] seinen Ansatz in der kritischen Gesellschaftstheorie [...].",
   "He situates his approach within critical social theory."),

  ("anstehen", "Gesellschaft & Politik", "Bildungssprachlich",
   "Zur baldigen Erledigung unausweichlich bevorstehen", "To be pending, due or imminent for decision",
   "wichtige Entscheidungen stehen an", ["bevorstehen", "drängen"],
   "Im kommenden Quartal stehen richtungsweisende Beschlüsse an.",
   "Im kommenden Quartal [...] richtungsweisende Beschlüsse [...].",
   "Groundbreaking decisions are pending in the coming quarter."),

  ("anstreben", "Gesellschaft & Politik", "Bildungssprachlich",
   "Ein anspruchsvolles Ziel planvoll verfolgen", "To strive for, pursue or aspire to an ambitious goal",
   "Klimaneutralität anstreben", ["intendieren", "hinwirken auf"],
   "Die Europäische Union strebt bis 2045 Klimaneutralität an.",
   "Die Europäische Union [...] bis 2045 Klimaneutralität [...].",
   "The European Union strives for climate neutrality by 2045."),

  ("antreiben", "Umwelt & Technologie", "Bildungssprachlich",
   "Einen Prozess beschleunigen oder als Impuls dienen", "To propel, fuel or drive forward development",
   "den Wandel antreiben", ["vorantreiben", "stimulieren"],
   "Technologische Neuerungen treiben den gesellschaftlichen Wandel an.",
   "Technologische Neuerungen [...] den gesellschaftlichen Wandel [...].",
   "Technological innovations propel societal change."),

  # AUF- (41-60)
  ("antreten", "Gesellschaft & Politik", "Formell",
   "Ein offizielles Amt oder eine Position feierlich übernehmen", "To assume an office, take up a formal post",
   "ein Amt / die Nachfolge antreten", ["übernehmen", "einnehmen"],
   "Die neu gewählte Präsidentin wird ihr Amt im Januar antreten.",
   "Die neu gewählte Präsidentin wird ihr Amt im Januar [...].",
   "The newly elected president will take up office in January."),

  ("anvisieren", "Wirtschaft & Arbeit", "Bildungssprachlich",
   "Ein präzises Ziel fokussieren und anstreben", "To target, set sights on or aim precisely at",
   "eine Zielgruppe / Quote anvisieren", ["fokussieren", "ins Auge fassen"],
   "Mit dem neuen Modell visiert der Konzern junge Käuferschichten an.",
   "Mit dem neuen Modell [...] der Konzern junge Käuferschichten [...].",
   "With the new model, the corporation is targeting younger buyers."),

  ("appellieren an", "Gesellschaft & Politik", "Bildungssprachlich",
   "Eindringlich an Vernunft, Moral oder Hilfsbereitschaft erinnern", "To appeal to, urge on moral or rational grounds",
   "appellieren an + Akk.", ["mahnen", "beschwören"],
   "Der Kanzler appellierte an das Verantwortungsbewusstsein der Bürger.",
   "Der Kanzler [...] an das Verantwortungsbewusstsein der Bürger.",
   "The Chancellor appealed to the citizens' sense of responsibility."),

  ("aufbereiten", "Wissenschaft & Forschung", "Fachsprachlich",
   "Daten, Fakten oder Rohstoffe methodisch nutzbar machen", "To process, prepare, recycle or edit data for use",
   "statistische Daten / Wasser aufbereiten", ["bearbeiten", "strukturieren"],
   "Das Institut hat die Klimadaten grafisch anschaulich aufbereitet.",
   "Das Institut hat die Klimadaten grafisch anschaulich [...].",
   "The institute has processed the climate data in a visually clear format."),

  ("aufbringen", "Psychologie & Kognition", "Bildungssprachlich",
   "Finanzielle Mittel beschaffen oder Geduld/Mut mobilisieren", "To raise funds, muster courage, summon patience",
   "Mut / Geduld / Mittel aufbringen", ["mobilisieren", "beschaffen"],
   "Für dieses ambitionierte Vorhaben fehlte es an den nötigen Mitteln.",
   "Für dieses ambitionierte Vorhaben konnte man die Mittel nicht [...].",
   "For this ambitious undertaking, they could not raise the required funds."),

  ("aufdrängen", "Psychologie & Kognition", "Bildungssprachlich",
   "Anderen eine Ansicht oder Gegenwart ungebeten aufzwingen", "To impose, thrust upon or force an opinion upon others",
   "jdm. eine Sichtweise aufdrängen", ["aufzwingen", "aufoktroyieren"],
   "Der Verdacht drängt sich auf, dass politische Motive vorlagen.",
   "Der Verdacht [...] sich auf, dass politische Motive vorlagen.",
   "The suspicion imposes itself that political motives were involved."),

  ("auferlegen", "Recht & Verwaltung", "Gehoben",
   "Jemandem verbindlich eine Last oder Pflicht vorschreiben", "To impose, levy or inflict a duty/fine upon someone",
   "Sanktionen / Pflichten auferlegen", ["verordnen", "aufbürden"],
   "Das Gericht legte dem Konzern empfindliche Strafzahlungen auf.",
   "Das Gericht [...] dem Konzern empfindliche Strafzahlungen [...].",
   "The court imposed severe financial penalties on the corporation."),

  ("auffassen", "Psychologie & Kognition", "Bildungssprachlich",
   "Eine Aussage in einem bestimmten Sinn interpretieren", "To interpret, construe, perceive or understand in a certain way",
   "auffassen als + Akk. / Nom.", ["interpretieren", "deuten"],
   "Seine Zurückhaltung wurde fälschlicherweise als Desinteresse aufgefasst.",
   "Seine Zurückhaltung wurde fälschlicherweise als Desinteresse [...].",
   "His reluctance was mistakenly interpreted as a lack of interest."),

  ("aufführen", "Wissenschaft & Forschung", "Formell",
   "Details in einer Liste lückenlos anführen", "To list, register or enumerate items systematically",
   "Belege / Quellen aufführen", ["auflisten", "verzeichnen"],
   "Im Anhang der Studie sind sämtliche Quellen ausführlich aufgeführt.",
   "Im Anhang der Studie sind sämtliche Quellen ausführlich [...].",
   "In the appendix to the study, all sources are listed in detail."),

  ("aufgreifen", "Kommunikation & Diskurs", "Bildungssprachlich",
   "Einen Gedanken oder Vorschlag aufnehmen und vertiefen", "To take up, seize upon, follow up on an idea/lead",
   "einen Vorschlag / Impuls aufgreifen", ["fortführen", "anknüpfen an"],
   "Die Ministerin griff die Initiative der Bürgerbewegung erfreut auf.",
   "Die Ministerin [...] die Initiative der Bürgerbewegung erfreut [...].",
   "The minister gladly took up the initiative of the citizens' movement."),

  ("aufkommen für", "Wirtschaft & Arbeit", "Formell",
   "Finanzielle Haftung übernehmen und Kosten begleichen", "To cover, pay for or defray expenses/damages",
   "aufkommen für + Akk.", ["haften für", "bezahlen"],
   "Die Versicherung weigerte sich, für den Schaden voll aufzukommen.",
   "Die Versicherung weigerte sich, für den Schaden voll [...].",
   "The insurance company refused to cover the damages in full."),

  ("auflehnen gegen", "Gesellschaft & Politik", "Gehoben",
   "Sich rebellisch einer Autorität oder Doktrin widersetzen", "To rebel, revolt or rise up against authority",
   "sich auflehnen gegen + Akk.", ["rebellieren", "widersetzen"],
   "Die Studierenden lehnten sich offen gegen das Verbot auf.",
   "Die Studierenden [...] sich offen gegen das Verbot [...].",
   "The students openly rebelled against the prohibition."),

  ("auflösen", "Gesellschaft & Politik", "Formell",
   "Eine Organisation beenden oder Verträge annullieren", "To dissolve an assembly or terminate a contract",
   "das Parlament / einen Vertrag auflösen", ["annullieren", "beenden"],
   "Nach dem Bruch der Koalition wurde das Parlament aufgelöst.",
   "Nach dem Bruch der Koalition wurde das Parlament [...].",
   "Following the collapse of the coalition, parliament was dissolved."),

  ("aufrechterhalten", "Gesellschaft & Politik", "Bildungssprachlich",
   "Einen Zustand, eine Ordnung oder Behauptung fortführen", "To maintain, uphold or sustain an order or claim",
   "die Ordnung / den Kontakt aufrechterhalten", ["wahren", "konservieren"],
   "Trotz aller Widerstände hielt die Kommission ihre Forderung aufrecht.",
   "Trotz aller Widerstände [...] die Kommission ihre Forderung [...].",
   "Despite all resistance, the commission upheld its demand."),

  ("aufschlüsseln", "Wissenschaft & Forschung", "Fachsprachlich",
   "Gesamteinheiten in ihre Bestandteile detailliert zerlegen", "To break down, disaggregate or categorize data",
   "Kosten / Daten nach Kriterien aufschlüsseln", ["gliedern", "differenzieren"],
   "Die Ausgaben wurden nach Ressorts und Quartalen aufgeschlüsselt.",
   "Die Ausgaben wurden nach Ressorts und Quartalen [...].",
   "Expenditures were broken down by department and quarter."),

  ("aufschieben", "Psychologie & Kognition", "Bildungssprachlich",
   "Eine fällige Aufgabe oder Entscheidung zeitlich verzögern", "To postpone, defer or procrastinate on an issue",
   "eine Entscheidung / Prüfung aufschieben", ["vertagen", "hinauszögern"],
   "Aus Angst vor Konflikten schob die Leitung die Kündigung auf.",
   "Aus Angst vor Konflikten [...] die Leitung die Kündigung [...].",
   "Fearing conflict, management postponed the dismissal."),

  ("aufstocken", "Wirtschaft & Arbeit", "Formell",
   "Vorhandene Mittel, Bestände oder Personal erhöhen", "To augment, supplement or top up resources/staff",
   "das Budget / Personal aufstocken", ["erhöhen", "vermehren"],
   "Um der Nachfrage Herr zu werden, stockte man das Pflegepersonal auf.",
   "Um der Nachfrage Herr zu werden, [...] man das Pflegepersonal [...].",
   "To cope with demand, the nursing staff was increased."),

  ("aufweisen", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Bestimmte Merkmale, Defizite oder Vorzüge besitzen", "To exhibit, show, feature or display characteristics",
   "Mängel / Parallelen aufweisen", ["zeigen", "besitzen"],
   "Das Gutachten weist signifikante methodische Mängel auf.",
   "Das Gutachten [...] signifikante methodische Mängel [...].",
   "The expert assessment displays significant methodological flaws."),

  ("aufwerfen", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Eine bedeutsame Frage oder Problematik zur Debatte stellen", "To raise or pose a profound question or problem",
   "eine Frage / Zweifel aufwerfen", ["aufbringen", "thematisieren"],
   "Der rasante Aufstieg von KI wirft grundlegende ethische Fragen auf.",
   "Der rasante Aufstieg von KI [...] grundlegende ethische Fragen [...].",
   "The rapid rise of AI raises fundamental ethical questions."),

  ("aufwenden", "Wirtschaft & Arbeit", "Bildungssprachlich",
   "Finanzielle Mittel oder Energie zweckgebunden investieren", "To expend, spend or devote time/resources",
   "Zeit / erhebliche Mittel aufwenden für", ["investieren", "einsetzen"],
   "Der Staat wendete Milliarden für den Ausbau der Schienenwege auf.",
   "Der Staat [...] Milliarden für den Ausbau der Schienenwege [...].",
   "The state expended billions on the expansion of railways."),

  # AUS- (61-80)
  ("aufzwingen", "Gesellschaft & Politik", "Bildungssprachlich",
   "Anderen gewaltsam oder autoritär den eigenen Willen diktieren", "To impose or force one's will upon others",
   "jdm. seinen Willen / Bedingungen aufzwingen", ["aufoktroyieren", "diktieren"],
   "Großmächte sollten kleineren Staaten ihre Doktrin nicht aufzwingen.",
   "Großmächte sollten kleineren Staaten ihre Doktrin nicht [...].",
   "Superpowers should not force their doctrine upon smaller states."),

  ("ausarten in", "Gesellschaft & Politik", "Bildungssprachlich",
   "Aus der Kontrolle geraten und in Exzesse münden", "To degenerate into, get out of hand, escalate into",
   "ausarten in + Akk.", ["eskalieren", "entgleisen"],
   "Die friedliche Demonstration drohte in gewaltsame Krawalle auszuarten.",
   "Die friedliche Demonstration drohte in gewaltsame Krawalle [...].",
   "The peaceful demonstration threatened to degenerate into violent riots."),

  ("ausbauen", "Wirtschaft & Arbeit", "Bildungssprachlich",
   "Bestehende Kapazitäten, Netze oder Kompetenzen erweitern", "To expand, develop or upgrade infrastructure/skills",
   "die Infrastruktur / Kapazitäten ausbauen", ["erweitern", "vergrößern"],
   "Die Regierung will das Netz für Hochgeschwindigkeitszüge zügig ausbauen.",
   "Die Regierung will das Netz für Hochgeschwindigkeitszüge zügig [...].",
   "The government aims to rapidly expand the high-speed rail network."),

  ("ausblenden", "Psychologie & Kognition", "Bildungssprachlich",
   "Bestimmte störende Fakten oder Gefahren bewusst ignorieren", "To block out, tune out or deliberately ignore facts",
   "die Realität / Risiken ausblenden", ["ignorieren", "verdrängen"],
   "In seiner Euphorie blendete der Anleger alle Warnsignale aus.",
   "In seiner Euphorie [...] der Anleger alle Warnsignale [...].",
   "In his euphoria, the investor blocked out all warning signs."),

  ("auseinandersetzen mit", "Kommunikation & Diskurs", "Bildungssprachlich",
   "Sich gründlich mit einem Thema oder Gegner befassen", "To grapple with, analyze critically or confront an issue",
   "sich auseinandersetzen mit + Dat.", ["diskutieren", "reflektieren über"],
   "Wissenschaftler müssen sich kritisch mit Fehlschlägen auseinandersetzen.",
   "Wissenschaftler müssen sich kritisch mit Fehlschlägen [...].",
   "Scientists must grapple critically with experimental failures."),

  ("ausfechten", "Gesellschaft & Politik", "Bildungssprachlich",
   "Einen Streit oder Konflikt bis zur Entscheidung austragen", "To fight out, contest or resolve a conflict definitively",
   "einen Streit / Konflikt ausfechten", ["austragen", "durchfechten"],
   "Der ideologische Disput wurde vor laufenden Fernsehkameras ausgefochten.",
   "Der ideologische Disput wurde vor laufenden Fernsehkameras [...].",
   "The ideological dispute was fought out in front of live TV cameras."),

  ("ausführen", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Einen Gedanken detailliert darlegen oder einen Plan umsetzen", "To elaborate upon an idea or execute a plan",
   "einen Gedanken näher ausführen", ["erläutern", "präzisieren"],
   "Wie der Redner in seinem Vortrag treffend ausführte, droht Stagnation.",
   "Wie der Redner in seinem Vortrag treffend [...], droht Stagnation.",
   "As the speaker aptly elaborated in his talk, stagnation looms."),

  ("ausgrenzen", "Gesellschaft & Politik", "Bildungssprachlich",
   "Individuen oder Gruppen gezielt von Teilhabe ausschließen", "To marginalize, ostracize or exclude socially",
   "Minderheiten / Andersdenkende ausgrenzen", ["marginalisieren", "ausschließen"],
   "Eine demokratische Gesellschaft darf Randgruppen nicht ausgrenzen.",
   "Eine demokratische Gesellschaft darf Randgruppen nicht [...].",
   "A democratic society must not marginalize peripheral groups."),

  ("aushandeln", "Gesellschaft & Politik", "Formell",
   "Durch Verhandlungen einen Kompromiss oder Vertrag erzielen", "To negotiate, hammer out or broker an agreement",
   "einen Kompromiss / Vertrag aushandeln", ["vereinbaren", "paktieren"],
   "Die Tarifparteien handelten in zähen Runden einen Kompromiss aus.",
   "Die Tarifparteien [...] in zähen Runden einen Kompromiss [...].",
   "The collective bargaining parties negotiated a compromise in tough rounds."),

  ("ausharren", "Psychologie & Kognition", "Gehoben",
   "Trotz Gefahr oder Kälte standhaft am Platz bleiben", "To endure, persevere, hold out or persist stoically",
   "in der Kälte / auf verlorenem Posten ausharren", ["durchhalten", "verharren"],
   "Trotz des Unwetters harrten die Hilfskräfte unermüdlich vor Ort aus.",
   "Trotz des Unwetters [...] die Hilfskräfte unermüdlich vor Ort [...].",
   "Despite the storm, relief workers persevered tirelessly on site."),

  ("aushöhlen", "Gesellschaft & Politik", "Bildungssprachlich",
   "Institutionen oder Rechte allmählich untergraben und schwächen", "To undermine, erode or hollow out democratic norms",
   "die Demokratie / Bürgerrechte aushöhlen", ["untergraben", "schwächen"],
   "Populistische Tendenzen drohen die Gewaltenteilung schleichend auszuhöhlen.",
   "Populistische Tendenzen drohen die Gewaltenteilung schleichend [...].",
   "Populist trends threaten to gradually hollow out the separation of powers."),

  ("auskommen mit", "Psychologie & Kognition", "Bildungssprachlich",
   "Mit vorhandenen Mitteln haushalten oder mit Personen harmonieren", "To manage with limited resources or get along with someone",
   "mit wenig Geld / gut miteinander auskommen", ["haushalten", "zurechtkommen"],
   "Viele Studierende müssen monatlich mit einem knappen Budget auskommen.",
   "Viele Studierende müssen monatlich mit einem knappen Budget [...].",
   "Many university students must manage with a tight monthly budget."),

  ("auslösen", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Als ursächlicher Impuls eine Kettenreaktion hervorrufen", "To trigger, spark or provoke a chain reaction",
   "eine Welle / Proteste auslösen", ["hervorrufen", "initiieren"],
   "Die Veröffentlichung des Berichts löste heftige Proteste aus.",
   "Die Veröffentlichung des Berichts [...] heftige Proteste [...].",
   "The publication of the report triggered fierce protests."),

  ("ausprägen", "Psychologie & Kognition", "Fachsprachlich",
   "Spezifische Eigenschaften oder Strukturen formen", "To develop, manifest or shape distinct traits",
   "Fähigkeiten / Symptome prägen sich aus", ["herausbilden", "formen"],
   "Bestimmte Charakterzüge prägen sich erst im Erwachsenenalter voll aus.",
   "Bestimmte Charakterzüge [...] sich erst im Erwachsenenalter voll [...].",
   "Certain character traits only manifest themselves fully in adulthood."),

  ("ausrichten an", "Wirtschaft & Arbeit", "Bildungssprachlich",
   "Strategien verbindlich an Leitlinien oder Kriterien orientieren", "To orient or align strategies with specific benchmarks",
   "ausrichten an + Dat.", ["orientieren an", "abstimmen auf"],
   "Unternehmen sollten ihre Strategie am Pariser Klimaabkommen ausrichten.",
   "Unternehmen sollten ihre Strategie am Pariser Klimaabkommen [...].",
   "Enterprises should align their strategy with the Paris Climate Agreement."),

  ("ausrüsten mit", "Umwelt & Technologie", "Formell",
   "Mit notwendigem Werkzeug oder Technologie ausstatten", "To equip, furnish or outfit with required gear/tools",
   "ausrüsten mit + Dat.", ["ausstatten", "versehen mit"],
   "Die Labore wurden mit modernsten Elektronenmikroskopen ausgerüstet.",
   "Die Labore wurden mit modernsten Elektronenmikroskopen [...].",
   "The laboratories were equipped with cutting-edge electron microscopes."),

  ("ausschlagen", "Psychologie & Kognition", "Bildungssprachlich",
   "Ein lukratives Angebot oder eine Beförderung dankend ablehnen", "To decline, turn down or reject an offer/gift",
   "ein Angebot / eine Einladung ausschlagen", ["ablehnen", "zurückweisen"],
   "Aus ethischen Gründen schlug sie das hochdotierte Jobangebot aus.",
   "Aus ethischen Gründen [...] sie das hochdotierte Jobangebot [...].",
   "Out of ethical reasons, she turned down the lucrative job offer."),

  ("ausschließen", "Recht & Verwaltung", "Formell",
   "Eine Möglichkeit logisch verwerfen oder jemanden verbannen", "To rule out, preclude or eliminate a possibility",
   "eine Möglichkeit / Manipulation ausschließen", ["verwerfen", "eliminieren"],
   "Die Wahlkommission konnte eine absichtliche Manipulation ausschließen.",
   "Die Wahlkommission konnte eine absichtliche Manipulation [...].",
   "The election commission was able to rule out deliberate tampering."),

  ("ausschöpfen", "Wirtschaft & Arbeit", "Bildungssprachlich",
   "Vorhandene Ressourcen, Potenziale oder Fristen voll nutzen", "To exhaust, maximize or fully utilize potentials/quotas",
   "Potenziale / den rechtlichen Rahmen ausschöpfen", ["maximieren", "voll nutzen"],
   "Wir müssen sämtliche diplomatischen Spielräume voll ausschöpfen.",
   "Wir müssen sämtliche diplomatischen Spielräume voll [...].",
   "We must fully utilize all diplomatic leeway."),

  ("ausstrahlen", "Kommunikation & Diskurs", "Bildungssprachlich",
   "Ein Programm senden oder eine spürbare Aura verbreiten", "To radiate authority or broadcast a television program",
   "Autorität / Ruhe ausstrahlen", ["verbreiten", "emittieren"],
   "In Krisenzeiten muss eine Führungspersönlichkeit Souveränität ausstrahlen.",
   "In Krisenzeiten muss eine Führungspersönlichkeit Souveränität [...].",
   "In times of crisis, a leader must radiate composure and sovereignty."),

  # BE- (81-100)
  ("ausüben", "Gesellschaft & Politik", "Formell",
   "Einen Beruf praktizieren oder Macht/Einfluss geltend machen", "To exercise power, exert pressure or practice a trade",
   "Macht / Druck / ein Amt ausüben", ["praktizieren", "anwenden"],
   "Lobbyisten versuchten, massiven Druck auf Abgeordnete auszuüben.",
   "Lobbyisten versuchten, massiven Druck auf Abgeordnete [...].",
   "Lobbyists attempted to exert massive pressure on parliamentarians."),

  ("ausweichen", "Gesellschaft & Politik", "Bildungssprachlich",
   "Einer Konfrontation oder heiklen Frage geschickt entgehen", "To evade, dodge or sidestep a difficult question/issue",
   "jdm. / einer Frage geschickt ausweichen (+ Dat.)", ["umgehen", "entgehen"],
   "Der Minister wich den Fragen der Pressekonferenz geschickt aus.",
   "Der Minister [...] den Fragen der Pressekonferenz geschickt [...].",
   "The minister skillfully sidestepped questions at the press conference."),

  ("ausweiten", "Wirtschaft & Arbeit", "Formell",
   "Geltungsbereich, Handelszonen oder Befugnisse vergrößern", "To expand, widen or broaden jurisdiction/trade",
   "den Handel / Befugnisse ausweiten", ["expandieren", "verbreitern"],
   "Der Konzern plant, seine Geschäftstätigkeit auf Asien auszuweiten.",
   "Der Konzern plant, seine Geschäftstätigkeit auf Asien [...].",
   "The corporation plans to expand its operations to Asia."),

  ("auswirken auf", "Gesellschaft & Politik", "Bildungssprachlich",
   "Spürbare Folgen oder Wirkungen auf einen Bereich haben", "To impact on, affect or have repercussions upon",
   "sich auswirken auf + Akk.", ["beeinflussen", "prägen"],
   "Die Steuererhöhung wird sich direkt auf die Inflation auswirken.",
   "Die Steuererhöhung wird sich direkt auf die Inflation [...].",
   "The tax increase will impact inflation directly."),

  ("beanstanden", "Recht & Verwaltung", "Formell",
   "Mängel oder Unregelmäßigkeiten offiziell rügen und anmahnen", "To object to, lodge a complaint against or challenge flaws",
   "Mängel / eine Abrechnung beanstanden", ["kritisieren", "rügen"],
   "Der Bundesrechnungshof beanstandete erhebliche Unregelmäßigkeiten.",
   "Der Bundesrechnungshof [...] erhebliche Unregelmäßigkeiten [...].",
   "The Federal Audit Office objected to substantial irregularities."),

  ("beanspruchen", "Recht & Verwaltung", "Formell",
   "Ein Recht fordern oder Ressourcen zeitlich belasten", "To lay claim to, demand or take up time/attention",
   "das Recht auf / viel Zeit beanspruchen", ["einfordern", "in Anspruch nehmen"],
   "Die Erstellung des Gutachtens beanspruchte mehrere Monate intensiver Arbeit.",
   "Die Erstellung des Gutachtens [...] mehrere Monate intensiver Arbeit [...].",
   "Drafting the assessment took up several months of intensive work."),

  ("beaufsichtigen", "Recht & Verwaltung", "Formell",
   "Kontrollieren, dass Regeln und Standards eingehalten werden", "To supervise, oversee or monitor compliance",
   "den Vorgang / die Wahlen beaufsichtigen", ["kontrollieren", "überwachen"],
   "Internationale Beobachter beaufsichtigten die Präsidentschaftswahlen.",
   "Internationale Beobachter [...] die Präsidentschaftswahlen [...].",
   "International observers supervised the presidential elections."),

  ("beauftragen mit", "Wirtschaft & Arbeit", "Formell",
   "Jemandem offiziell einen Auftrag oder eine Mission erteilen", "To commission, instruct or task someone with an errand",
   "beauftragen mit + Dat.", ["mandatieren", "übertragen"],
   "Das Konsortium wurde mit der Machbarkeitsstudie beauftragt.",
   "Das Konsortium wurde mit der Machbarkeitsstudie [...].",
   "The consortium was commissioned with the feasibility study."),

  ("bedauern", "Psychologie & Kognition", "Formell",
   "Über ein Ereignis oder eine Entscheidung aufrichtig traurig sein", "To regret, deplore or lament an outcome",
   "einen Schritt zutiefst bedauern", ["beklagen", "bereuen"],
   "Die Europäische Union bedauert den Rückzug der Partnerländer zutiefst.",
   "Die Europäische Union [...] den Rückzug der Partnerländer zutiefst.",
   "The European Union deeply regrets the withdrawal of the partner states."),

  ("bedenken", "Psychologie & Kognition", "Bildungssprachlich",
   "Faktoren in Überlegungen einbeziehen oder beschenken", "To bear in mind, consider thoughtfully or bestow a gift",
   "die Konsequenzen bedenken", ["berücksichtigen", "reflektieren"],
   "Man muss bei der Reform auch die Folgen für Senioren bedenken.",
   "Man muss bei der Reform auch die Folgen für Senioren [...].",
   "One must also bear in mind the consequences for senior citizens during reform."),

  ("bedingen", "Wissenschaft & Forschung", "Bildungssprachlich",
   "Als zwingende Ursache oder Bedingung zur Folge haben", "To condition, necessitate, entail or govern causally",
   "gegenseitig bedingen", ["voraussetzen", "verursachen"],
   "Wirtschaftswachstum und ökologische Nachhaltigkeit bedingen einander.",
   "Wirtschaftswachstum und ökologische Nachhaltigkeit [...] einander.",
   "Economic growth and ecological sustainability condition one another."),

  ("bedürfen", "Wissenschaft & Forschung", "Gehoben",
   "Etwas zwingend als Voraussetzung nötig haben (+ Genitiv)", "To require, call for or necessitate (+ genitive)",
   "bedürfen + Gen.", ["benötigen", "erfordern"],
   "Diese bahnbrechende Entdeckung bedarf noch der Bestätigung.",
   "Diese bahnbrechende Entdeckung [...] noch der Bestätigung.",
   "This pioneering discovery still requires rigorous empirical verification."),

  ("befördern", "Wirtschaft & Arbeit", "Bildungssprachlich",
   "Jemanden beruflich befördern oder eine Entwicklung anregen", "To promote a colleague or foster/facilitate growth",
   "den Dialog / Innovation befördern", ["begünstigen", "fördern"],
   "Transparenz befördert das Vertrauen der Bürger in die Institutionen.",
   "Transparenz [...] das Vertrauen der Bürger in die Institutionen.",
   "Transparency fosters citizens' trust in democratic institutions."),

  ("befürworten", "Gesellschaft & Politik", "Formell",
   "Sich ausdrücklich und zustimmend für eine Sache aussprechen", "To advocate, endorse, champion or support a policy",
   "eine Gesetzesänderung befürworten", ["unterstützen", "plädieren für"],
   "Zahlreiche Abgeordnete befürworteten die Einführung der Impfpflicht.",
   "Zahlreiche Abgeordnete [...] die Einführung der Impfpflicht.",
   "Numerous parliamentarians endorsed the introduction of mandatory vaccination."),

  ("begegnen", "Psychologie & Kognition", "Bildungssprachlich",
   "Einer Gefahr oder Kritik entschlossen entgegentreten", "To encounter someone or tackle/counteract a menace (+ Dat.)",
   "einer Krise mit Besonnenheit begegnen (+ Dat.)", ["entgegentreten", "parrieren"],
   "Der Vorstand begegnete den Gerüchten mit größter Gelassenheit.",
   "Der Vorstand [...] den Gerüchten mit größter Gelassenheit.",
   "The executive board countered the rumors with utmost composure."),

  ("begleichen", "Wirtschaft & Arbeit", "Formell",
   "Eine Schuld, offene Rechnung oder Forderung bezahlen", "To settle, discharge or pay off an outstanding bill",
   "eine Rechnung / Schulden begleichen", ["bezahlen", "tilgen"],
   "Der Kunde hat die fälligen Außenstände fristgerecht beglichen.",
   "Der Kunde hat die fälligen Außenstände fristgerecht [...].",
   "The client settled the outstanding invoices within the deadline."),

  ("begründen", "Kommunikation & Diskurs", "Bildungssprachlich",
   "Stichhaltige Argumente liefern oder ein Institut gründen", "To substantiate, give reasons for or establish a tradition",
   "eine These stichhaltig begründen", ["argumentieren", "rechtfertigen"],
   "Die Kommission begründete ihr Votum mit veränderten Rahmenbedingungen.",
   "Die Kommission [...] ihr Votum mit veränderten Rahmenbedingungen.",
   "The commission substantiated its vote with changed framework conditions."),

  ("begünstigen", "Gesellschaft & Politik", "Bildungssprachlich",
   "Vorteile verschaffen oder die Entstehung begünstigen", "To favor, foster or be conducive to an outcome",
   "die Ausbreitung / Korruption begünstigen", ["fördern", "privilegieren"],
   "Mangelnde Kontrollmechanismen begünstigen das Aufkommen von Korruption.",
   "Mangelnde Kontrollmechanismen [...] das Aufkommen von Korruption.",
   "Lack of oversight mechanisms fosters the emergence of corruption."),

  ("beharren auf", "Gesellschaft & Politik", "Bildungssprachlich",
   "Hartnäckig und unnachgiebig auf einer Position bestehen", "To insist stubbornly on, persist in or dig in heels on",
   "beharren auf + Dat.", ["bestehen auf", "festhalten an"],
   "Die Gewerkschaft beharrte kompromisslos auf einer Lohnerhöhung.",
   "Die Gewerkschaft [...] kompromisslos auf einer Lohnerhöhung.",
   "The trade union stubbornly insisted on an eight-percent wage increase."),

  ("beherzigen", "Psychologie & Kognition", "Gehoben",
   "Einen guten Rat oder eine Lehre aufmerksam befolgen", "To take to heart, heed or abide by good advice",
   "einen Rat / Ratschläge beherzigen", ["befolgen", "beachten"],
   "Wer die Ratschläge der Experten beherzigt, minimiert das Anlagerisiko.",
   "Wer die Ratschläge der Experten [...], minimiert das Anlagerisiko.",
   "Whoever heeds the experts' advice minimizes their investment risk.")
]

print(f"Loaded {len(VERBS_300)} initial verbs.")
