// Script to build 300 curated Goethe C1 verbs in modular TypeScript files
const fs = require('fs');
const path = require('path');

// Read raw data and write 3 modular files
// Each file will export 100 typed VocabularyItem objects

const verbsList = [
  // 1-30: Prefix AB-
  ["abbedingen", "Recht & Verwaltung", "Vertraglich ausschließen oder wegbedingen", "To contract out of, waive or legally exclude a statutory entitlement", "Fachsprachlich", "gesetzliche Ansprüche abbedingen", ["ausschließen", "aberkennen", "wegbedingen"], "Im individuellen Arbeitsvertrag ließen sich die tariflichen Mindeststandards keineswegs abbedingen.", "Im individuellen Arbeitsvertrag ließen sich die tariflichen Mindeststandards keineswegs [...].", "Statutory minimum standards could by no means be contracted out of in the individual employment contract."],
  ["abdecken", "Wirtschaft & Arbeit", "Einen Bedarf, ein Themenspektrum oder Kosten vollständig erfassen und finanzieren", "To cover, encompass or satisfy an aggregate demand/cost/topic", "Formell", "den Bedarf / die Gesamtkosten abdecken", ["abgelten", "erfassen", "decken"], "Die bereitgestellten Fördermittel decken die explodierenden Energiekosten der Universitäten nur partiell ab.", "Die bereitgestellten Fördermittel [...] die explodierenden Energiekosten der Universitäten nur partiell [...].", "The provided subsidies only partially cover the exploding energy costs of the universities."],
  ["abfedern", "Gesellschaft & Politik", "Negative Auswirkungen, Schocks oder Härten dämpfen und mildern", "To cushion, absorb or buffer negative impacts/hardships", "Bildungssprachlich", "soziale Härten / die Inflation abfedern", ["dämpfen", "abmildern", "auffangen"], "Die Regierung verabschiedete ein Hilfspaket, um die sozialen Härten der Transformation abzufedern.", "Die Regierung verabschiedete ein Hilfspaket, um die sozialen Härten der Transformation [...].", "The government passed an assistance package to cushion the social hardships of the transformation."],
  ["abfinden mit", "Psychologie & Kognition", "Sich widerstrebend mit einer unangenehmen Gegebenheit resigniert arrangieren", "To resign oneself to; to come to terms with an unpleasant reality", "Bildungssprachlich", "sich abfinden mit + Dat.", ["sich fügen", "resignieren", "sich arrangieren"], "Die Belegschaft wollte sich nicht kampflos mit den geplanten Werksschließungen abfinden.", "Die Belegschaft wollte sich nicht kampflos mit den geplanten Werksschließungen [...].", "The workforce was unwilling to resign itself to the planned plant closures without a fight."],
  ["abgrenzen von", "Wissenschaft & Forschung", "Unterschiede zu anderen Konzepten oder Phänomenen trennscharf definieren", "To demarcate, delineate or distinguish sharply from", "Fachsprachlich", "sich abgrenzen von + Dat.", ["differenzieren", "unterscheiden", "distinguieren"], "In seiner Dissertation grenzte der Forscher den Begriff der Resilienz präzise von psychischer Robustheit ab.", "In seiner Dissertation [...] der Forscher den Begriff der Resilienz präzise von psychischer Robustheit [...].", "In his dissertation, the researcher sharply delineated the concept of resilience from mere mental toughness."],
  ["abhandenkommen", "Psychologie & Kognition", "Verloren gehen; allmählich und unbemerkt schwinden", "To get lost; to misplace; to lose gradually (e.g., trust, sense of reality)", "Gehoben", "jdm. kommt der Realitätssinn abhanden", ["verloren gehen", "entschwinden", "verlieren"], "Im Zuge des permanenten Krisenmanagements ist vielen Führungskräften die langfristige strategische Vision abhandengekommen.", "Im Zuge des permanenten Krisenmanagements ist vielen Führungskräften die langfristige strategische Vision [...].", "In the course of permanent crisis management, many executives have lost their long-term strategic vision."],
  ["abkehren von", "Gesellschaft & Politik", "Eine frühere Überzeugung, Ideologie oder Methode bewusst aufgeben", "To turn away from; to abandon a doctrine, policy or principle", "Gehoben", "sich abkehren von + Dat.", ["ablassen von", "abschwören", "aufgeben"], "Die Wählerschaft kehrte sich demonstrativ von den traditionellen Volksparteien ab.", "Die Wählerschaft [...] sich demonstrativ von den traditionellen Volksparteien [...].", "The electorate demonstratively turned away from the traditional mainstream parties."],
  ["abkommen von", "Kommunikation & Diskurs", "Von einem eingeschlagenen Pfad, Thema oder Grundsatz abweichen", "To stray, deviate from a topic, path or agreed principle", "Gehoben", "vom Thema / vom ursprünglichen Plan abkommen", ["abweichen", "abschweifen", "abirren"], "Während der hitzigen Plenardebatte kam der Redner mehrfach vom eigentlichen Gegenstand ab.", "Während der hitzigen Plenardebatte [...] der Redner mehrfach vom eigentlichen Gegenstand [...].", "During the heated plenary debate, the speaker repeatedly strayed from the actual subject matter."],
  ["abklingen", "Wissenschaft & Forschung", "Allmählich schwächer werden und schließlich ganz aufhören", "To subside, fade away, die down (of symptoms, excitement, applause)", "Bildungssprachlich", "Symptome / eine Euphorie klingt ab", ["nachlassen", "verebben", "schwinden"], "Erst nachdem die akuten Symptome der Entzündung abgeklungen waren, konnte die Reha beginnen.", "Erst nachdem die akuten Symptome der Entzündung [...] waren, konnte die Reha beginnen.", "Only after the acute symptoms of inflammation had subsided could rehabilitation begin."],
  ["ableiten aus", "Wissenschaft & Forschung", "Logisch schlussfolgern oder den Ursprung eines Sachverhalts herleiten", "To deduce, derive from; to trace origins", "Bildungssprachlich", "ableiten aus + Dat.", ["deduzieren", "herleiten", "folgern"], "Aus den empirischen Erhebungen lässt sich ein klarer Kausalzusammenhang ableiten.", "Aus den empirischen Erhebungen lässt sich ein klarer Kausalzusammenhang [...].", "A clear causal relationship can be deduced from the empirical findings."],
  ["abmildern", "Gesellschaft & Politik", "Die Schärfe, Wucht oder Konsequenzen einer Krise verringern", "To alleviate, mitigate or moderate severity", "Formell", "die Folgen / das Urteil abmildern", ["lindern", "abschwächen", "mildern"], "Mit flankierenden Fördermaßnahmen versuchte die Kommission, die Härten für Kleinbauern abzumildern.", "Mit flankierenden Fördermaßnahmen versuchte die Kommission, die Härten für Kleinbauern [...].", "With flanking supportive measures, the commission attempted to mitigate hardships for smallholders."],
  ["abraten von", "Psychologie & Kognition", "Jemandem dringend empfehlen, eine bestimmte Handlung zu unterlassen", "To advise against, dissuade from doing something", "Formell", "abraten von + Dat.", ["warnen vor", "widerraten", "abmahnen"], "Sämtliche Finanzanalysten rieten eindringlich von hochspekulativen Derivatgeschäften ab.", "Sämtliche Finanzanalysten [...] eindringlich von hochspekulativen Derivatgeschäften [...].", "All financial analysts urgently advised against highly speculative derivative transactions."],
  ["absehen von", "Gesellschaft & Politik", "Etwas bewusst unberücksichtigt lassen; von einer Maßnahme oder Sanktion ablassen", "To refrain from; to disregard or dispense with something", "Gehoben", "absehen von + Dat.", ["verzichten auf", "unterlassen", "hinwegsehen über"], "Das Gericht sah im Hinblick auf das Geständnis des Angeklagten von einer Freiheitsstrafe ab.", "Das Gericht [...] im Hinblick auf das Geständnis des Angeklagten von einer Freiheitsstrafe [...].", "In light of the defendant's confession, the court refrained from imposing a prison sentence."],
  ["absprechen", "Gesellschaft & Politik", "Jemandem eine Eigenschaft, Kompetenz oder Berechtigung demonstrativ verwehren", "To deny, dispute or contest someone's competence, right or quality", "Bildungssprachlich", "jdm. die Kompetenz / Legitimität absprechen", ["aberkennen", "bestreiten", "in Abrede stellen"], "Kritiker sprachen dem neu ernannten Gremium jegliche demokratische Legitimität ab.", "Kritiker [...] dem neu ernannten Gremium jegliche demokratische Legitimität [...].", "Critics denied the newly appointed committee any democratic legitimacy."],
  ["abstreiten", "Recht & Verwaltung", "Die Wahrheit einer Behauptung oder Beschuldigung kategorisch leugnen", "To dispute, contest or vehemently deny an allegation", "Formell", "eine Anschuldigung vehement abstreiten", ["leugnen", "dementieren", "zurückweisen"], "Der Zeuge stritt vor dem Untersuchungsausschuss jede Kenntnis von Schmiergeldzahlungen ab.", "Der Zeuge [...] vor dem Untersuchungsausschuss jede Kenntnis von Schmiergeldzahlungen [...].", "Before the committee of inquiry, the witness denied any knowledge of bribery payments."],
  ["abwägen", "Psychologie & Kognition", "Vor- und Nachteile sowie Risiken gründlich und besonnen gegeneinander prüfen", "To weigh up, ponder or carefully balance pros and cons", "Bildungssprachlich", "Chancen und Risiken sorgfältig abwägen", ["evaluieren", "prüfen", "bedenken"], "Vor einem derart folgenschweren Beschluss müssen Vorstand und Betriebsrat alle Optionen sorgfältig abwägen.", "Vor einem derart folgenschweren Beschluss müssen Vorstand und Betriebsrat alle Optionen sorgfältig [...].", "Before such a momentous decision, the executive board and works council must carefully weigh up all options."],
  ["abwälzen auf", "Wirtschaft & Arbeit", "Eine Last, Pflicht oder finanzielle Bürde unangemessen auf andere übertragen", "To shift, offload onto others (costs, blame, burdens)", "Bildungssprachlich", "Kosten / Verantwortung auf Dritte abwälzen", ["übertragen", "delegieren", "abschieben"], "Monopolistische Konzerne neigen dazu, steigende Rohstoffpreise eins zu eins auf die Verbraucher abzuwälzen.", "Monopolistische Konzerne neigen dazu, steigende Rohstoffpreise eins zu eins auf die Verbraucher [...].", "Monopolistic corporations tend to offload rising raw material costs directly onto consumers."],
  ["abwenden", "Gesellschaft & Politik", "Ein drohendes Unheil oder eine akute Krise im Vorfeld verhindern", "To avert, ward off, stave off an impending disaster", "Gehoben", "eine Katastrophe / Schaden abwenden", ["verhindern", "abkehren", "bannen"], "Durch entschlossenes Einschreiten der Zentralbank konnte ein Kollaps des Finanzsystems abgewendet werden.", "Durch entschlossenes Einschreiten der Zentralbank konnte ein Kollaps des Finanzsystems [...] werden.", "Decisive intervention by the central bank succeeded in averting a collapse of the financial system."],
  ["abwickeln", "Wirtschaft & Arbeit", "Ein Geschäft ordnungsgemäß durchführen oder ein marodes Unternehmen auflösen", "To process, conduct a transaction or liquidate/wind up an enterprise", "Fachsprachlich", "ein Geschäft / eine Insolvenz abwickeln", ["durchführen", "liquidieren", "managen"], "Internationale Handelsgeschäfte werden heutzutage vollautomatisiert über digitale Plattformen abgewickelt.", "Internationale Handelsgeschäfte werden heutzutage vollautomatisiert über digitale Plattformen [...].", "International trade transactions are nowadays processed fully automatically via digital platforms."],
  ["abzielen auf", "Wissenschaft & Forschung", "Eine bestimmte Absicht oder Wirkung als konkretes Ziel anstreben", "To aim at, be targeted towards, be designed to achieve", "Bildungssprachlich", "abzielen auf + Akk.", ["intendieren", "anvisieren", "hinauslaufen auf"], "Die Reformmaßnahmen zielen darauf ab, die administrative Bürokratie spürbar zu entschlacken.", "Die Reformmaßnahmen [...] darauf ab, die administrative Bürokratie spürbar zu entschlacken.", "The reform measures aim to streamline administrative bureaucracy noticeably."],
  ["anbelangen", "Kommunikation & Diskurs", "In Bezug auf etwas oder jemanden gelten", "To concern, pertain to (as far as ... is concerned)", "Gehoben", "was [Akk.] anbelangt", ["betreffen", "angehen", "berühren"], "Was die finanzielle Machbarkeit anbelangt, so bestehen nach wie vor gravierende Zweifel im Beirat.", "Was die finanzielle Machbarkeit [...], so bestehen nach wie vor gravierende Zweifel im Beirat.", "As far as financial feasibility is concerned, serious doubts remain within the advisory board."],
  ["anberaumen", "Recht & Verwaltung", "Einen offiziellen Termin für eine Versammlung oder Gerichtsverhandlung festsetzen", "To schedule, convene or fix a formal date/meeting", "Formell", "eine Sitzung / einen Gerichtstermin anberaumen", ["ansetzen", "terminieren", "einberufen"], "Das Bundesverfassungsgericht beraumte die mündliche Verhandlung für Ende November an.", "Das Bundesverfassungsgericht [...] die mündliche Verhandlung für Ende November [...].", "The Federal Constitutional Court scheduled the oral hearing for late November."],
  ["anfechten", "Recht & Verwaltung", "Die rechtliche Gültigkeit einer Wahl, Klausel oder Entscheidung juristisch bestreiten", "To challenge, contest or dispute legally (a verdict, election, will)", "Fachsprachlich", "ein Urteil / eine Wahl anfechten", ["beeinspruchen", "beklagen", "bestreiten"], "Die unterlegene Partei kündigte umgehend an, das umstrittene Wahlergebnis gerichtlich anzufechten.", "Die unterlegene Partei kündigte umgehend an, das umstrittene Wahlergebnis gerichtlich [...].", "The defeated party immediately announced it would legally challenge the disputed election result."],
  ["anfordern", "Recht & Verwaltung", "Offiziell und nachdrücklich die Zusendung von Unterlagen verlangen", "To request formally, requisition or summon resources", "Formell", "Unterlagen / Verstärkung anfordern", ["verlangen", "beantragen", "erbitten"], "Die Staatsanwaltschaft forderte die vollständigen Geschäftsberichte der letzten fünf Jahre an.", "Die Staatsanwaltschaft [...] die vollständigen Geschäftsberichte der letzten fünf Jahre [...].", "The public prosecutor's office formally requested the full annual financial reports of the last five years."],
  ["anführen", "Kommunikation & Diskurs", "Argumente, Beispiele oder Quellen als Beleg zitieren", "To cite, quote, adduce evidence or lead an organization", "Bildungssprachlich", "Belege / Zeugen ins Feld führen / anführen", ["zitieren", "vorbringen", "nennen"], "Zur Untermauerung seiner provokanten These führte der Soziologe zahlreiche historische Präzedenzfälle an.", "Zur Untermauerung seiner provokanten These [...] der Soziologe zahlreiche historische Präzedenzfälle [...].", "To substantiate his provocative thesis, the sociologist cited numerous historical precedents."],
  ["angleichen an", "Gesellschaft & Politik", "Bestehende Unterschiede stufenweise beseitigen, bis Gleichförmigkeit herrscht", "To align with, harmonize or assimilate to a standard", "Formell", "angleichen an + Akk.", ["harmonisieren", "anpassen", "assimilieren"], "Ziel der EU-Richtlinie ist es, die nationalen Umweltstandards sukzessive aneinander anzugleichen.", "Ziel der EU-Richtlinie ist es, die nationalen Umweltstandards sukzessive aneinander [...].", "The aim of the EU directive is to gradually align national environmental standards with one another."],
  ["anknüpfen an", "Wissenschaft & Forschung", "Thematisch oder methodisch an frühere Erkenntnisse oder Traditionen anschließen", "To build upon, pick up on or connect with previous work", "Bildungssprachlich", "anknüpfen an + Akk.", ["fortführen", "anschließen an", "aufgreifen"], "Die jüngste Versuchsreihe knüpft nahtlos an die bahnbrechenden Resultate des Vorjahres an.", "Die jüngste Versuchsreihe [...] nahtlos an die bahnbrechenden Resultate des Vorjahres [...].", "The latest series of experiments connects seamlessly with the pioneering findings of the previous year."],
  ["anlasten", "Recht & Verwaltung", "Jemandem die moralische oder juristische Schuld für ein Vergehen zuschreiben", "To blame someone for, hold responsible or impute fault to someone", "Gehoben", "jdm. ein Versäumnis anlasten", ["vorwerfen", "zuschreiben", "beschuldigen"], "Man kann der neuen Abteilungsleitung die historischen Fehlplanungen ihrer Vorgänger nicht anlasten.", "Man kann der neuen Abteilungsleitung die historischen Fehlplanungen ihrer Vorgänger nicht [...].", "One cannot hold the new departmental management responsible for the historic miscalculations of its predecessors."],
  ["anmahnen", "Gesellschaft & Politik", "Auf fällige Pflichten, Fristen oder längst überfällige Reformen nachdrücklich pochen", "To urge, admonish or press for overdue compliance/action", "Gehoben", "Reformen / Einhaltung der Fristen anmahnen", ["einfordern", "ermahnen", "urgieren"], "Internationale Menschenrechtsorganisationen mahnten wiederholt den Schutz verfolgter Minderheiten an.", "Internationale Menschenrechtsorganisationen [...] wiederholt den Schutz verfolgter Minderheiten [...].", "International human rights organizations repeatedly urged the protection of persecuted minorities."],
  ["anmuten", "Psychologie & Kognition", "Auf das Gemüt oder den Betrachter in bestimmter Weise wirken", "To appear, strike someone as, seem curious/bizarre", "Gehoben", "seltsam / archaisch anmuten", ["wirken wie", "scheinen", "erscheinen"], "Aus heutiger Sicht mutet diese rigide bürokratische Vorschrift beinahe absurd an.", "Aus heutiger Sicht [...] diese rigide bürokratische Vorschrift beinahe absurd [...].", "From today's perspective, this rigid bureaucratic regulation seems almost absurd."]
];

console.log("Seed count:", verbsList.length);
